// Code generated by `ubx sdk gen` from azurerm_mysql_flexible_database. DO NOT EDIT.
package mysql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FlexibleDatabase_Timeouts struct {
	Create any
	Delete any
	Read any
}

var FlexibleDatabase_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type FlexibleDatabaseConfig struct {
	Charset any
	Collation any
	Id any
	Name any
	ResourceGroupName any
	ServerName any
	Timeouts any
}

var FlexibleDatabase = sdk.ResourceBinding{
	WireType: "azurerm_mysql_flexible_database",
	Fields: sdk.FieldMap{
		"Charset": sdk.FieldSpec{WireName: "charset"},
		"Collation": sdk.FieldSpec{WireName: "collation"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ServerName": sdk.FieldSpec{WireName: "server_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FlexibleDatabase_TimeoutsFields,
		},
	},
}
