// Code generated by `ubx sdk gen` from azurerm_cosmosdb_cassandra_cluster. DO NOT EDIT.
package cosmosdb

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CassandraCluster_Identity struct {
	PrincipalId any
	TenantId any
	Type any
}

type CassandraCluster_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CassandraCluster_IdentityFields = sdk.FieldMap{
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var CassandraCluster_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CassandraClusterConfig struct {
	AuthenticationMethod any
	ClientCertificatePems any
	DefaultAdminPassword any
	DelegatedManagementSubnetId any
	ExternalGossipCertificatePems any
	ExternalSeedNodeIpAddresses any
	HoursBetweenBackups any
	Id any
	Location any
	Name any
	RepairEnabled any
	ResourceGroupName any
	Tags any
	Version any
	Identity any
	Timeouts any
}

var CassandraCluster = sdk.ResourceBinding{
	WireType: "azurerm_cosmosdb_cassandra_cluster",
	Fields: sdk.FieldMap{
		"AuthenticationMethod": sdk.FieldSpec{WireName: "authentication_method"},
		"ClientCertificatePems": sdk.FieldSpec{WireName: "client_certificate_pems"},
		"DefaultAdminPassword": sdk.FieldSpec{WireName: "default_admin_password"},
		"DelegatedManagementSubnetId": sdk.FieldSpec{WireName: "delegated_management_subnet_id"},
		"ExternalGossipCertificatePems": sdk.FieldSpec{WireName: "external_gossip_certificate_pems"},
		"ExternalSeedNodeIpAddresses": sdk.FieldSpec{WireName: "external_seed_node_ip_addresses"},
		"HoursBetweenBackups": sdk.FieldSpec{WireName: "hours_between_backups"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RepairEnabled": sdk.FieldSpec{WireName: "repair_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Version": sdk.FieldSpec{WireName: "version"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: CassandraCluster_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CassandraCluster_TimeoutsFields,
		},
	},
}
