// Code generated by `ubx sdk gen` from azurerm_cosmosdb_gremlin_graph. DO NOT EDIT.
package cosmosdb

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type GremlinGraph_AutoscaleSettings struct {
	MaxThroughput any
}

type GremlinGraph_ConflictResolutionPolicy struct {
	ConflictResolutionPath any
	ConflictResolutionProcedure any
	Mode any
}

type GremlinGraph_IndexPolicy_CompositeIndex_Index struct {
	Order any
	Path any
}

type GremlinGraph_IndexPolicy_CompositeIndex struct {
	Index any
}

type GremlinGraph_IndexPolicy_SpatialIndex struct {
	Path any
	Types any
}

type GremlinGraph_IndexPolicy struct {
	Automatic any
	ExcludedPaths any
	IncludedPaths any
	IndexingMode any
	CompositeIndex any
	SpatialIndex any
}

type GremlinGraph_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type GremlinGraph_UniqueKey struct {
	Paths any
}

var GremlinGraph_AutoscaleSettingsFields = sdk.FieldMap{
		"MaxThroughput": sdk.FieldSpec{WireName: "max_throughput"},
	}

var GremlinGraph_ConflictResolutionPolicyFields = sdk.FieldMap{
		"ConflictResolutionPath": sdk.FieldSpec{WireName: "conflict_resolution_path"},
		"ConflictResolutionProcedure": sdk.FieldSpec{WireName: "conflict_resolution_procedure"},
		"Mode": sdk.FieldSpec{WireName: "mode"},
	}

var GremlinGraph_IndexPolicy_CompositeIndex_IndexFields = sdk.FieldMap{
		"Order": sdk.FieldSpec{WireName: "order"},
		"Path": sdk.FieldSpec{WireName: "path"},
	}

var GremlinGraph_IndexPolicy_CompositeIndexFields = sdk.FieldMap{
		"Index": sdk.FieldSpec{
			WireName: "index",
			Kind: "list",
			Fields: GremlinGraph_IndexPolicy_CompositeIndex_IndexFields,
		},
	}

var GremlinGraph_IndexPolicy_SpatialIndexFields = sdk.FieldMap{
		"Path": sdk.FieldSpec{WireName: "path"},
		"Types": sdk.FieldSpec{WireName: "types"},
	}

var GremlinGraph_IndexPolicyFields = sdk.FieldMap{
		"Automatic": sdk.FieldSpec{WireName: "automatic"},
		"ExcludedPaths": sdk.FieldSpec{WireName: "excluded_paths"},
		"IncludedPaths": sdk.FieldSpec{WireName: "included_paths"},
		"IndexingMode": sdk.FieldSpec{WireName: "indexing_mode"},
		"CompositeIndex": sdk.FieldSpec{
			WireName: "composite_index",
			Kind: "list",
			Fields: GremlinGraph_IndexPolicy_CompositeIndexFields,
		},
		"SpatialIndex": sdk.FieldSpec{
			WireName: "spatial_index",
			Kind: "list",
			Fields: GremlinGraph_IndexPolicy_SpatialIndexFields,
		},
	}

var GremlinGraph_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var GremlinGraph_UniqueKeyFields = sdk.FieldMap{
		"Paths": sdk.FieldSpec{WireName: "paths"},
	}

type GremlinGraphConfig struct {
	AccountName any
	AnalyticalStorageTtl any
	DatabaseName any
	DefaultTtl any
	Id any
	Name any
	PartitionKeyPath any
	PartitionKeyVersion any
	ResourceGroupName any
	Throughput any
	AutoscaleSettings any
	ConflictResolutionPolicy any
	IndexPolicy any
	Timeouts any
	UniqueKey any
}

var GremlinGraph = sdk.ResourceBinding{
	WireType: "azurerm_cosmosdb_gremlin_graph",
	Fields: sdk.FieldMap{
		"AccountName": sdk.FieldSpec{WireName: "account_name"},
		"AnalyticalStorageTtl": sdk.FieldSpec{WireName: "analytical_storage_ttl"},
		"DatabaseName": sdk.FieldSpec{WireName: "database_name"},
		"DefaultTtl": sdk.FieldSpec{WireName: "default_ttl"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PartitionKeyPath": sdk.FieldSpec{WireName: "partition_key_path"},
		"PartitionKeyVersion": sdk.FieldSpec{WireName: "partition_key_version"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Throughput": sdk.FieldSpec{WireName: "throughput"},
		"AutoscaleSettings": sdk.FieldSpec{
			WireName: "autoscale_settings",
			Kind: "list",
			Fields: GremlinGraph_AutoscaleSettingsFields,
		},
		"ConflictResolutionPolicy": sdk.FieldSpec{
			WireName: "conflict_resolution_policy",
			Kind: "list",
			Fields: GremlinGraph_ConflictResolutionPolicyFields,
		},
		"IndexPolicy": sdk.FieldSpec{
			WireName: "index_policy",
			Kind: "list",
			Fields: GremlinGraph_IndexPolicyFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: GremlinGraph_TimeoutsFields,
		},
		"UniqueKey": sdk.FieldSpec{
			WireName: "unique_key",
			Kind: "set",
			Fields: GremlinGraph_UniqueKeyFields,
		},
	},
}
