// Code generated by `ubx sdk gen` from azurerm_cosmosdb_mongo_user_definition. DO NOT EDIT.
package cosmosdb

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type MongoUserDefinition_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var MongoUserDefinition_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type MongoUserDefinitionConfig struct {
	CosmosMongoDatabaseId any
	Id any
	InheritedRoleNames any
	Password any
	Username any
	Timeouts any
}

var MongoUserDefinition = sdk.ResourceBinding{
	WireType: "azurerm_cosmosdb_mongo_user_definition",
	Fields: sdk.FieldMap{
		"CosmosMongoDatabaseId": sdk.FieldSpec{WireName: "cosmos_mongo_database_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"InheritedRoleNames": sdk.FieldSpec{WireName: "inherited_role_names"},
		"Password": sdk.FieldSpec{WireName: "password"},
		"Username": sdk.FieldSpec{WireName: "username"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: MongoUserDefinition_TimeoutsFields,
		},
	},
}
