// Code generated by `ubx sdk gen` from azurerm_api_management_product_api. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementProductApi_Timeouts struct {
	Create any
	Delete any
	Read any
}

var ManagementProductApi_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type ManagementProductApiConfig struct {
	ApiManagementName any
	ApiName any
	Id any
	ProductId any
	ResourceGroupName any
	Timeouts any
}

var ManagementProductApi = sdk.ResourceBinding{
	WireType: "azurerm_api_management_product_api",
	Fields: sdk.FieldMap{
		"ApiManagementName": sdk.FieldSpec{WireName: "api_management_name"},
		"ApiName": sdk.FieldSpec{WireName: "api_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ProductId": sdk.FieldSpec{WireName: "product_id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementProductApi_TimeoutsFields,
		},
	},
}
