// Code generated by `ubx sdk gen` from azurerm_api_management_identity_provider_microsoft. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementIdentityProviderMicrosoft_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementIdentityProviderMicrosoft_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementIdentityProviderMicrosoftConfig struct {
	ApiManagementName any
	ClientId any
	ClientSecret any
	Id any
	ResourceGroupName any
	Timeouts any
}

var ManagementIdentityProviderMicrosoft = sdk.ResourceBinding{
	WireType: "azurerm_api_management_identity_provider_microsoft",
	Fields: sdk.FieldMap{
		"ApiManagementName": sdk.FieldSpec{WireName: "api_management_name"},
		"ClientId": sdk.FieldSpec{WireName: "client_id"},
		"ClientSecret": sdk.FieldSpec{WireName: "client_secret"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementIdentityProviderMicrosoft_TimeoutsFields,
		},
	},
}
