// Code generated by `ubx sdk gen` from azurerm_api_management_gateway_certificate_authority. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementGatewayCertificateAuthority_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementGatewayCertificateAuthority_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementGatewayCertificateAuthorityConfig struct {
	ApiManagementId any
	CertificateName any
	GatewayName any
	Id any
	IsTrusted any
	Timeouts any
}

var ManagementGatewayCertificateAuthority = sdk.ResourceBinding{
	WireType: "azurerm_api_management_gateway_certificate_authority",
	Fields: sdk.FieldMap{
		"ApiManagementId": sdk.FieldSpec{WireName: "api_management_id"},
		"CertificateName": sdk.FieldSpec{WireName: "certificate_name"},
		"GatewayName": sdk.FieldSpec{WireName: "gateway_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IsTrusted": sdk.FieldSpec{WireName: "is_trusted"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementGatewayCertificateAuthority_TimeoutsFields,
		},
	},
}
