// Code generated by `ubx sdk gen` from azurerm_api_management_api_tag_description. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementApiTagDescription_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementApiTagDescription_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementApiTagDescriptionConfig struct {
	ApiTagId any
	Description any
	ExternalDocumentationDescription any
	ExternalDocumentationUrl any
	Id any
	Timeouts any
}

var ManagementApiTagDescription = sdk.ResourceBinding{
	WireType: "azurerm_api_management_api_tag_description",
	Fields: sdk.FieldMap{
		"ApiTagId": sdk.FieldSpec{WireName: "api_tag_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"ExternalDocumentationDescription": sdk.FieldSpec{WireName: "external_documentation_description"},
		"ExternalDocumentationUrl": sdk.FieldSpec{WireName: "external_documentation_url"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementApiTagDescription_TimeoutsFields,
		},
	},
}
