// Code generated by `ubx sdk gen` from azurerm_api_management_workspace_policy_fragment. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementWorkspacePolicyFragment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementWorkspacePolicyFragment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementWorkspacePolicyFragmentConfig struct {
	ApiManagementWorkspaceId any
	Description any
	Id any
	Name any
	XmlContent any
	XmlFormat any
	Timeouts any
}

var ManagementWorkspacePolicyFragment = sdk.ResourceBinding{
	WireType: "azurerm_api_management_workspace_policy_fragment",
	Fields: sdk.FieldMap{
		"ApiManagementWorkspaceId": sdk.FieldSpec{WireName: "api_management_workspace_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"XmlContent": sdk.FieldSpec{WireName: "xml_content"},
		"XmlFormat": sdk.FieldSpec{WireName: "xml_format"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementWorkspacePolicyFragment_TimeoutsFields,
		},
	},
}
