// Code generated by `ubx sdk gen` from azurerm_api_management_api_version_set. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementApiVersionSet_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementApiVersionSet_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementApiVersionSetConfig struct {
	ApiManagementName any
	Description any
	DisplayName any
	Id any
	Name any
	ResourceGroupName any
	VersionHeaderName any
	VersionQueryName any
	VersioningScheme any
	Timeouts any
}

var ManagementApiVersionSet = sdk.ResourceBinding{
	WireType: "azurerm_api_management_api_version_set",
	Fields: sdk.FieldMap{
		"ApiManagementName": sdk.FieldSpec{WireName: "api_management_name"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"VersionHeaderName": sdk.FieldSpec{WireName: "version_header_name"},
		"VersionQueryName": sdk.FieldSpec{WireName: "version_query_name"},
		"VersioningScheme": sdk.FieldSpec{WireName: "versioning_scheme"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementApiVersionSet_TimeoutsFields,
		},
	},
}
