// Code generated by `ubx sdk gen` from azurerm_api_management_policy. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementPolicyConfig struct {
	ApiManagementId any
	Id any
	XmlContent any
	XmlLink any
	Timeouts any
}

var ManagementPolicy = sdk.ResourceBinding{
	WireType: "azurerm_api_management_policy",
	Fields: sdk.FieldMap{
		"ApiManagementId": sdk.FieldSpec{WireName: "api_management_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"XmlContent": sdk.FieldSpec{WireName: "xml_content"},
		"XmlLink": sdk.FieldSpec{WireName: "xml_link"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementPolicy_TimeoutsFields,
		},
	},
}
