// Code generated by `ubx sdk gen` from azurerm_api_management_backend. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementBackend_CircuitBreakerRule_FailureCondition_StatusCodeRange struct {
	Max any
	Min any
}

type ManagementBackend_CircuitBreakerRule_FailureCondition struct {
	Count any
	ErrorReasons any
	IntervalDuration any
	Percentage any
	StatusCodeRange any
}

type ManagementBackend_CircuitBreakerRule struct {
	AcceptRetryAfterEnabled any
	Name any
	TripDuration any
	FailureCondition any
}

type ManagementBackend_Credentials_Authorization struct {
	Parameter any
	Scheme any
}

type ManagementBackend_Credentials struct {
	Certificate any
	Header any
	Query any
	Authorization any
}

type ManagementBackend_Proxy struct {
	Password any
	Url any
	Username any
}

type ManagementBackend_ServiceFabricCluster_ServerX509Name struct {
	IssuerCertificateThumbprint any
	Name any
}

type ManagementBackend_ServiceFabricCluster struct {
	ClientCertificateId any
	ClientCertificateThumbprint any
	ManagementEndpoints any
	MaxPartitionResolutionRetries any
	ServerCertificateThumbprints any
	ServerX509Name any
}

type ManagementBackend_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type ManagementBackend_Tls struct {
	ValidateCertificateChain any
	ValidateCertificateName any
}

var ManagementBackend_CircuitBreakerRule_FailureCondition_StatusCodeRangeFields = sdk.FieldMap{
		"Max": sdk.FieldSpec{WireName: "max"},
		"Min": sdk.FieldSpec{WireName: "min"},
	}

var ManagementBackend_CircuitBreakerRule_FailureConditionFields = sdk.FieldMap{
		"Count": sdk.FieldSpec{WireName: "count"},
		"ErrorReasons": sdk.FieldSpec{WireName: "error_reasons"},
		"IntervalDuration": sdk.FieldSpec{WireName: "interval_duration"},
		"Percentage": sdk.FieldSpec{WireName: "percentage"},
		"StatusCodeRange": sdk.FieldSpec{
			WireName: "status_code_range",
			Kind: "list",
			Fields: ManagementBackend_CircuitBreakerRule_FailureCondition_StatusCodeRangeFields,
		},
	}

var ManagementBackend_CircuitBreakerRuleFields = sdk.FieldMap{
		"AcceptRetryAfterEnabled": sdk.FieldSpec{WireName: "accept_retry_after_enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"TripDuration": sdk.FieldSpec{WireName: "trip_duration"},
		"FailureCondition": sdk.FieldSpec{
			WireName: "failure_condition",
			Kind: "list",
			Fields: ManagementBackend_CircuitBreakerRule_FailureConditionFields,
		},
	}

var ManagementBackend_Credentials_AuthorizationFields = sdk.FieldMap{
		"Parameter": sdk.FieldSpec{WireName: "parameter"},
		"Scheme": sdk.FieldSpec{WireName: "scheme"},
	}

var ManagementBackend_CredentialsFields = sdk.FieldMap{
		"Certificate": sdk.FieldSpec{WireName: "certificate"},
		"Header": sdk.FieldSpec{WireName: "header"},
		"Query": sdk.FieldSpec{WireName: "query"},
		"Authorization": sdk.FieldSpec{
			WireName: "authorization",
			Kind: "list",
			Fields: ManagementBackend_Credentials_AuthorizationFields,
		},
	}

var ManagementBackend_ProxyFields = sdk.FieldMap{
		"Password": sdk.FieldSpec{WireName: "password"},
		"Url": sdk.FieldSpec{WireName: "url"},
		"Username": sdk.FieldSpec{WireName: "username"},
	}

var ManagementBackend_ServiceFabricCluster_ServerX509NameFields = sdk.FieldMap{
		"IssuerCertificateThumbprint": sdk.FieldSpec{WireName: "issuer_certificate_thumbprint"},
		"Name": sdk.FieldSpec{WireName: "name"},
	}

var ManagementBackend_ServiceFabricClusterFields = sdk.FieldMap{
		"ClientCertificateId": sdk.FieldSpec{WireName: "client_certificate_id"},
		"ClientCertificateThumbprint": sdk.FieldSpec{WireName: "client_certificate_thumbprint"},
		"ManagementEndpoints": sdk.FieldSpec{WireName: "management_endpoints"},
		"MaxPartitionResolutionRetries": sdk.FieldSpec{WireName: "max_partition_resolution_retries"},
		"ServerCertificateThumbprints": sdk.FieldSpec{WireName: "server_certificate_thumbprints"},
		"ServerX509Name": sdk.FieldSpec{
			WireName: "server_x509_name",
			Kind: "set",
			Fields: ManagementBackend_ServiceFabricCluster_ServerX509NameFields,
		},
	}

var ManagementBackend_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var ManagementBackend_TlsFields = sdk.FieldMap{
		"ValidateCertificateChain": sdk.FieldSpec{WireName: "validate_certificate_chain"},
		"ValidateCertificateName": sdk.FieldSpec{WireName: "validate_certificate_name"},
	}

type ManagementBackendConfig struct {
	ApiManagementName any
	Description any
	Id any
	Name any
	Protocol any
	ResourceGroupName any
	ResourceId any
	Title any
	Url any
	CircuitBreakerRule any
	Credentials any
	Proxy any
	ServiceFabricCluster any
	Timeouts any
	Tls any
}

var ManagementBackend = sdk.ResourceBinding{
	WireType: "azurerm_api_management_backend",
	Fields: sdk.FieldMap{
		"ApiManagementName": sdk.FieldSpec{WireName: "api_management_name"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Protocol": sdk.FieldSpec{WireName: "protocol"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ResourceId": sdk.FieldSpec{WireName: "resource_id"},
		"Title": sdk.FieldSpec{WireName: "title"},
		"Url": sdk.FieldSpec{WireName: "url"},
		"CircuitBreakerRule": sdk.FieldSpec{
			WireName: "circuit_breaker_rule",
			Kind: "list",
			Fields: ManagementBackend_CircuitBreakerRuleFields,
		},
		"Credentials": sdk.FieldSpec{
			WireName: "credentials",
			Kind: "list",
			Fields: ManagementBackend_CredentialsFields,
		},
		"Proxy": sdk.FieldSpec{
			WireName: "proxy",
			Kind: "list",
			Fields: ManagementBackend_ProxyFields,
		},
		"ServiceFabricCluster": sdk.FieldSpec{
			WireName: "service_fabric_cluster",
			Kind: "list",
			Fields: ManagementBackend_ServiceFabricClusterFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementBackend_TimeoutsFields,
		},
		"Tls": sdk.FieldSpec{
			WireName: "tls",
			Kind: "list",
			Fields: ManagementBackend_TlsFields,
		},
	},
}
