// Code generated by `ubx sdk gen` from azurerm_api_management_identity_provider_aad. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementIdentityProviderAad_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementIdentityProviderAad_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementIdentityProviderAadConfig struct {
	AllowedTenants any
	ApiManagementName any
	ClientId any
	ClientLibrary any
	ClientSecret any
	Id any
	ResourceGroupName any
	SigninTenant any
	Timeouts any
}

var ManagementIdentityProviderAad = sdk.ResourceBinding{
	WireType: "azurerm_api_management_identity_provider_aad",
	Fields: sdk.FieldMap{
		"AllowedTenants": sdk.FieldSpec{WireName: "allowed_tenants"},
		"ApiManagementName": sdk.FieldSpec{WireName: "api_management_name"},
		"ClientId": sdk.FieldSpec{WireName: "client_id"},
		"ClientLibrary": sdk.FieldSpec{WireName: "client_library"},
		"ClientSecret": sdk.FieldSpec{WireName: "client_secret"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SigninTenant": sdk.FieldSpec{WireName: "signin_tenant"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementIdentityProviderAad_TimeoutsFields,
		},
	},
}
