// Code generated by `ubx sdk gen` from azurerm_api_management_identity_provider_facebook. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementIdentityProviderFacebook_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementIdentityProviderFacebook_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementIdentityProviderFacebookConfig struct {
	ApiManagementName any
	AppId any
	AppSecret any
	Id any
	ResourceGroupName any
	Timeouts any
}

var ManagementIdentityProviderFacebook = sdk.ResourceBinding{
	WireType: "azurerm_api_management_identity_provider_facebook",
	Fields: sdk.FieldMap{
		"ApiManagementName": sdk.FieldSpec{WireName: "api_management_name"},
		"AppId": sdk.FieldSpec{WireName: "app_id"},
		"AppSecret": sdk.FieldSpec{WireName: "app_secret"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementIdentityProviderFacebook_TimeoutsFields,
		},
	},
}
