// Code generated by `ubx sdk gen` from azurerm_api_management_policy_fragment. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementPolicyFragment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementPolicyFragment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementPolicyFragmentConfig struct {
	ApiManagementId any
	Description any
	Format any
	Id any
	Name any
	Value any
	Timeouts any
}

var ManagementPolicyFragment = sdk.ResourceBinding{
	WireType: "azurerm_api_management_policy_fragment",
	Fields: sdk.FieldMap{
		"ApiManagementId": sdk.FieldSpec{WireName: "api_management_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Format": sdk.FieldSpec{WireName: "format"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Value": sdk.FieldSpec{WireName: "value"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementPolicyFragment_TimeoutsFields,
		},
	},
}
