// Code generated by `ubx sdk gen` from azurerm_api_management_email_template. DO NOT EDIT.
package api

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementEmailTemplate_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementEmailTemplate_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementEmailTemplateConfig struct {
	ApiManagementName any
	Body any
	Id any
	ResourceGroupName any
	Subject any
	TemplateName any
	Timeouts any
}

var ManagementEmailTemplate = sdk.ResourceBinding{
	WireType: "azurerm_api_management_email_template",
	Fields: sdk.FieldMap{
		"ApiManagementName": sdk.FieldSpec{WireName: "api_management_name"},
		"Body": sdk.FieldSpec{WireName: "body"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Subject": sdk.FieldSpec{WireName: "subject"},
		"TemplateName": sdk.FieldSpec{WireName: "template_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementEmailTemplate_TimeoutsFields,
		},
	},
}
