// Code generated by `ubx sdk gen` from azurerm_application_insights_analytics_item. DO NOT EDIT.
package application

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type InsightsAnalyticsItem_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var InsightsAnalyticsItem_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type InsightsAnalyticsItemConfig struct {
	ApplicationInsightsId any
	Content any
	FunctionAlias any
	Id any
	Name any
	Scope any
	Type any
	Timeouts any
}

var InsightsAnalyticsItem = sdk.ResourceBinding{
	WireType: "azurerm_application_insights_analytics_item",
	Fields: sdk.FieldMap{
		"ApplicationInsightsId": sdk.FieldSpec{WireName: "application_insights_id"},
		"Content": sdk.FieldSpec{WireName: "content"},
		"FunctionAlias": sdk.FieldSpec{WireName: "function_alias"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Scope": sdk.FieldSpec{WireName: "scope"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: InsightsAnalyticsItem_TimeoutsFields,
		},
	},
}
