// Code generated by `ubx sdk gen` from azurerm_application_insights_api_key. DO NOT EDIT.
package application

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type InsightsApiKey_Timeouts struct {
	Create any
	Delete any
	Read any
}

var InsightsApiKey_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type InsightsApiKeyConfig struct {
	ApplicationInsightsId any
	Id any
	Name any
	ReadPermissions any
	WritePermissions any
	Timeouts any
}

var InsightsApiKey = sdk.ResourceBinding{
	WireType: "azurerm_application_insights_api_key",
	Fields: sdk.FieldMap{
		"ApplicationInsightsId": sdk.FieldSpec{WireName: "application_insights_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ReadPermissions": sdk.FieldSpec{WireName: "read_permissions"},
		"WritePermissions": sdk.FieldSpec{WireName: "write_permissions"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: InsightsApiKey_TimeoutsFields,
		},
	},
}
