// Code generated by `ubx sdk gen` from azurerm_application_load_balancer_security_policy. DO NOT EDIT.
package application

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type LoadBalancerSecurityPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var LoadBalancerSecurityPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type LoadBalancerSecurityPolicyConfig struct {
	ApplicationLoadBalancerId any
	Id any
	Location any
	Name any
	Tags any
	WebApplicationFirewallPolicyId any
	Timeouts any
}

var LoadBalancerSecurityPolicy = sdk.ResourceBinding{
	WireType: "azurerm_application_load_balancer_security_policy",
	Fields: sdk.FieldMap{
		"ApplicationLoadBalancerId": sdk.FieldSpec{WireName: "application_load_balancer_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"WebApplicationFirewallPolicyId": sdk.FieldSpec{WireName: "web_application_firewall_policy_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: LoadBalancerSecurityPolicy_TimeoutsFields,
		},
	},
}
