// Code generated by `ubx sdk gen` from azurerm_postgresql_flexible_server_active_directory_administrator. DO NOT EDIT.
package postgresql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FlexibleServerActiveDirectoryAdministrator_Timeouts struct {
	Create any
	Delete any
	Read any
}

var FlexibleServerActiveDirectoryAdministrator_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type FlexibleServerActiveDirectoryAdministratorConfig struct {
	Id any
	ObjectId any
	PrincipalName any
	PrincipalType any
	ResourceGroupName any
	ServerName any
	TenantId any
	Timeouts any
}

var FlexibleServerActiveDirectoryAdministrator = sdk.ResourceBinding{
	WireType: "azurerm_postgresql_flexible_server_active_directory_administrator",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"ObjectId": sdk.FieldSpec{WireName: "object_id"},
		"PrincipalName": sdk.FieldSpec{WireName: "principal_name"},
		"PrincipalType": sdk.FieldSpec{WireName: "principal_type"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ServerName": sdk.FieldSpec{WireName: "server_name"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FlexibleServerActiveDirectoryAdministrator_TimeoutsFields,
		},
	},
}
