// Code generated by `ubx sdk gen` from azurerm_postgresql_flexible_server_firewall_rule. DO NOT EDIT.
package postgresql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FlexibleServerFirewallRule_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FlexibleServerFirewallRule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FlexibleServerFirewallRuleConfig struct {
	EndIpAddress any
	Id any
	Name any
	ServerId any
	StartIpAddress any
	Timeouts any
}

var FlexibleServerFirewallRule = sdk.ResourceBinding{
	WireType: "azurerm_postgresql_flexible_server_firewall_rule",
	Fields: sdk.FieldMap{
		"EndIpAddress": sdk.FieldSpec{WireName: "end_ip_address"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ServerId": sdk.FieldSpec{WireName: "server_id"},
		"StartIpAddress": sdk.FieldSpec{WireName: "start_ip_address"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FlexibleServerFirewallRule_TimeoutsFields,
		},
	},
}
