// Code generated by `ubx sdk gen` from azurerm_postgresql_flexible_server_backup. DO NOT EDIT.
package postgresql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FlexibleServerBackup_Timeouts struct {
	Create any
	Delete any
	Read any
}

var FlexibleServerBackup_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type FlexibleServerBackupConfig struct {
	Id any
	Name any
	ServerId any
	Timeouts any
}

var FlexibleServerBackup = sdk.ResourceBinding{
	WireType: "azurerm_postgresql_flexible_server_backup",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ServerId": sdk.FieldSpec{WireName: "server_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FlexibleServerBackup_TimeoutsFields,
		},
	},
}
