// Code generated by `ubx sdk gen` from azurerm_netapp_account_encryption. DO NOT EDIT.
package netapp

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AccountEncryption_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AccountEncryption_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AccountEncryptionConfig struct {
	CrossTenantKeyVaultResourceId any
	EncryptionKey any
	FederatedClientId any
	Id any
	NetappAccountId any
	SystemAssignedIdentityPrincipalId any
	UserAssignedIdentityId any
	Timeouts any
}

var AccountEncryption = sdk.ResourceBinding{
	WireType: "azurerm_netapp_account_encryption",
	Fields: sdk.FieldMap{
		"CrossTenantKeyVaultResourceId": sdk.FieldSpec{WireName: "cross_tenant_key_vault_resource_id"},
		"EncryptionKey": sdk.FieldSpec{WireName: "encryption_key"},
		"FederatedClientId": sdk.FieldSpec{WireName: "federated_client_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"NetappAccountId": sdk.FieldSpec{WireName: "netapp_account_id"},
		"SystemAssignedIdentityPrincipalId": sdk.FieldSpec{WireName: "system_assigned_identity_principal_id"},
		"UserAssignedIdentityId": sdk.FieldSpec{WireName: "user_assigned_identity_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AccountEncryption_TimeoutsFields,
		},
	},
}
