// Code generated by `ubx sdk gen` from azurerm_netapp_backup_policy. DO NOT EDIT.
package netapp

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type BackupPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var BackupPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type BackupPolicyConfig struct {
	AccountName any
	DailyBackupsToKeep any
	Enabled any
	Id any
	Location any
	MonthlyBackupsToKeep any
	Name any
	ResourceGroupName any
	Tags any
	WeeklyBackupsToKeep any
	Timeouts any
}

var BackupPolicy = sdk.ResourceBinding{
	WireType: "azurerm_netapp_backup_policy",
	Fields: sdk.FieldMap{
		"AccountName": sdk.FieldSpec{WireName: "account_name"},
		"DailyBackupsToKeep": sdk.FieldSpec{WireName: "daily_backups_to_keep"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MonthlyBackupsToKeep": sdk.FieldSpec{WireName: "monthly_backups_to_keep"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"WeeklyBackupsToKeep": sdk.FieldSpec{WireName: "weekly_backups_to_keep"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: BackupPolicy_TimeoutsFields,
		},
	},
}
