// Code generated by `ubx sdk gen` from azurerm_netapp_snapshot_policy. DO NOT EDIT.
package netapp

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SnapshotPolicy_DailySchedule struct {
	Hour any
	Minute any
	SnapshotsToKeep any
}

type SnapshotPolicy_HourlySchedule struct {
	Minute any
	SnapshotsToKeep any
}

type SnapshotPolicy_MonthlySchedule struct {
	DaysOfMonth any
	Hour any
	Minute any
	SnapshotsToKeep any
}

type SnapshotPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type SnapshotPolicy_WeeklySchedule struct {
	DaysOfWeek any
	Hour any
	Minute any
	SnapshotsToKeep any
}

var SnapshotPolicy_DailyScheduleFields = sdk.FieldMap{
		"Hour": sdk.FieldSpec{WireName: "hour"},
		"Minute": sdk.FieldSpec{WireName: "minute"},
		"SnapshotsToKeep": sdk.FieldSpec{WireName: "snapshots_to_keep"},
	}

var SnapshotPolicy_HourlyScheduleFields = sdk.FieldMap{
		"Minute": sdk.FieldSpec{WireName: "minute"},
		"SnapshotsToKeep": sdk.FieldSpec{WireName: "snapshots_to_keep"},
	}

var SnapshotPolicy_MonthlyScheduleFields = sdk.FieldMap{
		"DaysOfMonth": sdk.FieldSpec{WireName: "days_of_month"},
		"Hour": sdk.FieldSpec{WireName: "hour"},
		"Minute": sdk.FieldSpec{WireName: "minute"},
		"SnapshotsToKeep": sdk.FieldSpec{WireName: "snapshots_to_keep"},
	}

var SnapshotPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var SnapshotPolicy_WeeklyScheduleFields = sdk.FieldMap{
		"DaysOfWeek": sdk.FieldSpec{WireName: "days_of_week"},
		"Hour": sdk.FieldSpec{WireName: "hour"},
		"Minute": sdk.FieldSpec{WireName: "minute"},
		"SnapshotsToKeep": sdk.FieldSpec{WireName: "snapshots_to_keep"},
	}

type SnapshotPolicyConfig struct {
	AccountName any
	Enabled any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	DailySchedule any
	HourlySchedule any
	MonthlySchedule any
	Timeouts any
	WeeklySchedule any
}

var SnapshotPolicy = sdk.ResourceBinding{
	WireType: "azurerm_netapp_snapshot_policy",
	Fields: sdk.FieldMap{
		"AccountName": sdk.FieldSpec{WireName: "account_name"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"DailySchedule": sdk.FieldSpec{
			WireName: "daily_schedule",
			Kind: "list",
			Fields: SnapshotPolicy_DailyScheduleFields,
		},
		"HourlySchedule": sdk.FieldSpec{
			WireName: "hourly_schedule",
			Kind: "list",
			Fields: SnapshotPolicy_HourlyScheduleFields,
		},
		"MonthlySchedule": sdk.FieldSpec{
			WireName: "monthly_schedule",
			Kind: "list",
			Fields: SnapshotPolicy_MonthlyScheduleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SnapshotPolicy_TimeoutsFields,
		},
		"WeeklySchedule": sdk.FieldSpec{
			WireName: "weekly_schedule",
			Kind: "list",
			Fields: SnapshotPolicy_WeeklyScheduleFields,
		},
	},
}
