// Code generated by `ubx sdk gen` from azurerm_logic_app_workflow. DO NOT EDIT.
package logic

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AppWorkflow_AccessControl_Action struct {
	AllowedCallerIpAddressRange any
}

type AppWorkflow_AccessControl_Trigger_OpenAuthenticationPolicy_Claim struct {
	Name any
	Value any
}

type AppWorkflow_AccessControl_Trigger_OpenAuthenticationPolicy struct {
	Name any
	Claim any
}

type AppWorkflow_AccessControl_Trigger struct {
	AllowedCallerIpAddressRange any
	OpenAuthenticationPolicy any
}

type AppWorkflow_AccessControl struct {
	Action any
	Content any
	Trigger any
	WorkflowManagement any
}

type AppWorkflow_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type AppWorkflow_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AppWorkflow_AccessControl_ActionFields = sdk.FieldMap{
		"AllowedCallerIpAddressRange": sdk.FieldSpec{WireName: "allowed_caller_ip_address_range"},
	}

var AppWorkflow_AccessControl_Trigger_OpenAuthenticationPolicy_ClaimFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var AppWorkflow_AccessControl_Trigger_OpenAuthenticationPolicyFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Claim": sdk.FieldSpec{
			WireName: "claim",
			Kind: "set",
			Fields: AppWorkflow_AccessControl_Trigger_OpenAuthenticationPolicy_ClaimFields,
		},
	}

var AppWorkflow_AccessControl_TriggerFields = sdk.FieldMap{
		"AllowedCallerIpAddressRange": sdk.FieldSpec{WireName: "allowed_caller_ip_address_range"},
		"OpenAuthenticationPolicy": sdk.FieldSpec{
			WireName: "open_authentication_policy",
			Kind: "set",
			Fields: AppWorkflow_AccessControl_Trigger_OpenAuthenticationPolicyFields,
		},
	}

var AppWorkflow_AccessControlFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{
			WireName: "action",
			Kind: "list",
			Fields: AppWorkflow_AccessControl_ActionFields,
		},
		"Content": sdk.FieldSpec{
			WireName: "content",
			Kind: "list",
			Fields: AppWorkflow_AccessControl_ActionFields,
		},
		"Trigger": sdk.FieldSpec{
			WireName: "trigger",
			Kind: "list",
			Fields: AppWorkflow_AccessControl_TriggerFields,
		},
		"WorkflowManagement": sdk.FieldSpec{
			WireName: "workflow_management",
			Kind: "list",
			Fields: AppWorkflow_AccessControl_ActionFields,
		},
	}

var AppWorkflow_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var AppWorkflow_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AppWorkflowConfig struct {
	Enabled any
	Id any
	IntegrationServiceEnvironmentId any
	Location any
	LogicAppIntegrationAccountId any
	Name any
	Parameters any
	ResourceGroupName any
	Tags any
	WorkflowParameters any
	WorkflowSchema any
	WorkflowVersion any
	AccessControl any
	Identity any
	Timeouts any
}

var AppWorkflow = sdk.ResourceBinding{
	WireType: "azurerm_logic_app_workflow",
	Fields: sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IntegrationServiceEnvironmentId": sdk.FieldSpec{WireName: "integration_service_environment_id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"LogicAppIntegrationAccountId": sdk.FieldSpec{WireName: "logic_app_integration_account_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"WorkflowParameters": sdk.FieldSpec{WireName: "workflow_parameters"},
		"WorkflowSchema": sdk.FieldSpec{WireName: "workflow_schema"},
		"WorkflowVersion": sdk.FieldSpec{WireName: "workflow_version"},
		"AccessControl": sdk.FieldSpec{
			WireName: "access_control",
			Kind: "list",
			Fields: AppWorkflow_AccessControlFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: AppWorkflow_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AppWorkflow_TimeoutsFields,
		},
	},
}
