// Code generated by `ubx sdk gen` from azurerm_logic_app_integration_account. DO NOT EDIT.
package logic

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AppIntegrationAccount_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AppIntegrationAccount_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AppIntegrationAccountConfig struct {
	Id any
	IntegrationServiceEnvironmentId any
	Location any
	Name any
	ResourceGroupName any
	SkuName any
	Tags any
	Timeouts any
}

var AppIntegrationAccount = sdk.ResourceBinding{
	WireType: "azurerm_logic_app_integration_account",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"IntegrationServiceEnvironmentId": sdk.FieldSpec{WireName: "integration_service_environment_id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SkuName": sdk.FieldSpec{WireName: "sku_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AppIntegrationAccount_TimeoutsFields,
		},
	},
}
