// Code generated by `ubx sdk gen` from azurerm_logic_app_integration_account_certificate. DO NOT EDIT.
package logic

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AppIntegrationAccountCertificate_KeyVaultKey struct {
	KeyName any
	KeyVaultId any
	KeyVersion any
}

type AppIntegrationAccountCertificate_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AppIntegrationAccountCertificate_KeyVaultKeyFields = sdk.FieldMap{
		"KeyName": sdk.FieldSpec{WireName: "key_name"},
		"KeyVaultId": sdk.FieldSpec{WireName: "key_vault_id"},
		"KeyVersion": sdk.FieldSpec{WireName: "key_version"},
	}

var AppIntegrationAccountCertificate_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AppIntegrationAccountCertificateConfig struct {
	Id any
	IntegrationAccountName any
	Metadata any
	Name any
	PublicCertificate any
	ResourceGroupName any
	KeyVaultKey any
	Timeouts any
}

var AppIntegrationAccountCertificate = sdk.ResourceBinding{
	WireType: "azurerm_logic_app_integration_account_certificate",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"IntegrationAccountName": sdk.FieldSpec{WireName: "integration_account_name"},
		"Metadata": sdk.FieldSpec{WireName: "metadata"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PublicCertificate": sdk.FieldSpec{WireName: "public_certificate"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"KeyVaultKey": sdk.FieldSpec{
			WireName: "key_vault_key",
			Kind: "list",
			Fields: AppIntegrationAccountCertificate_KeyVaultKeyFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AppIntegrationAccountCertificate_TimeoutsFields,
		},
	},
}
