// Code generated by `ubx sdk gen` from azurerm_logic_app_standard. DO NOT EDIT.
package logic

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AppStandard_ConnectionString struct {
	Name any
	Type any
	Value any
}

type AppStandard_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type AppStandard_SiteConfig_Cors struct {
	AllowedOrigins any
	SupportCredentials any
}

type AppStandard_SiteConfig_IpRestriction_Headers struct {
	XAzureFdid any
	XFdHealthProbe any
	XForwardedFor any
	XForwardedHost any
}

type AppStandard_SiteConfig_IpRestriction struct {
	Action any
	Description any
	Headers any
	IpAddress any
	Name any
	Priority any
	ServiceTag any
	VirtualNetworkSubnetId any
}

type AppStandard_SiteConfig struct {
	AlwaysOn any
	AppScaleLimit any
	AutoSwapSlotName any
	DotnetFrameworkVersion any
	ElasticInstanceMinimum any
	FtpsState any
	HealthCheckPath any
	Http2Enabled any
	IpRestrictionDefaultAction any
	LinuxFxVersion any
	MinTlsVersion any
	PreWarmedInstanceCount any
	RuntimeScaleMonitoringEnabled any
	ScmIpRestrictionDefaultAction any
	ScmMinTlsVersion any
	ScmType any
	ScmUseMainIpRestriction any
	Use32BitWorkerProcess any
	VnetRouteAllEnabled any
	WebsocketsEnabled any
	Cors any
	IpRestriction any
	ScmIpRestriction any
}

type AppStandard_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AppStandard_ConnectionStringFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var AppStandard_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var AppStandard_SiteConfig_CorsFields = sdk.FieldMap{
		"AllowedOrigins": sdk.FieldSpec{WireName: "allowed_origins"},
		"SupportCredentials": sdk.FieldSpec{WireName: "support_credentials"},
	}

var AppStandard_SiteConfig_IpRestriction_HeadersFields = sdk.FieldMap{
		"XAzureFdid": sdk.FieldSpec{WireName: "x_azure_fdid"},
		"XFdHealthProbe": sdk.FieldSpec{WireName: "x_fd_health_probe"},
		"XForwardedFor": sdk.FieldSpec{WireName: "x_forwarded_for"},
		"XForwardedHost": sdk.FieldSpec{WireName: "x_forwarded_host"},
	}

var AppStandard_SiteConfig_IpRestrictionFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Headers": sdk.FieldSpec{
			WireName: "headers",
			Kind: "list",
			Fields: AppStandard_SiteConfig_IpRestriction_HeadersFields,
		},
		"IpAddress": sdk.FieldSpec{WireName: "ip_address"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"ServiceTag": sdk.FieldSpec{WireName: "service_tag"},
		"VirtualNetworkSubnetId": sdk.FieldSpec{WireName: "virtual_network_subnet_id"},
	}

var AppStandard_SiteConfigFields = sdk.FieldMap{
		"AlwaysOn": sdk.FieldSpec{WireName: "always_on"},
		"AppScaleLimit": sdk.FieldSpec{WireName: "app_scale_limit"},
		"AutoSwapSlotName": sdk.FieldSpec{WireName: "auto_swap_slot_name"},
		"DotnetFrameworkVersion": sdk.FieldSpec{WireName: "dotnet_framework_version"},
		"ElasticInstanceMinimum": sdk.FieldSpec{WireName: "elastic_instance_minimum"},
		"FtpsState": sdk.FieldSpec{WireName: "ftps_state"},
		"HealthCheckPath": sdk.FieldSpec{WireName: "health_check_path"},
		"Http2Enabled": sdk.FieldSpec{WireName: "http2_enabled"},
		"IpRestrictionDefaultAction": sdk.FieldSpec{WireName: "ip_restriction_default_action"},
		"LinuxFxVersion": sdk.FieldSpec{WireName: "linux_fx_version"},
		"MinTlsVersion": sdk.FieldSpec{WireName: "min_tls_version"},
		"PreWarmedInstanceCount": sdk.FieldSpec{WireName: "pre_warmed_instance_count"},
		"RuntimeScaleMonitoringEnabled": sdk.FieldSpec{WireName: "runtime_scale_monitoring_enabled"},
		"ScmIpRestrictionDefaultAction": sdk.FieldSpec{WireName: "scm_ip_restriction_default_action"},
		"ScmMinTlsVersion": sdk.FieldSpec{WireName: "scm_min_tls_version"},
		"ScmType": sdk.FieldSpec{WireName: "scm_type"},
		"ScmUseMainIpRestriction": sdk.FieldSpec{WireName: "scm_use_main_ip_restriction"},
		"Use32BitWorkerProcess": sdk.FieldSpec{WireName: "use_32_bit_worker_process"},
		"VnetRouteAllEnabled": sdk.FieldSpec{WireName: "vnet_route_all_enabled"},
		"WebsocketsEnabled": sdk.FieldSpec{WireName: "websockets_enabled"},
		"Cors": sdk.FieldSpec{
			WireName: "cors",
			Kind: "list",
			Fields: AppStandard_SiteConfig_CorsFields,
		},
		"IpRestriction": sdk.FieldSpec{
			WireName: "ip_restriction",
			Kind: "list",
			Fields: AppStandard_SiteConfig_IpRestrictionFields,
		},
		"ScmIpRestriction": sdk.FieldSpec{
			WireName: "scm_ip_restriction",
			Kind: "list",
			Fields: AppStandard_SiteConfig_IpRestrictionFields,
		},
	}

var AppStandard_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AppStandardConfig struct {
	AppServicePlanId any
	AppSettings any
	BundleVersion any
	ClientAffinityEnabled any
	ClientCertificateMode any
	Enabled any
	FtpPublishBasicAuthenticationEnabled any
	HttpsOnly any
	Id any
	KeyVaultReferenceIdentityId any
	Location any
	Name any
	PublicNetworkAccess any
	ResourceGroupName any
	ScmPublishBasicAuthenticationEnabled any
	StorageAccountAccessKey any
	StorageAccountName any
	StorageAccountShareName any
	StorageKeyVaultSecretId any
	Tags any
	UseExtensionBundle any
	Version any
	VirtualNetworkSubnetId any
	VnetContentShareEnabled any
	ConnectionString any
	Identity any
	SiteConfig any
	Timeouts any
}

var AppStandard = sdk.ResourceBinding{
	WireType: "azurerm_logic_app_standard",
	Fields: sdk.FieldMap{
		"AppServicePlanId": sdk.FieldSpec{WireName: "app_service_plan_id"},
		"AppSettings": sdk.FieldSpec{WireName: "app_settings"},
		"BundleVersion": sdk.FieldSpec{WireName: "bundle_version"},
		"ClientAffinityEnabled": sdk.FieldSpec{WireName: "client_affinity_enabled"},
		"ClientCertificateMode": sdk.FieldSpec{WireName: "client_certificate_mode"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"FtpPublishBasicAuthenticationEnabled": sdk.FieldSpec{WireName: "ftp_publish_basic_authentication_enabled"},
		"HttpsOnly": sdk.FieldSpec{WireName: "https_only"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"KeyVaultReferenceIdentityId": sdk.FieldSpec{WireName: "key_vault_reference_identity_id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PublicNetworkAccess": sdk.FieldSpec{WireName: "public_network_access"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ScmPublishBasicAuthenticationEnabled": sdk.FieldSpec{WireName: "scm_publish_basic_authentication_enabled"},
		"StorageAccountAccessKey": sdk.FieldSpec{WireName: "storage_account_access_key"},
		"StorageAccountName": sdk.FieldSpec{WireName: "storage_account_name"},
		"StorageAccountShareName": sdk.FieldSpec{WireName: "storage_account_share_name"},
		"StorageKeyVaultSecretId": sdk.FieldSpec{WireName: "storage_key_vault_secret_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"UseExtensionBundle": sdk.FieldSpec{WireName: "use_extension_bundle"},
		"Version": sdk.FieldSpec{WireName: "version"},
		"VirtualNetworkSubnetId": sdk.FieldSpec{WireName: "virtual_network_subnet_id"},
		"VnetContentShareEnabled": sdk.FieldSpec{WireName: "vnet_content_share_enabled"},
		"ConnectionString": sdk.FieldSpec{
			WireName: "connection_string",
			Kind: "set",
			Fields: AppStandard_ConnectionStringFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: AppStandard_IdentityFields,
		},
		"SiteConfig": sdk.FieldSpec{
			WireName: "site_config",
			Kind: "list",
			Fields: AppStandard_SiteConfigFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AppStandard_TimeoutsFields,
		},
	},
}
