// Code generated by `ubx sdk gen` from azurerm_logic_app_trigger_recurrence. DO NOT EDIT.
package logic

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AppTriggerRecurrence_Schedule struct {
	AtTheseHours any
	AtTheseMinutes any
	OnTheseDays any
}

type AppTriggerRecurrence_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AppTriggerRecurrence_ScheduleFields = sdk.FieldMap{
		"AtTheseHours": sdk.FieldSpec{WireName: "at_these_hours"},
		"AtTheseMinutes": sdk.FieldSpec{WireName: "at_these_minutes"},
		"OnTheseDays": sdk.FieldSpec{WireName: "on_these_days"},
	}

var AppTriggerRecurrence_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AppTriggerRecurrenceConfig struct {
	Frequency any
	Id any
	Interval any
	LogicAppId any
	Name any
	StartTime any
	TimeZone any
	Schedule any
	Timeouts any
}

var AppTriggerRecurrence = sdk.ResourceBinding{
	WireType: "azurerm_logic_app_trigger_recurrence",
	Fields: sdk.FieldMap{
		"Frequency": sdk.FieldSpec{WireName: "frequency"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Interval": sdk.FieldSpec{WireName: "interval"},
		"LogicAppId": sdk.FieldSpec{WireName: "logic_app_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"StartTime": sdk.FieldSpec{WireName: "start_time"},
		"TimeZone": sdk.FieldSpec{WireName: "time_zone"},
		"Schedule": sdk.FieldSpec{
			WireName: "schedule",
			Kind: "list",
			Fields: AppTriggerRecurrence_ScheduleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AppTriggerRecurrence_TimeoutsFields,
		},
	},
}
