// Code generated by `ubx sdk gen` from azurerm_backup_policy_file_share. DO NOT EDIT.
package backup

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type PolicyFileShare_Backup_Hourly struct {
	Interval any
	StartTime any
	WindowDuration any
}

type PolicyFileShare_Backup struct {
	Frequency any
	Time any
	Hourly any
}

type PolicyFileShare_RetentionDaily struct {
	Count any
}

type PolicyFileShare_RetentionMonthly struct {
	Count any
	Days any
	IncludeLastDays any
	Weekdays any
	Weeks any
}

type PolicyFileShare_RetentionWeekly struct {
	Count any
	Weekdays any
}

type PolicyFileShare_RetentionYearly struct {
	Count any
	Days any
	IncludeLastDays any
	Months any
	Weekdays any
	Weeks any
}

type PolicyFileShare_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var PolicyFileShare_Backup_HourlyFields = sdk.FieldMap{
		"Interval": sdk.FieldSpec{WireName: "interval"},
		"StartTime": sdk.FieldSpec{WireName: "start_time"},
		"WindowDuration": sdk.FieldSpec{WireName: "window_duration"},
	}

var PolicyFileShare_BackupFields = sdk.FieldMap{
		"Frequency": sdk.FieldSpec{WireName: "frequency"},
		"Time": sdk.FieldSpec{WireName: "time"},
		"Hourly": sdk.FieldSpec{
			WireName: "hourly",
			Kind: "list",
			Fields: PolicyFileShare_Backup_HourlyFields,
		},
	}

var PolicyFileShare_RetentionDailyFields = sdk.FieldMap{
		"Count": sdk.FieldSpec{WireName: "count"},
	}

var PolicyFileShare_RetentionMonthlyFields = sdk.FieldMap{
		"Count": sdk.FieldSpec{WireName: "count"},
		"Days": sdk.FieldSpec{WireName: "days"},
		"IncludeLastDays": sdk.FieldSpec{WireName: "include_last_days"},
		"Weekdays": sdk.FieldSpec{WireName: "weekdays"},
		"Weeks": sdk.FieldSpec{WireName: "weeks"},
	}

var PolicyFileShare_RetentionWeeklyFields = sdk.FieldMap{
		"Count": sdk.FieldSpec{WireName: "count"},
		"Weekdays": sdk.FieldSpec{WireName: "weekdays"},
	}

var PolicyFileShare_RetentionYearlyFields = sdk.FieldMap{
		"Count": sdk.FieldSpec{WireName: "count"},
		"Days": sdk.FieldSpec{WireName: "days"},
		"IncludeLastDays": sdk.FieldSpec{WireName: "include_last_days"},
		"Months": sdk.FieldSpec{WireName: "months"},
		"Weekdays": sdk.FieldSpec{WireName: "weekdays"},
		"Weeks": sdk.FieldSpec{WireName: "weeks"},
	}

var PolicyFileShare_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type PolicyFileShareConfig struct {
	BackupTier any
	Id any
	Name any
	RecoveryVaultName any
	ResourceGroupName any
	SnapshotRetentionInDays any
	Timezone any
	Backup any
	RetentionDaily any
	RetentionMonthly any
	RetentionWeekly any
	RetentionYearly any
	Timeouts any
}

var PolicyFileShare = sdk.ResourceBinding{
	WireType: "azurerm_backup_policy_file_share",
	Fields: sdk.FieldMap{
		"BackupTier": sdk.FieldSpec{WireName: "backup_tier"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RecoveryVaultName": sdk.FieldSpec{WireName: "recovery_vault_name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SnapshotRetentionInDays": sdk.FieldSpec{WireName: "snapshot_retention_in_days"},
		"Timezone": sdk.FieldSpec{WireName: "timezone"},
		"Backup": sdk.FieldSpec{
			WireName: "backup",
			Kind: "list",
			Fields: PolicyFileShare_BackupFields,
		},
		"RetentionDaily": sdk.FieldSpec{
			WireName: "retention_daily",
			Kind: "list",
			Fields: PolicyFileShare_RetentionDailyFields,
		},
		"RetentionMonthly": sdk.FieldSpec{
			WireName: "retention_monthly",
			Kind: "list",
			Fields: PolicyFileShare_RetentionMonthlyFields,
		},
		"RetentionWeekly": sdk.FieldSpec{
			WireName: "retention_weekly",
			Kind: "list",
			Fields: PolicyFileShare_RetentionWeeklyFields,
		},
		"RetentionYearly": sdk.FieldSpec{
			WireName: "retention_yearly",
			Kind: "list",
			Fields: PolicyFileShare_RetentionYearlyFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PolicyFileShare_TimeoutsFields,
		},
	},
}
