// Code generated by `ubx sdk gen` from azurerm_windows_virtual_machine_scale_set. DO NOT EDIT.
package windows

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type VirtualMachineScaleSet_AdditionalCapabilities struct {
	UltraSsdEnabled any
}

type VirtualMachineScaleSet_AdditionalUnattendContent struct {
	Content any
	Setting any
}

type VirtualMachineScaleSet_AutomaticInstanceRepair struct {
	Action any
	Enabled any
	GracePeriod any
}

type VirtualMachineScaleSet_AutomaticOsUpgradePolicy struct {
	AutomaticOsUpgradeEnabled any
	AutomaticRollbackEnabled any
}

type VirtualMachineScaleSet_BootDiagnostics struct {
	StorageAccountUri any
}

type VirtualMachineScaleSet_DataDisk struct {
	Caching any
	CreateOption any
	DiskEncryptionSetId any
	DiskIopsReadWrite any
	DiskMbpsReadWrite any
	DiskSizeGb any
	Lun any
	Name any
	StorageAccountType any
	WriteAcceleratorEnabled any
}

type VirtualMachineScaleSet_Extension_ProtectedSettingsFromKeyVault struct {
	SecretUrl any
	SourceVaultId any
}

type VirtualMachineScaleSet_Extension struct {
	AutoUpgradeMinorVersion any
	AutomaticUpgradeEnabled any
	ForceUpdateTag any
	Name any
	ProtectedSettings any
	ProvisionAfterExtensions any
	Publisher any
	Settings any
	Type any
	TypeHandlerVersion any
	ProtectedSettingsFromKeyVault any
}

type VirtualMachineScaleSet_GalleryApplication struct {
	ConfigurationBlobUri any
	Order any
	Tag any
	VersionId any
}

type VirtualMachineScaleSet_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type VirtualMachineScaleSet_NetworkInterface_IpConfiguration_PublicIpAddress_IpTag struct {
	Tag any
	Type any
}

type VirtualMachineScaleSet_NetworkInterface_IpConfiguration_PublicIpAddress struct {
	DomainNameLabel any
	IdleTimeoutInMinutes any
	Name any
	PublicIpPrefixId any
	Version any
	IpTag any
}

type VirtualMachineScaleSet_NetworkInterface_IpConfiguration struct {
	ApplicationGatewayBackendAddressPoolIds any
	ApplicationSecurityGroupIds any
	LoadBalancerBackendAddressPoolIds any
	LoadBalancerInboundNatRulesIds any
	Name any
	Primary any
	SubnetId any
	Version any
	PublicIpAddress any
}

type VirtualMachineScaleSet_NetworkInterface struct {
	AcceleratedNetworkingEnabled any
	AuxiliaryMode any
	AuxiliarySku any
	DnsServers any
	IpForwardingEnabled any
	Name any
	NetworkSecurityGroupId any
	Primary any
	IpConfiguration any
}

type VirtualMachineScaleSet_OsDisk_DiffDiskSettings struct {
	Option any
	Placement any
}

type VirtualMachineScaleSet_OsDisk struct {
	Caching any
	DiskEncryptionSetId any
	DiskSizeGb any
	SecureVmDiskEncryptionSetId any
	SecurityEncryptionType any
	StorageAccountType any
	WriteAcceleratorEnabled any
	DiffDiskSettings any
}

type VirtualMachineScaleSet_Plan struct {
	Name any
	Product any
	Publisher any
}

type VirtualMachineScaleSet_RollingUpgradePolicy struct {
	CrossZoneUpgradesEnabled any
	MaxBatchInstancePercent any
	MaxUnhealthyInstancePercent any
	MaxUnhealthyUpgradedInstancePercent any
	MaximumSurgeInstancesEnabled any
	PauseTimeBetweenBatches any
	PrioritizeUnhealthyInstancesEnabled any
}

type VirtualMachineScaleSet_ScaleIn struct {
	ForceDeletionEnabled any
	Rule any
}

type VirtualMachineScaleSet_Secret_Certificate struct {
	Store any
	Url any
}

type VirtualMachineScaleSet_Secret struct {
	KeyVaultId any
	Certificate any
}

type VirtualMachineScaleSet_SourceImageReference struct {
	Offer any
	Publisher any
	Sku any
	Version any
}

type VirtualMachineScaleSet_SpotRestore struct {
	Enabled any
	Timeout any
}

type VirtualMachineScaleSet_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type VirtualMachineScaleSet_WinrmListener struct {
	CertificateUrl any
	Protocol any
}

var VirtualMachineScaleSet_AdditionalCapabilitiesFields = sdk.FieldMap{
		"UltraSsdEnabled": sdk.FieldSpec{WireName: "ultra_ssd_enabled"},
	}

var VirtualMachineScaleSet_AdditionalUnattendContentFields = sdk.FieldMap{
		"Content": sdk.FieldSpec{WireName: "content"},
		"Setting": sdk.FieldSpec{WireName: "setting"},
	}

var VirtualMachineScaleSet_AutomaticInstanceRepairFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"GracePeriod": sdk.FieldSpec{WireName: "grace_period"},
	}

var VirtualMachineScaleSet_AutomaticOsUpgradePolicyFields = sdk.FieldMap{
		"AutomaticOsUpgradeEnabled": sdk.FieldSpec{WireName: "automatic_os_upgrade_enabled"},
		"AutomaticRollbackEnabled": sdk.FieldSpec{WireName: "automatic_rollback_enabled"},
	}

var VirtualMachineScaleSet_BootDiagnosticsFields = sdk.FieldMap{
		"StorageAccountUri": sdk.FieldSpec{WireName: "storage_account_uri"},
	}

var VirtualMachineScaleSet_DataDiskFields = sdk.FieldMap{
		"Caching": sdk.FieldSpec{WireName: "caching"},
		"CreateOption": sdk.FieldSpec{WireName: "create_option"},
		"DiskEncryptionSetId": sdk.FieldSpec{WireName: "disk_encryption_set_id"},
		"DiskIopsReadWrite": sdk.FieldSpec{WireName: "disk_iops_read_write"},
		"DiskMbpsReadWrite": sdk.FieldSpec{WireName: "disk_mbps_read_write"},
		"DiskSizeGb": sdk.FieldSpec{WireName: "disk_size_gb"},
		"Lun": sdk.FieldSpec{WireName: "lun"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"StorageAccountType": sdk.FieldSpec{WireName: "storage_account_type"},
		"WriteAcceleratorEnabled": sdk.FieldSpec{WireName: "write_accelerator_enabled"},
	}

var VirtualMachineScaleSet_Extension_ProtectedSettingsFromKeyVaultFields = sdk.FieldMap{
		"SecretUrl": sdk.FieldSpec{WireName: "secret_url"},
		"SourceVaultId": sdk.FieldSpec{WireName: "source_vault_id"},
	}

var VirtualMachineScaleSet_ExtensionFields = sdk.FieldMap{
		"AutoUpgradeMinorVersion": sdk.FieldSpec{WireName: "auto_upgrade_minor_version"},
		"AutomaticUpgradeEnabled": sdk.FieldSpec{WireName: "automatic_upgrade_enabled"},
		"ForceUpdateTag": sdk.FieldSpec{WireName: "force_update_tag"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ProtectedSettings": sdk.FieldSpec{WireName: "protected_settings"},
		"ProvisionAfterExtensions": sdk.FieldSpec{WireName: "provision_after_extensions"},
		"Publisher": sdk.FieldSpec{WireName: "publisher"},
		"Settings": sdk.FieldSpec{WireName: "settings"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"TypeHandlerVersion": sdk.FieldSpec{WireName: "type_handler_version"},
		"ProtectedSettingsFromKeyVault": sdk.FieldSpec{
			WireName: "protected_settings_from_key_vault",
			Kind: "list",
			Fields: VirtualMachineScaleSet_Extension_ProtectedSettingsFromKeyVaultFields,
		},
	}

var VirtualMachineScaleSet_GalleryApplicationFields = sdk.FieldMap{
		"ConfigurationBlobUri": sdk.FieldSpec{WireName: "configuration_blob_uri"},
		"Order": sdk.FieldSpec{WireName: "order"},
		"Tag": sdk.FieldSpec{WireName: "tag"},
		"VersionId": sdk.FieldSpec{WireName: "version_id"},
	}

var VirtualMachineScaleSet_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var VirtualMachineScaleSet_NetworkInterface_IpConfiguration_PublicIpAddress_IpTagFields = sdk.FieldMap{
		"Tag": sdk.FieldSpec{WireName: "tag"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var VirtualMachineScaleSet_NetworkInterface_IpConfiguration_PublicIpAddressFields = sdk.FieldMap{
		"DomainNameLabel": sdk.FieldSpec{WireName: "domain_name_label"},
		"IdleTimeoutInMinutes": sdk.FieldSpec{WireName: "idle_timeout_in_minutes"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PublicIpPrefixId": sdk.FieldSpec{WireName: "public_ip_prefix_id"},
		"Version": sdk.FieldSpec{WireName: "version"},
		"IpTag": sdk.FieldSpec{
			WireName: "ip_tag",
			Kind: "list",
			Fields: VirtualMachineScaleSet_NetworkInterface_IpConfiguration_PublicIpAddress_IpTagFields,
		},
	}

var VirtualMachineScaleSet_NetworkInterface_IpConfigurationFields = sdk.FieldMap{
		"ApplicationGatewayBackendAddressPoolIds": sdk.FieldSpec{WireName: "application_gateway_backend_address_pool_ids"},
		"ApplicationSecurityGroupIds": sdk.FieldSpec{WireName: "application_security_group_ids"},
		"LoadBalancerBackendAddressPoolIds": sdk.FieldSpec{WireName: "load_balancer_backend_address_pool_ids"},
		"LoadBalancerInboundNatRulesIds": sdk.FieldSpec{WireName: "load_balancer_inbound_nat_rules_ids"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Primary": sdk.FieldSpec{WireName: "primary"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
		"Version": sdk.FieldSpec{WireName: "version"},
		"PublicIpAddress": sdk.FieldSpec{
			WireName: "public_ip_address",
			Kind: "list",
			Fields: VirtualMachineScaleSet_NetworkInterface_IpConfiguration_PublicIpAddressFields,
		},
	}

var VirtualMachineScaleSet_NetworkInterfaceFields = sdk.FieldMap{
		"AcceleratedNetworkingEnabled": sdk.FieldSpec{WireName: "accelerated_networking_enabled"},
		"AuxiliaryMode": sdk.FieldSpec{WireName: "auxiliary_mode"},
		"AuxiliarySku": sdk.FieldSpec{WireName: "auxiliary_sku"},
		"DnsServers": sdk.FieldSpec{WireName: "dns_servers"},
		"IpForwardingEnabled": sdk.FieldSpec{WireName: "ip_forwarding_enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkSecurityGroupId": sdk.FieldSpec{WireName: "network_security_group_id"},
		"Primary": sdk.FieldSpec{WireName: "primary"},
		"IpConfiguration": sdk.FieldSpec{
			WireName: "ip_configuration",
			Kind: "list",
			Fields: VirtualMachineScaleSet_NetworkInterface_IpConfigurationFields,
		},
	}

var VirtualMachineScaleSet_OsDisk_DiffDiskSettingsFields = sdk.FieldMap{
		"Option": sdk.FieldSpec{WireName: "option"},
		"Placement": sdk.FieldSpec{WireName: "placement"},
	}

var VirtualMachineScaleSet_OsDiskFields = sdk.FieldMap{
		"Caching": sdk.FieldSpec{WireName: "caching"},
		"DiskEncryptionSetId": sdk.FieldSpec{WireName: "disk_encryption_set_id"},
		"DiskSizeGb": sdk.FieldSpec{WireName: "disk_size_gb"},
		"SecureVmDiskEncryptionSetId": sdk.FieldSpec{WireName: "secure_vm_disk_encryption_set_id"},
		"SecurityEncryptionType": sdk.FieldSpec{WireName: "security_encryption_type"},
		"StorageAccountType": sdk.FieldSpec{WireName: "storage_account_type"},
		"WriteAcceleratorEnabled": sdk.FieldSpec{WireName: "write_accelerator_enabled"},
		"DiffDiskSettings": sdk.FieldSpec{
			WireName: "diff_disk_settings",
			Kind: "list",
			Fields: VirtualMachineScaleSet_OsDisk_DiffDiskSettingsFields,
		},
	}

var VirtualMachineScaleSet_PlanFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Product": sdk.FieldSpec{WireName: "product"},
		"Publisher": sdk.FieldSpec{WireName: "publisher"},
	}

var VirtualMachineScaleSet_RollingUpgradePolicyFields = sdk.FieldMap{
		"CrossZoneUpgradesEnabled": sdk.FieldSpec{WireName: "cross_zone_upgrades_enabled"},
		"MaxBatchInstancePercent": sdk.FieldSpec{WireName: "max_batch_instance_percent"},
		"MaxUnhealthyInstancePercent": sdk.FieldSpec{WireName: "max_unhealthy_instance_percent"},
		"MaxUnhealthyUpgradedInstancePercent": sdk.FieldSpec{WireName: "max_unhealthy_upgraded_instance_percent"},
		"MaximumSurgeInstancesEnabled": sdk.FieldSpec{WireName: "maximum_surge_instances_enabled"},
		"PauseTimeBetweenBatches": sdk.FieldSpec{WireName: "pause_time_between_batches"},
		"PrioritizeUnhealthyInstancesEnabled": sdk.FieldSpec{WireName: "prioritize_unhealthy_instances_enabled"},
	}

var VirtualMachineScaleSet_ScaleInFields = sdk.FieldMap{
		"ForceDeletionEnabled": sdk.FieldSpec{WireName: "force_deletion_enabled"},
		"Rule": sdk.FieldSpec{WireName: "rule"},
	}

var VirtualMachineScaleSet_Secret_CertificateFields = sdk.FieldMap{
		"Store": sdk.FieldSpec{WireName: "store"},
		"Url": sdk.FieldSpec{WireName: "url"},
	}

var VirtualMachineScaleSet_SecretFields = sdk.FieldMap{
		"KeyVaultId": sdk.FieldSpec{WireName: "key_vault_id"},
		"Certificate": sdk.FieldSpec{
			WireName: "certificate",
			Kind: "set",
			Fields: VirtualMachineScaleSet_Secret_CertificateFields,
		},
	}

var VirtualMachineScaleSet_SourceImageReferenceFields = sdk.FieldMap{
		"Offer": sdk.FieldSpec{WireName: "offer"},
		"Publisher": sdk.FieldSpec{WireName: "publisher"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"Version": sdk.FieldSpec{WireName: "version"},
	}

var VirtualMachineScaleSet_SpotRestoreFields = sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Timeout": sdk.FieldSpec{WireName: "timeout"},
	}

var VirtualMachineScaleSet_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var VirtualMachineScaleSet_WinrmListenerFields = sdk.FieldMap{
		"CertificateUrl": sdk.FieldSpec{WireName: "certificate_url"},
		"Protocol": sdk.FieldSpec{WireName: "protocol"},
	}

type VirtualMachineScaleSetConfig struct {
	AdminPassword any
	AdminUsername any
	AutomaticUpdatesEnabled any
	CapacityReservationGroupId any
	ComputerNamePrefix any
	CustomData any
	DoNotRunExtensionsOnOverprovisionedMachines any
	EdgeZone any
	EncryptionAtHostEnabled any
	EvictionPolicy any
	ExtensionOperationsEnabled any
	ExtensionsTimeBudget any
	HealthProbeId any
	HostGroupId any
	Id any
	Instances any
	LicenseType any
	Location any
	MaxBidPrice any
	Name any
	Overprovision any
	PlatformFaultDomainCount any
	Priority any
	ProvisionVmAgent any
	ProximityPlacementGroupId any
	ResilientVmCreationEnabled any
	ResilientVmDeletionEnabled any
	ResourceGroupName any
	SecureBootEnabled any
	SinglePlacementGroup any
	Sku any
	SourceImageId any
	Tags any
	Timezone any
	UpgradeMode any
	UserData any
	VtpmEnabled any
	ZoneBalance any
	Zones any
	AdditionalCapabilities any
	AdditionalUnattendContent any
	AutomaticInstanceRepair any
	AutomaticOsUpgradePolicy any
	BootDiagnostics any
	DataDisk any
	Extension any
	GalleryApplication any
	Identity any
	NetworkInterface any
	OsDisk any
	Plan any
	RollingUpgradePolicy any
	ScaleIn any
	Secret any
	SourceImageReference any
	SpotRestore any
	TerminationNotification any
	Timeouts any
	WinrmListener any
}

var VirtualMachineScaleSet = sdk.ResourceBinding{
	WireType: "azurerm_windows_virtual_machine_scale_set",
	Fields: sdk.FieldMap{
		"AdminPassword": sdk.FieldSpec{WireName: "admin_password"},
		"AdminUsername": sdk.FieldSpec{WireName: "admin_username"},
		"AutomaticUpdatesEnabled": sdk.FieldSpec{WireName: "automatic_updates_enabled"},
		"CapacityReservationGroupId": sdk.FieldSpec{WireName: "capacity_reservation_group_id"},
		"ComputerNamePrefix": sdk.FieldSpec{WireName: "computer_name_prefix"},
		"CustomData": sdk.FieldSpec{WireName: "custom_data"},
		"DoNotRunExtensionsOnOverprovisionedMachines": sdk.FieldSpec{WireName: "do_not_run_extensions_on_overprovisioned_machines"},
		"EdgeZone": sdk.FieldSpec{WireName: "edge_zone"},
		"EncryptionAtHostEnabled": sdk.FieldSpec{WireName: "encryption_at_host_enabled"},
		"EvictionPolicy": sdk.FieldSpec{WireName: "eviction_policy"},
		"ExtensionOperationsEnabled": sdk.FieldSpec{WireName: "extension_operations_enabled"},
		"ExtensionsTimeBudget": sdk.FieldSpec{WireName: "extensions_time_budget"},
		"HealthProbeId": sdk.FieldSpec{WireName: "health_probe_id"},
		"HostGroupId": sdk.FieldSpec{WireName: "host_group_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Instances": sdk.FieldSpec{WireName: "instances"},
		"LicenseType": sdk.FieldSpec{WireName: "license_type"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MaxBidPrice": sdk.FieldSpec{WireName: "max_bid_price"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Overprovision": sdk.FieldSpec{WireName: "overprovision"},
		"PlatformFaultDomainCount": sdk.FieldSpec{WireName: "platform_fault_domain_count"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"ProvisionVmAgent": sdk.FieldSpec{WireName: "provision_vm_agent"},
		"ProximityPlacementGroupId": sdk.FieldSpec{WireName: "proximity_placement_group_id"},
		"ResilientVmCreationEnabled": sdk.FieldSpec{WireName: "resilient_vm_creation_enabled"},
		"ResilientVmDeletionEnabled": sdk.FieldSpec{WireName: "resilient_vm_deletion_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SecureBootEnabled": sdk.FieldSpec{WireName: "secure_boot_enabled"},
		"SinglePlacementGroup": sdk.FieldSpec{WireName: "single_placement_group"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"SourceImageId": sdk.FieldSpec{WireName: "source_image_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timezone": sdk.FieldSpec{WireName: "timezone"},
		"UpgradeMode": sdk.FieldSpec{WireName: "upgrade_mode"},
		"UserData": sdk.FieldSpec{WireName: "user_data"},
		"VtpmEnabled": sdk.FieldSpec{WireName: "vtpm_enabled"},
		"ZoneBalance": sdk.FieldSpec{WireName: "zone_balance"},
		"Zones": sdk.FieldSpec{WireName: "zones"},
		"AdditionalCapabilities": sdk.FieldSpec{
			WireName: "additional_capabilities",
			Kind: "list",
			Fields: VirtualMachineScaleSet_AdditionalCapabilitiesFields,
		},
		"AdditionalUnattendContent": sdk.FieldSpec{
			WireName: "additional_unattend_content",
			Kind: "list",
			Fields: VirtualMachineScaleSet_AdditionalUnattendContentFields,
		},
		"AutomaticInstanceRepair": sdk.FieldSpec{
			WireName: "automatic_instance_repair",
			Kind: "list",
			Fields: VirtualMachineScaleSet_AutomaticInstanceRepairFields,
		},
		"AutomaticOsUpgradePolicy": sdk.FieldSpec{
			WireName: "automatic_os_upgrade_policy",
			Kind: "list",
			Fields: VirtualMachineScaleSet_AutomaticOsUpgradePolicyFields,
		},
		"BootDiagnostics": sdk.FieldSpec{
			WireName: "boot_diagnostics",
			Kind: "list",
			Fields: VirtualMachineScaleSet_BootDiagnosticsFields,
		},
		"DataDisk": sdk.FieldSpec{
			WireName: "data_disk",
			Kind: "list",
			Fields: VirtualMachineScaleSet_DataDiskFields,
		},
		"Extension": sdk.FieldSpec{
			WireName: "extension",
			Kind: "set",
			Fields: VirtualMachineScaleSet_ExtensionFields,
		},
		"GalleryApplication": sdk.FieldSpec{
			WireName: "gallery_application",
			Kind: "list",
			Fields: VirtualMachineScaleSet_GalleryApplicationFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: VirtualMachineScaleSet_IdentityFields,
		},
		"NetworkInterface": sdk.FieldSpec{
			WireName: "network_interface",
			Kind: "list",
			Fields: VirtualMachineScaleSet_NetworkInterfaceFields,
		},
		"OsDisk": sdk.FieldSpec{
			WireName: "os_disk",
			Kind: "list",
			Fields: VirtualMachineScaleSet_OsDiskFields,
		},
		"Plan": sdk.FieldSpec{
			WireName: "plan",
			Kind: "list",
			Fields: VirtualMachineScaleSet_PlanFields,
		},
		"RollingUpgradePolicy": sdk.FieldSpec{
			WireName: "rolling_upgrade_policy",
			Kind: "list",
			Fields: VirtualMachineScaleSet_RollingUpgradePolicyFields,
		},
		"ScaleIn": sdk.FieldSpec{
			WireName: "scale_in",
			Kind: "list",
			Fields: VirtualMachineScaleSet_ScaleInFields,
		},
		"Secret": sdk.FieldSpec{
			WireName: "secret",
			Kind: "list",
			Fields: VirtualMachineScaleSet_SecretFields,
		},
		"SourceImageReference": sdk.FieldSpec{
			WireName: "source_image_reference",
			Kind: "list",
			Fields: VirtualMachineScaleSet_SourceImageReferenceFields,
		},
		"SpotRestore": sdk.FieldSpec{
			WireName: "spot_restore",
			Kind: "list",
			Fields: VirtualMachineScaleSet_SpotRestoreFields,
		},
		"TerminationNotification": sdk.FieldSpec{
			WireName: "termination_notification",
			Kind: "list",
			Fields: VirtualMachineScaleSet_SpotRestoreFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: VirtualMachineScaleSet_TimeoutsFields,
		},
		"WinrmListener": sdk.FieldSpec{
			WireName: "winrm_listener",
			Kind: "set",
			Fields: VirtualMachineScaleSet_WinrmListenerFields,
		},
	},
}
