// Code generated by `ubx sdk gen` from azurerm_purview_account. DO NOT EDIT.
package purview

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Account_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Account_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Account_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Account_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AccountConfig struct {
	Id any
	Location any
	ManagedEventHubEnabled any
	ManagedResourceGroupName any
	Name any
	PublicNetworkEnabled any
	ResourceGroupName any
	Tags any
	Identity any
	Timeouts any
}

var Account = sdk.ResourceBinding{
	WireType: "azurerm_purview_account",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"ManagedEventHubEnabled": sdk.FieldSpec{WireName: "managed_event_hub_enabled"},
		"ManagedResourceGroupName": sdk.FieldSpec{WireName: "managed_resource_group_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PublicNetworkEnabled": sdk.FieldSpec{WireName: "public_network_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Account_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Account_TimeoutsFields,
		},
	},
}
