// Code generated by `ubx sdk gen` from azurerm_management_group_policy_exemption. DO NOT EDIT.
package management

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type GroupPolicyExemption_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var GroupPolicyExemption_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type GroupPolicyExemptionConfig struct {
	Description any
	DisplayName any
	ExemptionCategory any
	ExpiresOn any
	Id any
	ManagementGroupId any
	Metadata any
	Name any
	PolicyAssignmentId any
	PolicyDefinitionReferenceIds any
	Timeouts any
}

var GroupPolicyExemption = sdk.ResourceBinding{
	WireType: "azurerm_management_group_policy_exemption",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"ExemptionCategory": sdk.FieldSpec{WireName: "exemption_category"},
		"ExpiresOn": sdk.FieldSpec{WireName: "expires_on"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ManagementGroupId": sdk.FieldSpec{WireName: "management_group_id"},
		"Metadata": sdk.FieldSpec{WireName: "metadata"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PolicyAssignmentId": sdk.FieldSpec{WireName: "policy_assignment_id"},
		"PolicyDefinitionReferenceIds": sdk.FieldSpec{WireName: "policy_definition_reference_ids"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: GroupPolicyExemption_TimeoutsFields,
		},
	},
}
