// Code generated by `ubx sdk gen` from azurerm_management_group_subscription_association. DO NOT EDIT.
package management

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type GroupSubscriptionAssociation_Timeouts struct {
	Create any
	Delete any
	Read any
}

var GroupSubscriptionAssociation_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type GroupSubscriptionAssociationConfig struct {
	Id any
	ManagementGroupId any
	SubscriptionId any
	Timeouts any
}

var GroupSubscriptionAssociation = sdk.ResourceBinding{
	WireType: "azurerm_management_group_subscription_association",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"ManagementGroupId": sdk.FieldSpec{WireName: "management_group_id"},
		"SubscriptionId": sdk.FieldSpec{WireName: "subscription_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: GroupSubscriptionAssociation_TimeoutsFields,
		},
	},
}
