// Code generated by `ubx sdk gen` from azurerm_management_group_template_deployment. DO NOT EDIT.
package management

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type GroupTemplateDeployment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var GroupTemplateDeployment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type GroupTemplateDeploymentConfig struct {
	DebugLevel any
	Id any
	Location any
	ManagementGroupId any
	Name any
	ParametersContent any
	Tags any
	TemplateContent any
	TemplateSpecVersionId any
	Timeouts any
}

var GroupTemplateDeployment = sdk.ResourceBinding{
	WireType: "azurerm_management_group_template_deployment",
	Fields: sdk.FieldMap{
		"DebugLevel": sdk.FieldSpec{WireName: "debug_level"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"ManagementGroupId": sdk.FieldSpec{WireName: "management_group_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ParametersContent": sdk.FieldSpec{WireName: "parameters_content"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TemplateContent": sdk.FieldSpec{WireName: "template_content"},
		"TemplateSpecVersionId": sdk.FieldSpec{WireName: "template_spec_version_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: GroupTemplateDeployment_TimeoutsFields,
		},
	},
}
