// Code generated by `ubx sdk gen` from azurerm_redis_cache_access_policy. DO NOT EDIT.
package redis

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CacheAccessPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CacheAccessPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CacheAccessPolicyConfig struct {
	Id any
	Name any
	Permissions any
	RedisCacheId any
	Timeouts any
}

var CacheAccessPolicy = sdk.ResourceBinding{
	WireType: "azurerm_redis_cache_access_policy",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Permissions": sdk.FieldSpec{WireName: "permissions"},
		"RedisCacheId": sdk.FieldSpec{WireName: "redis_cache_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CacheAccessPolicy_TimeoutsFields,
		},
	},
}
