// Code generated by `ubx sdk gen` from azurerm_portal_dashboard. DO NOT EDIT.
package portal

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Dashboard_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Dashboard_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DashboardConfig struct {
	DashboardProperties any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	Timeouts any
}

var Dashboard = sdk.ResourceBinding{
	WireType: "azurerm_portal_dashboard",
	Fields: sdk.FieldMap{
		"DashboardProperties": sdk.FieldSpec{WireName: "dashboard_properties"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Dashboard_TimeoutsFields,
		},
	},
}
