// Code generated by `ubx sdk gen` from azurerm_iothub_enrichment. DO NOT EDIT.
package iothub

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Enrichment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Enrichment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type EnrichmentConfig struct {
	EndpointNames any
	Id any
	IothubName any
	Key any
	ResourceGroupName any
	Value any
	Timeouts any
}

var Enrichment = sdk.ResourceBinding{
	WireType: "azurerm_iothub_enrichment",
	Fields: sdk.FieldMap{
		"EndpointNames": sdk.FieldSpec{WireName: "endpoint_names"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IothubName": sdk.FieldSpec{WireName: "iothub_name"},
		"Key": sdk.FieldSpec{WireName: "key"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Value": sdk.FieldSpec{WireName: "value"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Enrichment_TimeoutsFields,
		},
	},
}
