// Code generated by `ubx sdk gen` from azurerm_iothub_file_upload. DO NOT EDIT.
package iothub

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FileUpload_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FileUpload_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FileUploadConfig struct {
	AuthenticationType any
	ConnectionString any
	ContainerName any
	DefaultTtl any
	Id any
	IdentityId any
	IothubId any
	LockDuration any
	MaxDeliveryCount any
	NotificationsEnabled any
	SasTtl any
	Timeouts any
}

var FileUpload = sdk.ResourceBinding{
	WireType: "azurerm_iothub_file_upload",
	Fields: sdk.FieldMap{
		"AuthenticationType": sdk.FieldSpec{WireName: "authentication_type"},
		"ConnectionString": sdk.FieldSpec{WireName: "connection_string"},
		"ContainerName": sdk.FieldSpec{WireName: "container_name"},
		"DefaultTtl": sdk.FieldSpec{WireName: "default_ttl"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IdentityId": sdk.FieldSpec{WireName: "identity_id"},
		"IothubId": sdk.FieldSpec{WireName: "iothub_id"},
		"LockDuration": sdk.FieldSpec{WireName: "lock_duration"},
		"MaxDeliveryCount": sdk.FieldSpec{WireName: "max_delivery_count"},
		"NotificationsEnabled": sdk.FieldSpec{WireName: "notifications_enabled"},
		"SasTtl": sdk.FieldSpec{WireName: "sas_ttl"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FileUpload_TimeoutsFields,
		},
	},
}
