// Code generated by `ubx sdk gen` from azurerm_palo_alto_local_rulestack_rule. DO NOT EDIT.
package palo

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AltoLocalRulestackRule_Category struct {
	CustomUrls any
	Feeds any
}

type AltoLocalRulestackRule_Destination struct {
	Cidrs any
	Countries any
	Feeds any
	LocalRulestackFqdnListIds any
	LocalRulestackPrefixListIds any
}

type AltoLocalRulestackRule_Source struct {
	Cidrs any
	Countries any
	Feeds any
	LocalRulestackPrefixListIds any
}

type AltoLocalRulestackRule_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AltoLocalRulestackRule_CategoryFields = sdk.FieldMap{
		"CustomUrls": sdk.FieldSpec{WireName: "custom_urls"},
		"Feeds": sdk.FieldSpec{WireName: "feeds"},
	}

var AltoLocalRulestackRule_DestinationFields = sdk.FieldMap{
		"Cidrs": sdk.FieldSpec{WireName: "cidrs"},
		"Countries": sdk.FieldSpec{WireName: "countries"},
		"Feeds": sdk.FieldSpec{WireName: "feeds"},
		"LocalRulestackFqdnListIds": sdk.FieldSpec{WireName: "local_rulestack_fqdn_list_ids"},
		"LocalRulestackPrefixListIds": sdk.FieldSpec{WireName: "local_rulestack_prefix_list_ids"},
	}

var AltoLocalRulestackRule_SourceFields = sdk.FieldMap{
		"Cidrs": sdk.FieldSpec{WireName: "cidrs"},
		"Countries": sdk.FieldSpec{WireName: "countries"},
		"Feeds": sdk.FieldSpec{WireName: "feeds"},
		"LocalRulestackPrefixListIds": sdk.FieldSpec{WireName: "local_rulestack_prefix_list_ids"},
	}

var AltoLocalRulestackRule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AltoLocalRulestackRuleConfig struct {
	Action any
	Applications any
	AuditComment any
	DecryptionRuleType any
	Description any
	Enabled any
	Id any
	InspectionCertificateId any
	LoggingEnabled any
	Name any
	NegateDestination any
	NegateSource any
	Priority any
	Protocol any
	ProtocolPorts any
	RulestackId any
	Tags any
	Category any
	Destination any
	Source any
	Timeouts any
}

var AltoLocalRulestackRule = sdk.ResourceBinding{
	WireType: "azurerm_palo_alto_local_rulestack_rule",
	Fields: sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Applications": sdk.FieldSpec{WireName: "applications"},
		"AuditComment": sdk.FieldSpec{WireName: "audit_comment"},
		"DecryptionRuleType": sdk.FieldSpec{WireName: "decryption_rule_type"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"InspectionCertificateId": sdk.FieldSpec{WireName: "inspection_certificate_id"},
		"LoggingEnabled": sdk.FieldSpec{WireName: "logging_enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NegateDestination": sdk.FieldSpec{WireName: "negate_destination"},
		"NegateSource": sdk.FieldSpec{WireName: "negate_source"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"Protocol": sdk.FieldSpec{WireName: "protocol"},
		"ProtocolPorts": sdk.FieldSpec{WireName: "protocol_ports"},
		"RulestackId": sdk.FieldSpec{WireName: "rulestack_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Category": sdk.FieldSpec{
			WireName: "category",
			Kind: "list",
			Fields: AltoLocalRulestackRule_CategoryFields,
		},
		"Destination": sdk.FieldSpec{
			WireName: "destination",
			Kind: "list",
			Fields: AltoLocalRulestackRule_DestinationFields,
		},
		"Source": sdk.FieldSpec{
			WireName: "source",
			Kind: "list",
			Fields: AltoLocalRulestackRule_SourceFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AltoLocalRulestackRule_TimeoutsFields,
		},
	},
}
