// Code generated by `ubx sdk gen` from azurerm_palo_alto_local_rulestack_outbound_untrust_certificate_association. DO NOT EDIT.
package palo

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AltoLocalRulestackOutboundUntrustCertificateAssociation_Timeouts struct {
	Create any
	Delete any
	Read any
}

var AltoLocalRulestackOutboundUntrustCertificateAssociation_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type AltoLocalRulestackOutboundUntrustCertificateAssociationConfig struct {
	CertificateId any
	Id any
	Timeouts any
}

var AltoLocalRulestackOutboundUntrustCertificateAssociation = sdk.ResourceBinding{
	WireType: "azurerm_palo_alto_local_rulestack_outbound_untrust_certificate_association",
	Fields: sdk.FieldMap{
		"CertificateId": sdk.FieldSpec{WireName: "certificate_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AltoLocalRulestackOutboundUntrustCertificateAssociation_TimeoutsFields,
		},
	},
}
