// Code generated by `ubx sdk gen` from azurerm_palo_alto_next_generation_firewall_virtual_network_strata_cloud_manager. DO NOT EDIT.
package palo

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_BackendConfig struct {
	Port any
	PublicIpAddress any
}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_FrontendConfig struct {
	Port any
	PublicIpAddressId any
}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat struct {
	Name any
	Protocol any
	BackendConfig any
	FrontendConfig any
}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettings struct {
	AzureDnsServers any
	DnsServers any
	UseAzureDns any
}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Identity struct {
	IdentityIds any
	Type any
}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile_VnetConfiguration struct {
	IpOfTrustForUserDefinedRoutes any
	TrustedSubnetId any
	UntrustedSubnetId any
	VirtualNetworkId any
}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile struct {
	EgressNatIpAddressIds any
	EgressNatIpAddresses any
	PublicIpAddressIds any
	PublicIpAddresses any
	TrustedAddressRanges any
	VnetConfiguration any
}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_BackendConfigFields = sdk.FieldMap{
		"Port": sdk.FieldSpec{WireName: "port"},
		"PublicIpAddress": sdk.FieldSpec{WireName: "public_ip_address"},
	}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_FrontendConfigFields = sdk.FieldMap{
		"Port": sdk.FieldSpec{WireName: "port"},
		"PublicIpAddressId": sdk.FieldSpec{WireName: "public_ip_address_id"},
	}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNatFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Protocol": sdk.FieldSpec{WireName: "protocol"},
		"BackendConfig": sdk.FieldSpec{
			WireName: "backend_config",
			Kind: "list",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_BackendConfigFields,
		},
		"FrontendConfig": sdk.FieldSpec{
			WireName: "frontend_config",
			Kind: "list",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNat_FrontendConfigFields,
		},
	}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettingsFields = sdk.FieldMap{
		"AzureDnsServers": sdk.FieldSpec{WireName: "azure_dns_servers"},
		"DnsServers": sdk.FieldSpec{WireName: "dns_servers"},
		"UseAzureDns": sdk.FieldSpec{WireName: "use_azure_dns"},
	}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile_VnetConfigurationFields = sdk.FieldMap{
		"IpOfTrustForUserDefinedRoutes": sdk.FieldSpec{WireName: "ip_of_trust_for_user_defined_routes"},
		"TrustedSubnetId": sdk.FieldSpec{WireName: "trusted_subnet_id"},
		"UntrustedSubnetId": sdk.FieldSpec{WireName: "untrusted_subnet_id"},
		"VirtualNetworkId": sdk.FieldSpec{WireName: "virtual_network_id"},
	}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfileFields = sdk.FieldMap{
		"EgressNatIpAddressIds": sdk.FieldSpec{WireName: "egress_nat_ip_address_ids"},
		"EgressNatIpAddresses": sdk.FieldSpec{WireName: "egress_nat_ip_addresses"},
		"PublicIpAddressIds": sdk.FieldSpec{WireName: "public_ip_address_ids"},
		"PublicIpAddresses": sdk.FieldSpec{WireName: "public_ip_addresses"},
		"TrustedAddressRanges": sdk.FieldSpec{WireName: "trusted_address_ranges"},
		"VnetConfiguration": sdk.FieldSpec{
			WireName: "vnet_configuration",
			Kind: "list",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfile_VnetConfigurationFields,
		},
	}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AltoNextGenerationFirewallVirtualNetworkStrataCloudManagerConfig struct {
	Id any
	Location any
	MarketplaceOfferId any
	Name any
	PlanId any
	ResourceGroupName any
	StrataCloudManagerTenantName any
	Tags any
	DestinationNat any
	DnsSettings any
	Identity any
	NetworkProfile any
	Timeouts any
}

var AltoNextGenerationFirewallVirtualNetworkStrataCloudManager = sdk.ResourceBinding{
	WireType: "azurerm_palo_alto_next_generation_firewall_virtual_network_strata_cloud_manager",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MarketplaceOfferId": sdk.FieldSpec{WireName: "marketplace_offer_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PlanId": sdk.FieldSpec{WireName: "plan_id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"StrataCloudManagerTenantName": sdk.FieldSpec{WireName: "strata_cloud_manager_tenant_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"DestinationNat": sdk.FieldSpec{
			WireName: "destination_nat",
			Kind: "list",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DestinationNatFields,
		},
		"DnsSettings": sdk.FieldSpec{
			WireName: "dns_settings",
			Kind: "list",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_DnsSettingsFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_IdentityFields,
		},
		"NetworkProfile": sdk.FieldSpec{
			WireName: "network_profile",
			Kind: "list",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_NetworkProfileFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AltoNextGenerationFirewallVirtualNetworkStrataCloudManager_TimeoutsFields,
		},
	},
}
