// Code generated by `ubx sdk gen` from azurerm_palo_alto_local_rulestack_prefix_list. DO NOT EDIT.
package palo

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AltoLocalRulestackPrefixList_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AltoLocalRulestackPrefixList_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AltoLocalRulestackPrefixListConfig struct {
	AuditComment any
	Description any
	Id any
	Name any
	PrefixList any
	RulestackId any
	Timeouts any
}

var AltoLocalRulestackPrefixList = sdk.ResourceBinding{
	WireType: "azurerm_palo_alto_local_rulestack_prefix_list",
	Fields: sdk.FieldMap{
		"AuditComment": sdk.FieldSpec{WireName: "audit_comment"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrefixList": sdk.FieldSpec{WireName: "prefix_list"},
		"RulestackId": sdk.FieldSpec{WireName: "rulestack_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AltoLocalRulestackPrefixList_TimeoutsFields,
		},
	},
}
