// Code generated by `ubx sdk gen` from azurerm_palo_alto_local_rulestack_fqdn_list. DO NOT EDIT.
package palo

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AltoLocalRulestackFqdnList_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AltoLocalRulestackFqdnList_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AltoLocalRulestackFqdnListConfig struct {
	AuditComment any
	Description any
	FullyQualifiedDomainNames any
	Id any
	Name any
	RulestackId any
	Timeouts any
}

var AltoLocalRulestackFqdnList = sdk.ResourceBinding{
	WireType: "azurerm_palo_alto_local_rulestack_fqdn_list",
	Fields: sdk.FieldMap{
		"AuditComment": sdk.FieldSpec{WireName: "audit_comment"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"FullyQualifiedDomainNames": sdk.FieldSpec{WireName: "fully_qualified_domain_names"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RulestackId": sdk.FieldSpec{WireName: "rulestack_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AltoLocalRulestackFqdnList_TimeoutsFields,
		},
	},
}
