// Code generated by `ubx sdk gen` from azurerm_confidential_ledger. DO NOT EDIT.
package confidential

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Ledger_AzureadBasedServicePrincipal struct {
	LedgerRoleName any
	PrincipalId any
	TenantId any
}

type Ledger_CertificateBasedSecurityPrincipal struct {
	LedgerRoleName any
	PemPublicKey any
}

type Ledger_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Ledger_AzureadBasedServicePrincipalFields = sdk.FieldMap{
		"LedgerRoleName": sdk.FieldSpec{WireName: "ledger_role_name"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
	}

var Ledger_CertificateBasedSecurityPrincipalFields = sdk.FieldMap{
		"LedgerRoleName": sdk.FieldSpec{WireName: "ledger_role_name"},
		"PemPublicKey": sdk.FieldSpec{WireName: "pem_public_key"},
	}

var Ledger_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type LedgerConfig struct {
	Id any
	LedgerType any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	AzureadBasedServicePrincipal any
	CertificateBasedSecurityPrincipal any
	Timeouts any
}

var Ledger = sdk.ResourceBinding{
	WireType: "azurerm_confidential_ledger",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"LedgerType": sdk.FieldSpec{WireName: "ledger_type"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"AzureadBasedServicePrincipal": sdk.FieldSpec{
			WireName: "azuread_based_service_principal",
			Kind: "list",
			Fields: Ledger_AzureadBasedServicePrincipalFields,
		},
		"CertificateBasedSecurityPrincipal": sdk.FieldSpec{
			WireName: "certificate_based_security_principal",
			Kind: "list",
			Fields: Ledger_CertificateBasedSecurityPrincipalFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Ledger_TimeoutsFields,
		},
	},
}
