// Code generated by `ubx sdk gen` from azurerm_kusto_attached_database_configuration. DO NOT EDIT.
package kusto

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AttachedDatabaseConfiguration_Sharing struct {
	ExternalTablesToExclude any
	ExternalTablesToInclude any
	FunctionsToExclude any
	FunctionsToInclude any
	MaterializedViewsToExclude any
	MaterializedViewsToInclude any
	TablesToExclude any
	TablesToInclude any
}

type AttachedDatabaseConfiguration_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AttachedDatabaseConfiguration_SharingFields = sdk.FieldMap{
		"ExternalTablesToExclude": sdk.FieldSpec{WireName: "external_tables_to_exclude"},
		"ExternalTablesToInclude": sdk.FieldSpec{WireName: "external_tables_to_include"},
		"FunctionsToExclude": sdk.FieldSpec{WireName: "functions_to_exclude"},
		"FunctionsToInclude": sdk.FieldSpec{WireName: "functions_to_include"},
		"MaterializedViewsToExclude": sdk.FieldSpec{WireName: "materialized_views_to_exclude"},
		"MaterializedViewsToInclude": sdk.FieldSpec{WireName: "materialized_views_to_include"},
		"TablesToExclude": sdk.FieldSpec{WireName: "tables_to_exclude"},
		"TablesToInclude": sdk.FieldSpec{WireName: "tables_to_include"},
	}

var AttachedDatabaseConfiguration_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AttachedDatabaseConfigurationConfig struct {
	ClusterId any
	ClusterName any
	DatabaseName any
	DatabaseNameOverride any
	DatabaseNamePrefix any
	DefaultPrincipalModificationKind any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Sharing any
	Timeouts any
}

var AttachedDatabaseConfiguration = sdk.ResourceBinding{
	WireType: "azurerm_kusto_attached_database_configuration",
	Fields: sdk.FieldMap{
		"ClusterId": sdk.FieldSpec{WireName: "cluster_id"},
		"ClusterName": sdk.FieldSpec{WireName: "cluster_name"},
		"DatabaseName": sdk.FieldSpec{WireName: "database_name"},
		"DatabaseNameOverride": sdk.FieldSpec{WireName: "database_name_override"},
		"DatabaseNamePrefix": sdk.FieldSpec{WireName: "database_name_prefix"},
		"DefaultPrincipalModificationKind": sdk.FieldSpec{WireName: "default_principal_modification_kind"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Sharing": sdk.FieldSpec{
			WireName: "sharing",
			Kind: "list",
			Fields: AttachedDatabaseConfiguration_SharingFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AttachedDatabaseConfiguration_TimeoutsFields,
		},
	},
}
