// Code generated by `ubx sdk gen` from azurerm_kusto_cluster_principal_assignment. DO NOT EDIT.
package kusto

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ClusterPrincipalAssignment_Timeouts struct {
	Create any
	Delete any
	Read any
}

var ClusterPrincipalAssignment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type ClusterPrincipalAssignmentConfig struct {
	ClusterName any
	Id any
	Name any
	PrincipalId any
	PrincipalType any
	ResourceGroupName any
	Role any
	TenantId any
	Timeouts any
}

var ClusterPrincipalAssignment = sdk.ResourceBinding{
	WireType: "azurerm_kusto_cluster_principal_assignment",
	Fields: sdk.FieldMap{
		"ClusterName": sdk.FieldSpec{WireName: "cluster_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"PrincipalType": sdk.FieldSpec{WireName: "principal_type"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Role": sdk.FieldSpec{WireName: "role"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ClusterPrincipalAssignment_TimeoutsFields,
		},
	},
}
