// Code generated by `ubx sdk gen` from azurerm_kusto_cluster_managed_private_endpoint. DO NOT EDIT.
package kusto

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ClusterManagedPrivateEndpoint_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ClusterManagedPrivateEndpoint_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ClusterManagedPrivateEndpointConfig struct {
	ClusterName any
	GroupId any
	Id any
	Name any
	PrivateLinkResourceId any
	PrivateLinkResourceRegion any
	RequestMessage any
	ResourceGroupName any
	Timeouts any
}

var ClusterManagedPrivateEndpoint = sdk.ResourceBinding{
	WireType: "azurerm_kusto_cluster_managed_private_endpoint",
	Fields: sdk.FieldMap{
		"ClusterName": sdk.FieldSpec{WireName: "cluster_name"},
		"GroupId": sdk.FieldSpec{WireName: "group_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateLinkResourceId": sdk.FieldSpec{WireName: "private_link_resource_id"},
		"PrivateLinkResourceRegion": sdk.FieldSpec{WireName: "private_link_resource_region"},
		"RequestMessage": sdk.FieldSpec{WireName: "request_message"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ClusterManagedPrivateEndpoint_TimeoutsFields,
		},
	},
}
