// Code generated by `ubx sdk gen` from azurerm_kusto_database. DO NOT EDIT.
package kusto

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Database_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Database_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DatabaseConfig struct {
	ClusterName any
	HotCachePeriod any
	Id any
	Location any
	Name any
	ResourceGroupName any
	SoftDeletePeriod any
	Timeouts any
}

var Database = sdk.ResourceBinding{
	WireType: "azurerm_kusto_database",
	Fields: sdk.FieldMap{
		"ClusterName": sdk.FieldSpec{WireName: "cluster_name"},
		"HotCachePeriod": sdk.FieldSpec{WireName: "hot_cache_period"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SoftDeletePeriod": sdk.FieldSpec{WireName: "soft_delete_period"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Database_TimeoutsFields,
		},
	},
}
