// Code generated by `ubx sdk gen` from azurerm_kusto_eventhub_data_connection. DO NOT EDIT.
package kusto

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type EventhubDataConnection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var EventhubDataConnection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type EventhubDataConnectionConfig struct {
	ClusterName any
	Compression any
	ConsumerGroup any
	DataFormat any
	DatabaseName any
	DatabaseRoutingType any
	EventSystemProperties any
	EventhubId any
	Id any
	IdentityId any
	Location any
	MappingRuleName any
	Name any
	ResourceGroupName any
	RetrievalStartDate any
	TableName any
	Timeouts any
}

var EventhubDataConnection = sdk.ResourceBinding{
	WireType: "azurerm_kusto_eventhub_data_connection",
	Fields: sdk.FieldMap{
		"ClusterName": sdk.FieldSpec{WireName: "cluster_name"},
		"Compression": sdk.FieldSpec{WireName: "compression"},
		"ConsumerGroup": sdk.FieldSpec{WireName: "consumer_group"},
		"DataFormat": sdk.FieldSpec{WireName: "data_format"},
		"DatabaseName": sdk.FieldSpec{WireName: "database_name"},
		"DatabaseRoutingType": sdk.FieldSpec{WireName: "database_routing_type"},
		"EventSystemProperties": sdk.FieldSpec{WireName: "event_system_properties"},
		"EventhubId": sdk.FieldSpec{WireName: "eventhub_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IdentityId": sdk.FieldSpec{WireName: "identity_id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MappingRuleName": sdk.FieldSpec{WireName: "mapping_rule_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"RetrievalStartDate": sdk.FieldSpec{WireName: "retrieval_start_date"},
		"TableName": sdk.FieldSpec{WireName: "table_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: EventhubDataConnection_TimeoutsFields,
		},
	},
}
