// Code generated by `ubx sdk gen` from azurerm_batch_account. DO NOT EDIT.
package batch

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Account_Encryption struct {
	KeyVaultKeyId any
}

type Account_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Account_KeyVaultReference struct {
	Id any
	Url any
}

type Account_NetworkProfile_AccountAccess_IpRule struct {
	Action any
	IpRange any
}

type Account_NetworkProfile_AccountAccess struct {
	DefaultAction any
	IpRule any
}

type Account_NetworkProfile struct {
	AccountAccess any
	NodeManagementAccess any
}

type Account_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Account_EncryptionFields = sdk.FieldMap{
		"KeyVaultKeyId": sdk.FieldSpec{WireName: "key_vault_key_id"},
	}

var Account_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Account_KeyVaultReferenceFields = sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Url": sdk.FieldSpec{WireName: "url"},
	}

var Account_NetworkProfile_AccountAccess_IpRuleFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"IpRange": sdk.FieldSpec{WireName: "ip_range"},
	}

var Account_NetworkProfile_AccountAccessFields = sdk.FieldMap{
		"DefaultAction": sdk.FieldSpec{WireName: "default_action"},
		"IpRule": sdk.FieldSpec{
			WireName: "ip_rule",
			Kind: "list",
			Fields: Account_NetworkProfile_AccountAccess_IpRuleFields,
		},
	}

var Account_NetworkProfileFields = sdk.FieldMap{
		"AccountAccess": sdk.FieldSpec{
			WireName: "account_access",
			Kind: "list",
			Fields: Account_NetworkProfile_AccountAccessFields,
		},
		"NodeManagementAccess": sdk.FieldSpec{
			WireName: "node_management_access",
			Kind: "list",
			Fields: Account_NetworkProfile_AccountAccessFields,
		},
	}

var Account_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AccountConfig struct {
	AllowedAuthenticationModes any
	Encryption any
	Id any
	Location any
	Name any
	PoolAllocationMode any
	PublicNetworkAccessEnabled any
	ResourceGroupName any
	StorageAccountAuthenticationMode any
	StorageAccountId any
	StorageAccountNodeIdentity any
	Tags any
	Identity any
	KeyVaultReference any
	NetworkProfile any
	Timeouts any
}

var Account = sdk.ResourceBinding{
	WireType: "azurerm_batch_account",
	Fields: sdk.FieldMap{
		"AllowedAuthenticationModes": sdk.FieldSpec{WireName: "allowed_authentication_modes"},
		"Encryption": sdk.FieldSpec{
			WireName: "encryption",
			Kind: "list",
			Fields: Account_EncryptionFields,
		},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PoolAllocationMode": sdk.FieldSpec{WireName: "pool_allocation_mode"},
		"PublicNetworkAccessEnabled": sdk.FieldSpec{WireName: "public_network_access_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"StorageAccountAuthenticationMode": sdk.FieldSpec{WireName: "storage_account_authentication_mode"},
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
		"StorageAccountNodeIdentity": sdk.FieldSpec{WireName: "storage_account_node_identity"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Account_IdentityFields,
		},
		"KeyVaultReference": sdk.FieldSpec{
			WireName: "key_vault_reference",
			Kind: "list",
			Fields: Account_KeyVaultReferenceFields,
		},
		"NetworkProfile": sdk.FieldSpec{
			WireName: "network_profile",
			Kind: "list",
			Fields: Account_NetworkProfileFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Account_TimeoutsFields,
		},
	},
}
