// Code generated by `ubx sdk gen` from azurerm_advisor_suppression. DO NOT EDIT.
package advisor

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Suppression_Timeouts struct {
	Create any
	Delete any
	Read any
}

var Suppression_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type SuppressionConfig struct {
	Id any
	Name any
	RecommendationId any
	ResourceId any
	Ttl any
	Timeouts any
}

var Suppression = sdk.ResourceBinding{
	WireType: "azurerm_advisor_suppression",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RecommendationId": sdk.FieldSpec{WireName: "recommendation_id"},
		"ResourceId": sdk.FieldSpec{WireName: "resource_id"},
		"Ttl": sdk.FieldSpec{WireName: "ttl"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Suppression_TimeoutsFields,
		},
	},
}
