// Code generated by `ubx sdk gen` from azurerm_stream_analytics_stream_input_eventhub_v2. DO NOT EDIT.
package stream

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AnalyticsStreamInputEventhubV2_Serialization struct {
	Encoding any
	FieldDelimiter any
	Type any
}

type AnalyticsStreamInputEventhubV2_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AnalyticsStreamInputEventhubV2_SerializationFields = sdk.FieldMap{
		"Encoding": sdk.FieldSpec{WireName: "encoding"},
		"FieldDelimiter": sdk.FieldSpec{WireName: "field_delimiter"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var AnalyticsStreamInputEventhubV2_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AnalyticsStreamInputEventhubV2Config struct {
	AuthenticationMode any
	EventhubConsumerGroupName any
	EventhubName any
	Id any
	Name any
	PartitionKey any
	ServicebusNamespace any
	SharedAccessPolicyKey any
	SharedAccessPolicyName any
	StreamAnalyticsJobId any
	Serialization any
	Timeouts any
}

var AnalyticsStreamInputEventhubV2 = sdk.ResourceBinding{
	WireType: "azurerm_stream_analytics_stream_input_eventhub_v2",
	Fields: sdk.FieldMap{
		"AuthenticationMode": sdk.FieldSpec{WireName: "authentication_mode"},
		"EventhubConsumerGroupName": sdk.FieldSpec{WireName: "eventhub_consumer_group_name"},
		"EventhubName": sdk.FieldSpec{WireName: "eventhub_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PartitionKey": sdk.FieldSpec{WireName: "partition_key"},
		"ServicebusNamespace": sdk.FieldSpec{WireName: "servicebus_namespace"},
		"SharedAccessPolicyKey": sdk.FieldSpec{WireName: "shared_access_policy_key"},
		"SharedAccessPolicyName": sdk.FieldSpec{WireName: "shared_access_policy_name"},
		"StreamAnalyticsJobId": sdk.FieldSpec{WireName: "stream_analytics_job_id"},
		"Serialization": sdk.FieldSpec{
			WireName: "serialization",
			Kind: "list",
			Fields: AnalyticsStreamInputEventhubV2_SerializationFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AnalyticsStreamInputEventhubV2_TimeoutsFields,
		},
	},
}
