// Code generated by `ubx sdk gen` from azurerm_stream_analytics_job. DO NOT EDIT.
package stream

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AnalyticsJob_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type AnalyticsJob_JobStorageAccount struct {
	AccountKey any
	AccountName any
	AuthenticationMode any
}

type AnalyticsJob_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AnalyticsJob_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var AnalyticsJob_JobStorageAccountFields = sdk.FieldMap{
		"AccountKey": sdk.FieldSpec{WireName: "account_key"},
		"AccountName": sdk.FieldSpec{WireName: "account_name"},
		"AuthenticationMode": sdk.FieldSpec{WireName: "authentication_mode"},
	}

var AnalyticsJob_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AnalyticsJobConfig struct {
	CompatibilityLevel any
	ContentStoragePolicy any
	DataLocale any
	EventsLateArrivalMaxDelayInSeconds any
	EventsOutOfOrderMaxDelayInSeconds any
	EventsOutOfOrderPolicy any
	Id any
	Location any
	Name any
	OutputErrorPolicy any
	ResourceGroupName any
	SkuName any
	StreamAnalyticsClusterId any
	StreamingUnits any
	Tags any
	TransformationQuery any
	Type any
	Identity any
	JobStorageAccount any
	Timeouts any
}

var AnalyticsJob = sdk.ResourceBinding{
	WireType: "azurerm_stream_analytics_job",
	Fields: sdk.FieldMap{
		"CompatibilityLevel": sdk.FieldSpec{WireName: "compatibility_level"},
		"ContentStoragePolicy": sdk.FieldSpec{WireName: "content_storage_policy"},
		"DataLocale": sdk.FieldSpec{WireName: "data_locale"},
		"EventsLateArrivalMaxDelayInSeconds": sdk.FieldSpec{WireName: "events_late_arrival_max_delay_in_seconds"},
		"EventsOutOfOrderMaxDelayInSeconds": sdk.FieldSpec{WireName: "events_out_of_order_max_delay_in_seconds"},
		"EventsOutOfOrderPolicy": sdk.FieldSpec{WireName: "events_out_of_order_policy"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OutputErrorPolicy": sdk.FieldSpec{WireName: "output_error_policy"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SkuName": sdk.FieldSpec{WireName: "sku_name"},
		"StreamAnalyticsClusterId": sdk.FieldSpec{WireName: "stream_analytics_cluster_id"},
		"StreamingUnits": sdk.FieldSpec{WireName: "streaming_units"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TransformationQuery": sdk.FieldSpec{WireName: "transformation_query"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: AnalyticsJob_IdentityFields,
		},
		"JobStorageAccount": sdk.FieldSpec{
			WireName: "job_storage_account",
			Kind: "list",
			Fields: AnalyticsJob_JobStorageAccountFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AnalyticsJob_TimeoutsFields,
		},
	},
}
