// Code generated by `ubx sdk gen` from azurerm_stream_analytics_reference_input_mssql. DO NOT EDIT.
package stream

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AnalyticsReferenceInputMssql_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AnalyticsReferenceInputMssql_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AnalyticsReferenceInputMssqlConfig struct {
	Database any
	DeltaSnapshotQuery any
	FullSnapshotQuery any
	Id any
	Name any
	Password any
	RefreshIntervalDuration any
	RefreshType any
	ResourceGroupName any
	Server any
	StreamAnalyticsJobName any
	Table any
	Username any
	Timeouts any
}

var AnalyticsReferenceInputMssql = sdk.ResourceBinding{
	WireType: "azurerm_stream_analytics_reference_input_mssql",
	Fields: sdk.FieldMap{
		"Database": sdk.FieldSpec{WireName: "database"},
		"DeltaSnapshotQuery": sdk.FieldSpec{WireName: "delta_snapshot_query"},
		"FullSnapshotQuery": sdk.FieldSpec{WireName: "full_snapshot_query"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Password": sdk.FieldSpec{WireName: "password"},
		"RefreshIntervalDuration": sdk.FieldSpec{WireName: "refresh_interval_duration"},
		"RefreshType": sdk.FieldSpec{WireName: "refresh_type"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Server": sdk.FieldSpec{WireName: "server"},
		"StreamAnalyticsJobName": sdk.FieldSpec{WireName: "stream_analytics_job_name"},
		"Table": sdk.FieldSpec{WireName: "table"},
		"Username": sdk.FieldSpec{WireName: "username"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AnalyticsReferenceInputMssql_TimeoutsFields,
		},
	},
}
