// Code generated by `ubx sdk gen` from azurerm_advanced_threat_protection. DO NOT EDIT.
package advanced

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ThreatProtection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ThreatProtection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ThreatProtectionConfig struct {
	Enabled any
	Id any
	TargetResourceId any
	Timeouts any
}

var ThreatProtection = sdk.ResourceBinding{
	WireType: "azurerm_advanced_threat_protection",
	Fields: sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"TargetResourceId": sdk.FieldSpec{WireName: "target_resource_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ThreatProtection_TimeoutsFields,
		},
	},
}
