// Code generated by `ubx sdk gen` from azurerm_dns_caa_record. DO NOT EDIT.
package dns

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CaaRecord_Record struct {
	Flags any
	Tag any
	Value any
}

type CaaRecord_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CaaRecord_RecordFields = sdk.FieldMap{
		"Flags": sdk.FieldSpec{WireName: "flags"},
		"Tag": sdk.FieldSpec{WireName: "tag"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var CaaRecord_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CaaRecordConfig struct {
	Id any
	Name any
	ResourceGroupName any
	Tags any
	Ttl any
	ZoneName any
	Record any
	Timeouts any
}

var CaaRecord = sdk.ResourceBinding{
	WireType: "azurerm_dns_caa_record",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Ttl": sdk.FieldSpec{WireName: "ttl"},
		"ZoneName": sdk.FieldSpec{WireName: "zone_name"},
		"Record": sdk.FieldSpec{
			WireName: "record",
			Kind: "set",
			Fields: CaaRecord_RecordFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CaaRecord_TimeoutsFields,
		},
	},
}
