// Code generated by `ubx sdk gen` from azurerm_dns_cname_record. DO NOT EDIT.
package dns

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CnameRecord_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CnameRecord_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CnameRecordConfig struct {
	Id any
	Name any
	Record any
	ResourceGroupName any
	Tags any
	TargetResourceId any
	Ttl any
	ZoneName any
	Timeouts any
}

var CnameRecord = sdk.ResourceBinding{
	WireType: "azurerm_dns_cname_record",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Record": sdk.FieldSpec{WireName: "record"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TargetResourceId": sdk.FieldSpec{WireName: "target_resource_id"},
		"Ttl": sdk.FieldSpec{WireName: "ttl"},
		"ZoneName": sdk.FieldSpec{WireName: "zone_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CnameRecord_TimeoutsFields,
		},
	},
}
