// Code generated by `ubx sdk gen` from azurerm_dns_mx_record. DO NOT EDIT.
package dns

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type MxRecord_Record struct {
	Exchange any
	Preference any
}

type MxRecord_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var MxRecord_RecordFields = sdk.FieldMap{
		"Exchange": sdk.FieldSpec{WireName: "exchange"},
		"Preference": sdk.FieldSpec{WireName: "preference"},
	}

var MxRecord_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type MxRecordConfig struct {
	Id any
	Name any
	ResourceGroupName any
	Tags any
	Ttl any
	ZoneName any
	Record any
	Timeouts any
}

var MxRecord = sdk.ResourceBinding{
	WireType: "azurerm_dns_mx_record",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Ttl": sdk.FieldSpec{WireName: "ttl"},
		"ZoneName": sdk.FieldSpec{WireName: "zone_name"},
		"Record": sdk.FieldSpec{
			WireName: "record",
			Kind: "set",
			Fields: MxRecord_RecordFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: MxRecord_TimeoutsFields,
		},
	},
}
