// Code generated by `ubx sdk gen` from azurerm_stack_hci_network_interface. DO NOT EDIT.
package stack

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type HciNetworkInterface_IpConfiguration struct {
	Gateway any
	PrefixLength any
	PrivateIpAddress any
	SubnetId any
}

type HciNetworkInterface_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var HciNetworkInterface_IpConfigurationFields = sdk.FieldMap{
		"Gateway": sdk.FieldSpec{WireName: "gateway"},
		"PrefixLength": sdk.FieldSpec{WireName: "prefix_length"},
		"PrivateIpAddress": sdk.FieldSpec{WireName: "private_ip_address"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
	}

var HciNetworkInterface_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type HciNetworkInterfaceConfig struct {
	CustomLocationId any
	DnsServers any
	Id any
	Location any
	MacAddress any
	Name any
	ResourceGroupName any
	Tags any
	IpConfiguration any
	Timeouts any
}

var HciNetworkInterface = sdk.ResourceBinding{
	WireType: "azurerm_stack_hci_network_interface",
	Fields: sdk.FieldMap{
		"CustomLocationId": sdk.FieldSpec{WireName: "custom_location_id"},
		"DnsServers": sdk.FieldSpec{WireName: "dns_servers"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MacAddress": sdk.FieldSpec{WireName: "mac_address"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"IpConfiguration": sdk.FieldSpec{
			WireName: "ip_configuration",
			Kind: "list",
			Fields: HciNetworkInterface_IpConfigurationFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: HciNetworkInterface_TimeoutsFields,
		},
	},
}
