// Code generated by `ubx sdk gen` from azurerm_stack_hci_cluster. DO NOT EDIT.
package stack

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type HciCluster_Identity struct {
	PrincipalId any
	TenantId any
	Type any
}

type HciCluster_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var HciCluster_IdentityFields = sdk.FieldMap{
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var HciCluster_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type HciClusterConfig struct {
	AutomanageConfigurationId any
	ClientId any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	TenantId any
	Identity any
	Timeouts any
}

var HciCluster = sdk.ResourceBinding{
	WireType: "azurerm_stack_hci_cluster",
	Fields: sdk.FieldMap{
		"AutomanageConfigurationId": sdk.FieldSpec{WireName: "automanage_configuration_id"},
		"ClientId": sdk.FieldSpec{WireName: "client_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: HciCluster_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: HciCluster_TimeoutsFields,
		},
	},
}
