// Code generated by `ubx sdk gen` from azurerm_stack_hci_extension. DO NOT EDIT.
package stack

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type HciExtension_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var HciExtension_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type HciExtensionConfig struct {
	ArcSettingId any
	AutoUpgradeMinorVersionEnabled any
	AutomaticUpgradeEnabled any
	Id any
	Name any
	ProtectedSettings any
	Publisher any
	Settings any
	Type any
	TypeHandlerVersion any
	Timeouts any
}

var HciExtension = sdk.ResourceBinding{
	WireType: "azurerm_stack_hci_extension",
	Fields: sdk.FieldMap{
		"ArcSettingId": sdk.FieldSpec{WireName: "arc_setting_id"},
		"AutoUpgradeMinorVersionEnabled": sdk.FieldSpec{WireName: "auto_upgrade_minor_version_enabled"},
		"AutomaticUpgradeEnabled": sdk.FieldSpec{WireName: "automatic_upgrade_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ProtectedSettings": sdk.FieldSpec{WireName: "protected_settings"},
		"Publisher": sdk.FieldSpec{WireName: "publisher"},
		"Settings": sdk.FieldSpec{WireName: "settings"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"TypeHandlerVersion": sdk.FieldSpec{WireName: "type_handler_version"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: HciExtension_TimeoutsFields,
		},
	},
}
