// Code generated by `ubx sdk gen` from azurerm_site_recovery_vmware_replication_policy. DO NOT EDIT.
package site

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type RecoveryVmwareReplicationPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var RecoveryVmwareReplicationPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type RecoveryVmwareReplicationPolicyConfig struct {
	ApplicationConsistentSnapshotFrequencyInMinutes any
	Id any
	Name any
	RecoveryPointRetentionInMinutes any
	RecoveryVaultId any
	Timeouts any
}

var RecoveryVmwareReplicationPolicy = sdk.ResourceBinding{
	WireType: "azurerm_site_recovery_vmware_replication_policy",
	Fields: sdk.FieldMap{
		"ApplicationConsistentSnapshotFrequencyInMinutes": sdk.FieldSpec{WireName: "application_consistent_snapshot_frequency_in_minutes"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RecoveryPointRetentionInMinutes": sdk.FieldSpec{WireName: "recovery_point_retention_in_minutes"},
		"RecoveryVaultId": sdk.FieldSpec{WireName: "recovery_vault_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: RecoveryVmwareReplicationPolicy_TimeoutsFields,
		},
	},
}
