// Code generated by `ubx sdk gen` from azurerm_workloads_sap_discovery_virtual_instance. DO NOT EDIT.
package workloads

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SapDiscoveryVirtualInstance_Identity struct {
	IdentityIds any
	Type any
}

type SapDiscoveryVirtualInstance_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var SapDiscoveryVirtualInstance_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var SapDiscoveryVirtualInstance_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type SapDiscoveryVirtualInstanceConfig struct {
	CentralServerVirtualMachineId any
	Environment any
	Id any
	Location any
	ManagedResourceGroupName any
	ManagedResourcesNetworkAccessType any
	ManagedStorageAccountName any
	Name any
	ResourceGroupName any
	SapProduct any
	Tags any
	Identity any
	Timeouts any
}

var SapDiscoveryVirtualInstance = sdk.ResourceBinding{
	WireType: "azurerm_workloads_sap_discovery_virtual_instance",
	Fields: sdk.FieldMap{
		"CentralServerVirtualMachineId": sdk.FieldSpec{WireName: "central_server_virtual_machine_id"},
		"Environment": sdk.FieldSpec{WireName: "environment"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"ManagedResourceGroupName": sdk.FieldSpec{WireName: "managed_resource_group_name"},
		"ManagedResourcesNetworkAccessType": sdk.FieldSpec{WireName: "managed_resources_network_access_type"},
		"ManagedStorageAccountName": sdk.FieldSpec{WireName: "managed_storage_account_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SapProduct": sdk.FieldSpec{WireName: "sap_product"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: SapDiscoveryVirtualInstance_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SapDiscoveryVirtualInstance_TimeoutsFields,
		},
	},
}
