// Code generated by `ubx sdk gen` from azurerm_email_communication_service_domain_sender_username. DO NOT EDIT.
package email

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CommunicationServiceDomainSenderUsername_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CommunicationServiceDomainSenderUsername_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CommunicationServiceDomainSenderUsernameConfig struct {
	DisplayName any
	EmailServiceDomainId any
	Id any
	Name any
	Timeouts any
}

var CommunicationServiceDomainSenderUsername = sdk.ResourceBinding{
	WireType: "azurerm_email_communication_service_domain_sender_username",
	Fields: sdk.FieldMap{
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"EmailServiceDomainId": sdk.FieldSpec{WireName: "email_service_domain_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CommunicationServiceDomainSenderUsername_TimeoutsFields,
		},
	},
}
