// Code generated by `ubx sdk gen` from azurerm_cost_management_scheduled_action. DO NOT EDIT.
package cost

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagementScheduledAction_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagementScheduledAction_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagementScheduledActionConfig struct {
	DayOfMonth any
	DaysOfWeek any
	DisplayName any
	EmailAddressSender any
	EmailAddresses any
	EmailSubject any
	EndDate any
	Frequency any
	HourOfDay any
	Id any
	Message any
	Name any
	StartDate any
	ViewId any
	WeeksOfMonth any
	Timeouts any
}

var ManagementScheduledAction = sdk.ResourceBinding{
	WireType: "azurerm_cost_management_scheduled_action",
	Fields: sdk.FieldMap{
		"DayOfMonth": sdk.FieldSpec{WireName: "day_of_month"},
		"DaysOfWeek": sdk.FieldSpec{WireName: "days_of_week"},
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"EmailAddressSender": sdk.FieldSpec{WireName: "email_address_sender"},
		"EmailAddresses": sdk.FieldSpec{WireName: "email_addresses"},
		"EmailSubject": sdk.FieldSpec{WireName: "email_subject"},
		"EndDate": sdk.FieldSpec{WireName: "end_date"},
		"Frequency": sdk.FieldSpec{WireName: "frequency"},
		"HourOfDay": sdk.FieldSpec{WireName: "hour_of_day"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Message": sdk.FieldSpec{WireName: "message"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"StartDate": sdk.FieldSpec{WireName: "start_date"},
		"ViewId": sdk.FieldSpec{WireName: "view_id"},
		"WeeksOfMonth": sdk.FieldSpec{WireName: "weeks_of_month"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagementScheduledAction_TimeoutsFields,
		},
	},
}
