// Code generated by `ubx sdk gen` from azurerm_log_analytics_workspace_table. DO NOT EDIT.
package log

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AnalyticsWorkspaceTable_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AnalyticsWorkspaceTable_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AnalyticsWorkspaceTableConfig struct {
	Id any
	Name any
	Plan any
	RetentionInDays any
	TotalRetentionInDays any
	WorkspaceId any
	Timeouts any
}

var AnalyticsWorkspaceTable = sdk.ResourceBinding{
	WireType: "azurerm_log_analytics_workspace_table",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Plan": sdk.FieldSpec{WireName: "plan"},
		"RetentionInDays": sdk.FieldSpec{WireName: "retention_in_days"},
		"TotalRetentionInDays": sdk.FieldSpec{WireName: "total_retention_in_days"},
		"WorkspaceId": sdk.FieldSpec{WireName: "workspace_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AnalyticsWorkspaceTable_TimeoutsFields,
		},
	},
}
