// Code generated by `ubx sdk gen` from azurerm_log_analytics_query_pack. DO NOT EDIT.
package log

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AnalyticsQueryPack_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AnalyticsQueryPack_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AnalyticsQueryPackConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	Timeouts any
}

var AnalyticsQueryPack = sdk.ResourceBinding{
	WireType: "azurerm_log_analytics_query_pack",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AnalyticsQueryPack_TimeoutsFields,
		},
	},
}
