// Code generated by `ubx sdk gen` from azurerm_frontdoor_firewall_policy. DO NOT EDIT.
package frontdoor

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FirewallPolicy_CustomRule_MatchCondition struct {
	MatchValues any
	MatchVariable any
	NegationCondition any
	Operator any
	Selector any
	Transforms any
}

type FirewallPolicy_CustomRule struct {
	Action any
	Enabled any
	Name any
	Priority any
	RateLimitDurationInMinutes any
	RateLimitThreshold any
	Type any
	MatchCondition any
}

type FirewallPolicy_ManagedRule_Exclusion struct {
	MatchVariable any
	Operator any
	Selector any
}

type FirewallPolicy_ManagedRule_Override_Rule struct {
	Action any
	Enabled any
	RuleId any
	Exclusion any
}

type FirewallPolicy_ManagedRule_Override struct {
	RuleGroupName any
	Exclusion any
	Rule any
}

type FirewallPolicy_ManagedRule struct {
	Type any
	Version any
	Exclusion any
	Override any
}

type FirewallPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FirewallPolicy_CustomRule_MatchConditionFields = sdk.FieldMap{
		"MatchValues": sdk.FieldSpec{WireName: "match_values"},
		"MatchVariable": sdk.FieldSpec{WireName: "match_variable"},
		"NegationCondition": sdk.FieldSpec{WireName: "negation_condition"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Selector": sdk.FieldSpec{WireName: "selector"},
		"Transforms": sdk.FieldSpec{WireName: "transforms"},
	}

var FirewallPolicy_CustomRuleFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"RateLimitDurationInMinutes": sdk.FieldSpec{WireName: "rate_limit_duration_in_minutes"},
		"RateLimitThreshold": sdk.FieldSpec{WireName: "rate_limit_threshold"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"MatchCondition": sdk.FieldSpec{
			WireName: "match_condition",
			Kind: "list",
			Fields: FirewallPolicy_CustomRule_MatchConditionFields,
		},
	}

var FirewallPolicy_ManagedRule_ExclusionFields = sdk.FieldMap{
		"MatchVariable": sdk.FieldSpec{WireName: "match_variable"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Selector": sdk.FieldSpec{WireName: "selector"},
	}

var FirewallPolicy_ManagedRule_Override_RuleFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"RuleId": sdk.FieldSpec{WireName: "rule_id"},
		"Exclusion": sdk.FieldSpec{
			WireName: "exclusion",
			Kind: "list",
			Fields: FirewallPolicy_ManagedRule_ExclusionFields,
		},
	}

var FirewallPolicy_ManagedRule_OverrideFields = sdk.FieldMap{
		"RuleGroupName": sdk.FieldSpec{WireName: "rule_group_name"},
		"Exclusion": sdk.FieldSpec{
			WireName: "exclusion",
			Kind: "list",
			Fields: FirewallPolicy_ManagedRule_ExclusionFields,
		},
		"Rule": sdk.FieldSpec{
			WireName: "rule",
			Kind: "list",
			Fields: FirewallPolicy_ManagedRule_Override_RuleFields,
		},
	}

var FirewallPolicy_ManagedRuleFields = sdk.FieldMap{
		"Type": sdk.FieldSpec{WireName: "type"},
		"Version": sdk.FieldSpec{WireName: "version"},
		"Exclusion": sdk.FieldSpec{
			WireName: "exclusion",
			Kind: "list",
			Fields: FirewallPolicy_ManagedRule_ExclusionFields,
		},
		"Override": sdk.FieldSpec{
			WireName: "override",
			Kind: "list",
			Fields: FirewallPolicy_ManagedRule_OverrideFields,
		},
	}

var FirewallPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FirewallPolicyConfig struct {
	CustomBlockResponseBody any
	CustomBlockResponseStatusCode any
	Enabled any
	Id any
	Mode any
	Name any
	RedirectUrl any
	ResourceGroupName any
	Tags any
	CustomRule any
	ManagedRule any
	Timeouts any
}

var FirewallPolicy = sdk.ResourceBinding{
	WireType: "azurerm_frontdoor_firewall_policy",
	Fields: sdk.FieldMap{
		"CustomBlockResponseBody": sdk.FieldSpec{WireName: "custom_block_response_body"},
		"CustomBlockResponseStatusCode": sdk.FieldSpec{WireName: "custom_block_response_status_code"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Mode": sdk.FieldSpec{WireName: "mode"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RedirectUrl": sdk.FieldSpec{WireName: "redirect_url"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"CustomRule": sdk.FieldSpec{
			WireName: "custom_rule",
			Kind: "list",
			Fields: FirewallPolicy_CustomRuleFields,
		},
		"ManagedRule": sdk.FieldSpec{
			WireName: "managed_rule",
			Kind: "list",
			Fields: FirewallPolicy_ManagedRuleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FirewallPolicy_TimeoutsFields,
		},
	},
}
