// Code generated by `ubx sdk gen` from azurerm_bot_channel_sms. DO NOT EDIT.
package bot

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ChannelSms_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ChannelSms_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ChannelSmsConfig struct {
	BotName any
	Id any
	Location any
	PhoneNumber any
	ResourceGroupName any
	SmsChannelAccountSecurityId any
	SmsChannelAuthToken any
	Timeouts any
}

var ChannelSms = sdk.ResourceBinding{
	WireType: "azurerm_bot_channel_sms",
	Fields: sdk.FieldMap{
		"BotName": sdk.FieldSpec{WireName: "bot_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"PhoneNumber": sdk.FieldSpec{WireName: "phone_number"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SmsChannelAccountSecurityId": sdk.FieldSpec{WireName: "sms_channel_account_security_id"},
		"SmsChannelAuthToken": sdk.FieldSpec{WireName: "sms_channel_auth_token"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ChannelSms_TimeoutsFields,
		},
	},
}
