// Code generated by `ubx sdk gen` from azurerm_bot_channel_facebook. DO NOT EDIT.
package bot

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ChannelFacebook_Page struct {
	AccessToken any
	Id any
}

type ChannelFacebook_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ChannelFacebook_PageFields = sdk.FieldMap{
		"AccessToken": sdk.FieldSpec{WireName: "access_token"},
		"Id": sdk.FieldSpec{WireName: "id"},
	}

var ChannelFacebook_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ChannelFacebookConfig struct {
	BotName any
	FacebookApplicationId any
	FacebookApplicationSecret any
	Id any
	Location any
	ResourceGroupName any
	Page any
	Timeouts any
}

var ChannelFacebook = sdk.ResourceBinding{
	WireType: "azurerm_bot_channel_facebook",
	Fields: sdk.FieldMap{
		"BotName": sdk.FieldSpec{WireName: "bot_name"},
		"FacebookApplicationId": sdk.FieldSpec{WireName: "facebook_application_id"},
		"FacebookApplicationSecret": sdk.FieldSpec{WireName: "facebook_application_secret"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Page": sdk.FieldSpec{
			WireName: "page",
			Kind: "set",
			Fields: ChannelFacebook_PageFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ChannelFacebook_TimeoutsFields,
		},
	},
}
