// Code generated by `ubx sdk gen` from azurerm_bot_connection. DO NOT EDIT.
package bot

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Connection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Connection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ConnectionConfig struct {
	BotName any
	ClientId any
	ClientSecret any
	Id any
	Location any
	Name any
	Parameters any
	ResourceGroupName any
	Scopes any
	ServiceProviderName any
	Timeouts any
}

var Connection = sdk.ResourceBinding{
	WireType: "azurerm_bot_connection",
	Fields: sdk.FieldMap{
		"BotName": sdk.FieldSpec{WireName: "bot_name"},
		"ClientId": sdk.FieldSpec{WireName: "client_id"},
		"ClientSecret": sdk.FieldSpec{WireName: "client_secret"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Scopes": sdk.FieldSpec{WireName: "scopes"},
		"ServiceProviderName": sdk.FieldSpec{WireName: "service_provider_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Connection_TimeoutsFields,
		},
	},
}
