// Code generated by `ubx sdk gen` from azurerm_bot_web_app. DO NOT EDIT.
package bot

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type WebApp_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var WebApp_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type WebAppConfig struct {
	DeveloperAppInsightsApiKey any
	DeveloperAppInsightsApplicationId any
	DeveloperAppInsightsKey any
	DisplayName any
	Endpoint any
	Id any
	Location any
	LuisAppIds any
	LuisKey any
	MicrosoftAppId any
	MicrosoftAppTenantId any
	MicrosoftAppType any
	MicrosoftAppUserAssignedIdentityId any
	Name any
	ResourceGroupName any
	Sku any
	Tags any
	Timeouts any
}

var WebApp = sdk.ResourceBinding{
	WireType: "azurerm_bot_web_app",
	Fields: sdk.FieldMap{
		"DeveloperAppInsightsApiKey": sdk.FieldSpec{WireName: "developer_app_insights_api_key"},
		"DeveloperAppInsightsApplicationId": sdk.FieldSpec{WireName: "developer_app_insights_application_id"},
		"DeveloperAppInsightsKey": sdk.FieldSpec{WireName: "developer_app_insights_key"},
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"Endpoint": sdk.FieldSpec{WireName: "endpoint"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"LuisAppIds": sdk.FieldSpec{WireName: "luis_app_ids"},
		"LuisKey": sdk.FieldSpec{WireName: "luis_key"},
		"MicrosoftAppId": sdk.FieldSpec{WireName: "microsoft_app_id"},
		"MicrosoftAppTenantId": sdk.FieldSpec{WireName: "microsoft_app_tenant_id"},
		"MicrosoftAppType": sdk.FieldSpec{WireName: "microsoft_app_type"},
		"MicrosoftAppUserAssignedIdentityId": sdk.FieldSpec{WireName: "microsoft_app_user_assigned_identity_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: WebApp_TimeoutsFields,
		},
	},
}
