// Code generated by `ubx sdk gen` from azurerm_eventhub_namespace. DO NOT EDIT.
package eventhub

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Namespace_NetworkRulesets_IpRule struct {
	Action any
	IpMask any
}

type Namespace_NetworkRulesets_VirtualNetworkRule struct {
	IgnoreMissingVirtualNetworkServiceEndpoint any
	SubnetId any
}

type Namespace_NetworkRulesets struct {
	DefaultAction any
	IpRule any
	PublicNetworkAccessEnabled any
	TrustedServiceAccessEnabled any
	VirtualNetworkRule any
}

type Namespace_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Namespace_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Namespace_NetworkRulesets_IpRuleFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"IpMask": sdk.FieldSpec{WireName: "ip_mask"},
	}

var Namespace_NetworkRulesets_VirtualNetworkRuleFields = sdk.FieldMap{
		"IgnoreMissingVirtualNetworkServiceEndpoint": sdk.FieldSpec{WireName: "ignore_missing_virtual_network_service_endpoint"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
	}

var Namespace_NetworkRulesetsFields = sdk.FieldMap{
		"DefaultAction": sdk.FieldSpec{WireName: "default_action"},
		"IpRule": sdk.FieldSpec{
			WireName: "ip_rule",
			Kind: "list",
			Fields: Namespace_NetworkRulesets_IpRuleFields,
		},
		"PublicNetworkAccessEnabled": sdk.FieldSpec{WireName: "public_network_access_enabled"},
		"TrustedServiceAccessEnabled": sdk.FieldSpec{WireName: "trusted_service_access_enabled"},
		"VirtualNetworkRule": sdk.FieldSpec{
			WireName: "virtual_network_rule",
			Kind: "set",
			Fields: Namespace_NetworkRulesets_VirtualNetworkRuleFields,
		},
	}

var Namespace_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Namespace_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type NamespaceConfig struct {
	AutoInflateEnabled any
	Capacity any
	DedicatedClusterId any
	Id any
	LocalAuthenticationEnabled any
	Location any
	MaximumThroughputUnits any
	MinimumTlsVersion any
	Name any
	NetworkRulesets any
	PublicNetworkAccessEnabled any
	ResourceGroupName any
	Sku any
	Tags any
	Identity any
	Timeouts any
}

var Namespace = sdk.ResourceBinding{
	WireType: "azurerm_eventhub_namespace",
	Fields: sdk.FieldMap{
		"AutoInflateEnabled": sdk.FieldSpec{WireName: "auto_inflate_enabled"},
		"Capacity": sdk.FieldSpec{WireName: "capacity"},
		"DedicatedClusterId": sdk.FieldSpec{WireName: "dedicated_cluster_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LocalAuthenticationEnabled": sdk.FieldSpec{WireName: "local_authentication_enabled"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MaximumThroughputUnits": sdk.FieldSpec{WireName: "maximum_throughput_units"},
		"MinimumTlsVersion": sdk.FieldSpec{WireName: "minimum_tls_version"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkRulesets": sdk.FieldSpec{
			WireName: "network_rulesets",
			Kind: "list",
			Fields: Namespace_NetworkRulesetsFields,
		},
		"PublicNetworkAccessEnabled": sdk.FieldSpec{WireName: "public_network_access_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Namespace_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Namespace_TimeoutsFields,
		},
	},
}
