// Code generated by `ubx sdk gen` from azurerm_network_interface_nat_rule_association. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type InterfaceNatRuleAssociation_Timeouts struct {
	Create any
	Delete any
	Read any
}

var InterfaceNatRuleAssociation_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type InterfaceNatRuleAssociationConfig struct {
	Id any
	IpConfigurationName any
	NatRuleId any
	NetworkInterfaceId any
	Timeouts any
}

var InterfaceNatRuleAssociation = sdk.ResourceBinding{
	WireType: "azurerm_network_interface_nat_rule_association",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"IpConfigurationName": sdk.FieldSpec{WireName: "ip_configuration_name"},
		"NatRuleId": sdk.FieldSpec{WireName: "nat_rule_id"},
		"NetworkInterfaceId": sdk.FieldSpec{WireName: "network_interface_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: InterfaceNatRuleAssociation_TimeoutsFields,
		},
	},
}
