// Code generated by `ubx sdk gen` from azurerm_network_interface_application_security_group_association. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type InterfaceApplicationSecurityGroupAssociation_Timeouts struct {
	Create any
	Delete any
	Read any
}

var InterfaceApplicationSecurityGroupAssociation_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type InterfaceApplicationSecurityGroupAssociationConfig struct {
	ApplicationSecurityGroupId any
	Id any
	NetworkInterfaceId any
	Timeouts any
}

var InterfaceApplicationSecurityGroupAssociation = sdk.ResourceBinding{
	WireType: "azurerm_network_interface_application_security_group_association",
	Fields: sdk.FieldMap{
		"ApplicationSecurityGroupId": sdk.FieldSpec{WireName: "application_security_group_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"NetworkInterfaceId": sdk.FieldSpec{WireName: "network_interface_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: InterfaceApplicationSecurityGroupAssociation_TimeoutsFields,
		},
	},
}
