// Code generated by `ubx sdk gen` from azurerm_network_manager_network_group. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerNetworkGroup_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagerNetworkGroup_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagerNetworkGroupConfig struct {
	Description any
	Id any
	MemberType any
	Name any
	NetworkManagerId any
	Timeouts any
}

var ManagerNetworkGroup = sdk.ResourceBinding{
	WireType: "azurerm_network_manager_network_group",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"MemberType": sdk.FieldSpec{WireName: "member_type"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkManagerId": sdk.FieldSpec{WireName: "network_manager_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerNetworkGroup_TimeoutsFields,
		},
	},
}
