// Code generated by `ubx sdk gen` from azurerm_network_manager_management_group_connection. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerManagementGroupConnection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagerManagementGroupConnection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagerManagementGroupConnectionConfig struct {
	Description any
	Id any
	ManagementGroupId any
	Name any
	NetworkManagerId any
	Timeouts any
}

var ManagerManagementGroupConnection = sdk.ResourceBinding{
	WireType: "azurerm_network_manager_management_group_connection",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ManagementGroupId": sdk.FieldSpec{WireName: "management_group_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkManagerId": sdk.FieldSpec{WireName: "network_manager_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerManagementGroupConnection_TimeoutsFields,
		},
	},
}
