// Code generated by `ubx sdk gen` from azurerm_network_manager_connectivity_configuration. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerConnectivityConfiguration_AppliesToGroup struct {
	GlobalMeshEnabled any
	GroupConnectivity any
	NetworkGroupId any
	UseHubGateway any
}

type ManagerConnectivityConfiguration_Hub struct {
	ResourceId any
	ResourceType any
}

type ManagerConnectivityConfiguration_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagerConnectivityConfiguration_AppliesToGroupFields = sdk.FieldMap{
		"GlobalMeshEnabled": sdk.FieldSpec{WireName: "global_mesh_enabled"},
		"GroupConnectivity": sdk.FieldSpec{WireName: "group_connectivity"},
		"NetworkGroupId": sdk.FieldSpec{WireName: "network_group_id"},
		"UseHubGateway": sdk.FieldSpec{WireName: "use_hub_gateway"},
	}

var ManagerConnectivityConfiguration_HubFields = sdk.FieldMap{
		"ResourceId": sdk.FieldSpec{WireName: "resource_id"},
		"ResourceType": sdk.FieldSpec{WireName: "resource_type"},
	}

var ManagerConnectivityConfiguration_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagerConnectivityConfigurationConfig struct {
	ConnectedGroupAddressOverlapEnabled any
	ConnectedGroupPrivateEndpointsScale any
	ConnectivityTopology any
	DeleteExistingPeeringEnabled any
	Description any
	GlobalMeshEnabled any
	Id any
	Name any
	NetworkManagerId any
	PeeringEnforcementEnabled any
	AppliesToGroup any
	Hub any
	Timeouts any
}

var ManagerConnectivityConfiguration = sdk.ResourceBinding{
	WireType: "azurerm_network_manager_connectivity_configuration",
	Fields: sdk.FieldMap{
		"ConnectedGroupAddressOverlapEnabled": sdk.FieldSpec{WireName: "connected_group_address_overlap_enabled"},
		"ConnectedGroupPrivateEndpointsScale": sdk.FieldSpec{WireName: "connected_group_private_endpoints_scale"},
		"ConnectivityTopology": sdk.FieldSpec{WireName: "connectivity_topology"},
		"DeleteExistingPeeringEnabled": sdk.FieldSpec{WireName: "delete_existing_peering_enabled"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"GlobalMeshEnabled": sdk.FieldSpec{WireName: "global_mesh_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkManagerId": sdk.FieldSpec{WireName: "network_manager_id"},
		"PeeringEnforcementEnabled": sdk.FieldSpec{WireName: "peering_enforcement_enabled"},
		"AppliesToGroup": sdk.FieldSpec{
			WireName: "applies_to_group",
			Kind: "list",
			Fields: ManagerConnectivityConfiguration_AppliesToGroupFields,
		},
		"Hub": sdk.FieldSpec{
			WireName: "hub",
			Kind: "list",
			Fields: ManagerConnectivityConfiguration_HubFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerConnectivityConfiguration_TimeoutsFields,
		},
	},
}
