// Code generated by `ubx sdk gen` from azurerm_network_manager_ipam_pool. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerIpamPool_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagerIpamPool_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagerIpamPoolConfig struct {
	AddressPrefixes any
	Description any
	DisplayName any
	Id any
	Location any
	Name any
	NetworkManagerId any
	ParentPoolName any
	Tags any
	Timeouts any
}

var ManagerIpamPool = sdk.ResourceBinding{
	WireType: "azurerm_network_manager_ipam_pool",
	Fields: sdk.FieldMap{
		"AddressPrefixes": sdk.FieldSpec{WireName: "address_prefixes"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkManagerId": sdk.FieldSpec{WireName: "network_manager_id"},
		"ParentPoolName": sdk.FieldSpec{WireName: "parent_pool_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerIpamPool_TimeoutsFields,
		},
	},
}
