// Code generated by `ubx sdk gen` from azurerm_network_manager_scope_connection. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerScopeConnection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagerScopeConnection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagerScopeConnectionConfig struct {
	Description any
	Id any
	Name any
	NetworkManagerId any
	TargetScopeId any
	TenantId any
	Timeouts any
}

var ManagerScopeConnection = sdk.ResourceBinding{
	WireType: "azurerm_network_manager_scope_connection",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkManagerId": sdk.FieldSpec{WireName: "network_manager_id"},
		"TargetScopeId": sdk.FieldSpec{WireName: "target_scope_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerScopeConnection_TimeoutsFields,
		},
	},
}
