// Code generated by `ubx sdk gen` from azurerm_network_manager_deployment. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerDeployment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagerDeployment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagerDeploymentConfig struct {
	ConfigurationIds any
	Id any
	Location any
	NetworkManagerId any
	ScopeAccess any
	Triggers any
	Timeouts any
}

var ManagerDeployment = sdk.ResourceBinding{
	WireType: "azurerm_network_manager_deployment",
	Fields: sdk.FieldMap{
		"ConfigurationIds": sdk.FieldSpec{WireName: "configuration_ids"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"NetworkManagerId": sdk.FieldSpec{WireName: "network_manager_id"},
		"ScopeAccess": sdk.FieldSpec{WireName: "scope_access"},
		"Triggers": sdk.FieldSpec{WireName: "triggers"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerDeployment_TimeoutsFields,
		},
	},
}
