// Code generated by `ubx sdk gen` from azurerm_network_manager_verifier_workspace_reachability_analysis_intent. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTraffic struct {
	DestinationIps any
	DestinationPorts any
	Protocols any
	SourceIps any
	SourcePorts any
}

type ManagerVerifierWorkspaceReachabilityAnalysisIntent_Timeouts struct {
	Create any
	Delete any
	Read any
}

var ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTrafficFields = sdk.FieldMap{
		"DestinationIps": sdk.FieldSpec{WireName: "destination_ips"},
		"DestinationPorts": sdk.FieldSpec{WireName: "destination_ports"},
		"Protocols": sdk.FieldSpec{WireName: "protocols"},
		"SourceIps": sdk.FieldSpec{WireName: "source_ips"},
		"SourcePorts": sdk.FieldSpec{WireName: "source_ports"},
	}

var ManagerVerifierWorkspaceReachabilityAnalysisIntent_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type ManagerVerifierWorkspaceReachabilityAnalysisIntentConfig struct {
	Description any
	DestinationResourceId any
	Id any
	Name any
	SourceResourceId any
	VerifierWorkspaceId any
	IpTraffic any
	Timeouts any
}

var ManagerVerifierWorkspaceReachabilityAnalysisIntent = sdk.ResourceBinding{
	WireType: "azurerm_network_manager_verifier_workspace_reachability_analysis_intent",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"DestinationResourceId": sdk.FieldSpec{WireName: "destination_resource_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SourceResourceId": sdk.FieldSpec{WireName: "source_resource_id"},
		"VerifierWorkspaceId": sdk.FieldSpec{WireName: "verifier_workspace_id"},
		"IpTraffic": sdk.FieldSpec{
			WireName: "ip_traffic",
			Kind: "list",
			Fields: ManagerVerifierWorkspaceReachabilityAnalysisIntent_IpTrafficFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerVerifierWorkspaceReachabilityAnalysisIntent_TimeoutsFields,
		},
	},
}
