// Code generated by `ubx sdk gen` from azurerm_network_profile. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Profile_ContainerNetworkInterface_IpConfiguration struct {
	Name any
	SubnetId any
}

type Profile_ContainerNetworkInterface struct {
	Name any
	IpConfiguration any
}

type Profile_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Profile_ContainerNetworkInterface_IpConfigurationFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
	}

var Profile_ContainerNetworkInterfaceFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"IpConfiguration": sdk.FieldSpec{
			WireName: "ip_configuration",
			Kind: "list",
			Fields: Profile_ContainerNetworkInterface_IpConfigurationFields,
		},
	}

var Profile_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ProfileConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	ContainerNetworkInterface any
	Timeouts any
}

var Profile = sdk.ResourceBinding{
	WireType: "azurerm_network_profile",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"ContainerNetworkInterface": sdk.FieldSpec{
			WireName: "container_network_interface",
			Kind: "list",
			Fields: Profile_ContainerNetworkInterfaceFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Profile_TimeoutsFields,
		},
	},
}
