// Code generated by `ubx sdk gen` from azurerm_network_security_perimeter_access_rule. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SecurityPerimeterAccessRule_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var SecurityPerimeterAccessRule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type SecurityPerimeterAccessRuleConfig struct {
	AddressPrefixes any
	Direction any
	Fqdns any
	Id any
	Name any
	NetworkSecurityPerimeterProfileId any
	ServiceTags any
	SubscriptionIds any
	Timeouts any
}

var SecurityPerimeterAccessRule = sdk.ResourceBinding{
	WireType: "azurerm_network_security_perimeter_access_rule",
	Fields: sdk.FieldMap{
		"AddressPrefixes": sdk.FieldSpec{WireName: "address_prefixes"},
		"Direction": sdk.FieldSpec{WireName: "direction"},
		"Fqdns": sdk.FieldSpec{WireName: "fqdns"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkSecurityPerimeterProfileId": sdk.FieldSpec{WireName: "network_security_perimeter_profile_id"},
		"ServiceTags": sdk.FieldSpec{WireName: "service_tags"},
		"SubscriptionIds": sdk.FieldSpec{WireName: "subscription_ids"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SecurityPerimeterAccessRule_TimeoutsFields,
		},
	},
}
