// Code generated by `ubx sdk gen` from azurerm_network_watcher_flow_log. DO NOT EDIT.
package network

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type WatcherFlowLog_RetentionPolicy struct {
	Days any
	Enabled any
}

type WatcherFlowLog_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type WatcherFlowLog_TrafficAnalytics struct {
	Enabled any
	IntervalInMinutes any
	WorkspaceId any
	WorkspaceRegion any
	WorkspaceResourceId any
}

var WatcherFlowLog_RetentionPolicyFields = sdk.FieldMap{
		"Days": sdk.FieldSpec{WireName: "days"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
	}

var WatcherFlowLog_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var WatcherFlowLog_TrafficAnalyticsFields = sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"IntervalInMinutes": sdk.FieldSpec{WireName: "interval_in_minutes"},
		"WorkspaceId": sdk.FieldSpec{WireName: "workspace_id"},
		"WorkspaceRegion": sdk.FieldSpec{WireName: "workspace_region"},
		"WorkspaceResourceId": sdk.FieldSpec{WireName: "workspace_resource_id"},
	}

type WatcherFlowLogConfig struct {
	Enabled any
	Id any
	Location any
	Name any
	NetworkWatcherName any
	ResourceGroupName any
	StorageAccountId any
	Tags any
	TargetResourceId any
	Version any
	RetentionPolicy any
	Timeouts any
	TrafficAnalytics any
}

var WatcherFlowLog = sdk.ResourceBinding{
	WireType: "azurerm_network_watcher_flow_log",
	Fields: sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkWatcherName": sdk.FieldSpec{WireName: "network_watcher_name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TargetResourceId": sdk.FieldSpec{WireName: "target_resource_id"},
		"Version": sdk.FieldSpec{WireName: "version"},
		"RetentionPolicy": sdk.FieldSpec{
			WireName: "retention_policy",
			Kind: "list",
			Fields: WatcherFlowLog_RetentionPolicyFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: WatcherFlowLog_TimeoutsFields,
		},
		"TrafficAnalytics": sdk.FieldSpec{
			WireName: "traffic_analytics",
			Kind: "list",
			Fields: WatcherFlowLog_TrafficAnalyticsFields,
		},
	},
}
