// Code generated by `ubx sdk gen` from azurerm_qumulo_file_system. DO NOT EDIT.
package qumulo

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FileSystem_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FileSystem_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FileSystemConfig struct {
	AdminPassword any
	Email any
	Id any
	Location any
	Name any
	OfferId any
	PlanId any
	PublisherId any
	ResourceGroupName any
	StorageSku any
	SubnetId any
	Tags any
	Zone any
	Timeouts any
}

var FileSystem = sdk.ResourceBinding{
	WireType: "azurerm_qumulo_file_system",
	Fields: sdk.FieldMap{
		"AdminPassword": sdk.FieldSpec{WireName: "admin_password"},
		"Email": sdk.FieldSpec{WireName: "email"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OfferId": sdk.FieldSpec{WireName: "offer_id"},
		"PlanId": sdk.FieldSpec{WireName: "plan_id"},
		"PublisherId": sdk.FieldSpec{WireName: "publisher_id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"StorageSku": sdk.FieldSpec{WireName: "storage_sku"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Zone": sdk.FieldSpec{WireName: "zone"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FileSystem_TimeoutsFields,
		},
	},
}
