// Code generated by `ubx sdk gen` from azurerm_synapse_private_link_hub. DO NOT EDIT.
package synapse

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type PrivateLinkHub_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var PrivateLinkHub_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type PrivateLinkHubConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	Timeouts any
}

var PrivateLinkHub = sdk.ResourceBinding{
	WireType: "azurerm_synapse_private_link_hub",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PrivateLinkHub_TimeoutsFields,
		},
	},
}
