// Code generated by `ubx sdk gen` from azurerm_synapse_spark_pool. DO NOT EDIT.
package synapse

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SparkPool_AutoPause struct {
	DelayInMinutes any
}

type SparkPool_AutoScale struct {
	MaxNodeCount any
	MinNodeCount any
}

type SparkPool_LibraryRequirement struct {
	Content any
	Filename any
}

type SparkPool_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var SparkPool_AutoPauseFields = sdk.FieldMap{
		"DelayInMinutes": sdk.FieldSpec{WireName: "delay_in_minutes"},
	}

var SparkPool_AutoScaleFields = sdk.FieldMap{
		"MaxNodeCount": sdk.FieldSpec{WireName: "max_node_count"},
		"MinNodeCount": sdk.FieldSpec{WireName: "min_node_count"},
	}

var SparkPool_LibraryRequirementFields = sdk.FieldMap{
		"Content": sdk.FieldSpec{WireName: "content"},
		"Filename": sdk.FieldSpec{WireName: "filename"},
	}

var SparkPool_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type SparkPoolConfig struct {
	CacheSize any
	ComputeIsolationEnabled any
	DynamicExecutorAllocationEnabled any
	Id any
	MaxExecutors any
	MinExecutors any
	Name any
	NodeCount any
	NodeSize any
	NodeSizeFamily any
	SessionLevelPackagesEnabled any
	SparkEventsFolder any
	SparkLogFolder any
	SparkVersion any
	SynapseWorkspaceId any
	Tags any
	AutoPause any
	AutoScale any
	LibraryRequirement any
	SparkConfig any
	Timeouts any
}

var SparkPool = sdk.ResourceBinding{
	WireType: "azurerm_synapse_spark_pool",
	Fields: sdk.FieldMap{
		"CacheSize": sdk.FieldSpec{WireName: "cache_size"},
		"ComputeIsolationEnabled": sdk.FieldSpec{WireName: "compute_isolation_enabled"},
		"DynamicExecutorAllocationEnabled": sdk.FieldSpec{WireName: "dynamic_executor_allocation_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"MaxExecutors": sdk.FieldSpec{WireName: "max_executors"},
		"MinExecutors": sdk.FieldSpec{WireName: "min_executors"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NodeCount": sdk.FieldSpec{WireName: "node_count"},
		"NodeSize": sdk.FieldSpec{WireName: "node_size"},
		"NodeSizeFamily": sdk.FieldSpec{WireName: "node_size_family"},
		"SessionLevelPackagesEnabled": sdk.FieldSpec{WireName: "session_level_packages_enabled"},
		"SparkEventsFolder": sdk.FieldSpec{WireName: "spark_events_folder"},
		"SparkLogFolder": sdk.FieldSpec{WireName: "spark_log_folder"},
		"SparkVersion": sdk.FieldSpec{WireName: "spark_version"},
		"SynapseWorkspaceId": sdk.FieldSpec{WireName: "synapse_workspace_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"AutoPause": sdk.FieldSpec{
			WireName: "auto_pause",
			Kind: "list",
			Fields: SparkPool_AutoPauseFields,
		},
		"AutoScale": sdk.FieldSpec{
			WireName: "auto_scale",
			Kind: "list",
			Fields: SparkPool_AutoScaleFields,
		},
		"LibraryRequirement": sdk.FieldSpec{
			WireName: "library_requirement",
			Kind: "list",
			Fields: SparkPool_LibraryRequirementFields,
		},
		"SparkConfig": sdk.FieldSpec{
			WireName: "spark_config",
			Kind: "list",
			Fields: SparkPool_LibraryRequirementFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SparkPool_TimeoutsFields,
		},
	},
}
