// Code generated by `ubx sdk gen` from azurerm_synapse_sql_pool_extended_auditing_policy. DO NOT EDIT.
package synapse

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SqlPoolExtendedAuditingPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var SqlPoolExtendedAuditingPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type SqlPoolExtendedAuditingPolicyConfig struct {
	Id any
	LogMonitoringEnabled any
	RetentionInDays any
	SqlPoolId any
	StorageAccountAccessKey any
	StorageAccountAccessKeyIsSecondary any
	StorageEndpoint any
	Timeouts any
}

var SqlPoolExtendedAuditingPolicy = sdk.ResourceBinding{
	WireType: "azurerm_synapse_sql_pool_extended_auditing_policy",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"LogMonitoringEnabled": sdk.FieldSpec{WireName: "log_monitoring_enabled"},
		"RetentionInDays": sdk.FieldSpec{WireName: "retention_in_days"},
		"SqlPoolId": sdk.FieldSpec{WireName: "sql_pool_id"},
		"StorageAccountAccessKey": sdk.FieldSpec{WireName: "storage_account_access_key"},
		"StorageAccountAccessKeyIsSecondary": sdk.FieldSpec{WireName: "storage_account_access_key_is_secondary"},
		"StorageEndpoint": sdk.FieldSpec{WireName: "storage_endpoint"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SqlPoolExtendedAuditingPolicy_TimeoutsFields,
		},
	},
}
