// Code generated by `ubx sdk gen` from azurerm_dev_test_virtual_network. DO NOT EDIT.
package dev

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type TestVirtualNetwork_Subnet_SharedPublicIpAddress_AllowedPorts struct {
	BackendPort any
	TransportProtocol any
}

type TestVirtualNetwork_Subnet_SharedPublicIpAddress struct {
	AllowedPorts any
}

type TestVirtualNetwork_Subnet struct {
	Name any
	UseInVirtualMachineCreation any
	UsePublicIpAddress any
	SharedPublicIpAddress any
}

type TestVirtualNetwork_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var TestVirtualNetwork_Subnet_SharedPublicIpAddress_AllowedPortsFields = sdk.FieldMap{
		"BackendPort": sdk.FieldSpec{WireName: "backend_port"},
		"TransportProtocol": sdk.FieldSpec{WireName: "transport_protocol"},
	}

var TestVirtualNetwork_Subnet_SharedPublicIpAddressFields = sdk.FieldMap{
		"AllowedPorts": sdk.FieldSpec{
			WireName: "allowed_ports",
			Kind: "list",
			Fields: TestVirtualNetwork_Subnet_SharedPublicIpAddress_AllowedPortsFields,
		},
	}

var TestVirtualNetwork_SubnetFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"UseInVirtualMachineCreation": sdk.FieldSpec{WireName: "use_in_virtual_machine_creation"},
		"UsePublicIpAddress": sdk.FieldSpec{WireName: "use_public_ip_address"},
		"SharedPublicIpAddress": sdk.FieldSpec{
			WireName: "shared_public_ip_address",
			Kind: "list",
			Fields: TestVirtualNetwork_Subnet_SharedPublicIpAddressFields,
		},
	}

var TestVirtualNetwork_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type TestVirtualNetworkConfig struct {
	Description any
	Id any
	LabName any
	Name any
	ResourceGroupName any
	Tags any
	Subnet any
	Timeouts any
}

var TestVirtualNetwork = sdk.ResourceBinding{
	WireType: "azurerm_dev_test_virtual_network",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LabName": sdk.FieldSpec{WireName: "lab_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Subnet": sdk.FieldSpec{
			WireName: "subnet",
			Kind: "list",
			Fields: TestVirtualNetwork_SubnetFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: TestVirtualNetwork_TimeoutsFields,
		},
	},
}
