// Code generated by `ubx sdk gen` from azurerm_attestation_provider. DO NOT EDIT.
package attestation

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Provider_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Provider_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ProviderConfig struct {
	Id any
	Location any
	Name any
	OpenEnclavePolicyBase64 any
	PolicySigningCertificateData any
	ResourceGroupName any
	SevSnpPolicyBase64 any
	SgxEnclavePolicyBase64 any
	Tags any
	TpmPolicyBase64 any
	Timeouts any
}

var Provider = sdk.ResourceBinding{
	WireType: "azurerm_attestation_provider",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OpenEnclavePolicyBase64": sdk.FieldSpec{WireName: "open_enclave_policy_base64"},
		"PolicySigningCertificateData": sdk.FieldSpec{WireName: "policy_signing_certificate_data"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SevSnpPolicyBase64": sdk.FieldSpec{WireName: "sev_snp_policy_base64"},
		"SgxEnclavePolicyBase64": sdk.FieldSpec{WireName: "sgx_enclave_policy_base64"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TpmPolicyBase64": sdk.FieldSpec{WireName: "tpm_policy_base64"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Provider_TimeoutsFields,
		},
	},
}
