// Code generated by `ubx sdk gen` from azurerm_healthcare_fhir_service. DO NOT EDIT.
package healthcare

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FhirService_Authentication struct {
	Audience any
	Authority any
	SmartProxyEnabled any
}

type FhirService_Cors struct {
	AllowedHeaders any
	AllowedMethods any
	AllowedOrigins any
	CredentialsAllowed any
	MaxAgeInSeconds any
}

type FhirService_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type FhirService_OciArtifact struct {
	Digest any
	ImageName any
	LoginServer any
}

type FhirService_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FhirService_AuthenticationFields = sdk.FieldMap{
		"Audience": sdk.FieldSpec{WireName: "audience"},
		"Authority": sdk.FieldSpec{WireName: "authority"},
		"SmartProxyEnabled": sdk.FieldSpec{WireName: "smart_proxy_enabled"},
	}

var FhirService_CorsFields = sdk.FieldMap{
		"AllowedHeaders": sdk.FieldSpec{WireName: "allowed_headers"},
		"AllowedMethods": sdk.FieldSpec{WireName: "allowed_methods"},
		"AllowedOrigins": sdk.FieldSpec{WireName: "allowed_origins"},
		"CredentialsAllowed": sdk.FieldSpec{WireName: "credentials_allowed"},
		"MaxAgeInSeconds": sdk.FieldSpec{WireName: "max_age_in_seconds"},
	}

var FhirService_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var FhirService_OciArtifactFields = sdk.FieldMap{
		"Digest": sdk.FieldSpec{WireName: "digest"},
		"ImageName": sdk.FieldSpec{WireName: "image_name"},
		"LoginServer": sdk.FieldSpec{WireName: "login_server"},
	}

var FhirService_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FhirServiceConfig struct {
	AccessPolicyObjectIds any
	ConfigurationExportStorageAccountName any
	ContainerRegistryLoginServerUrl any
	Id any
	Kind any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	WorkspaceId any
	Authentication any
	Cors any
	Identity any
	OciArtifact any
	Timeouts any
}

var FhirService = sdk.ResourceBinding{
	WireType: "azurerm_healthcare_fhir_service",
	Fields: sdk.FieldMap{
		"AccessPolicyObjectIds": sdk.FieldSpec{WireName: "access_policy_object_ids"},
		"ConfigurationExportStorageAccountName": sdk.FieldSpec{WireName: "configuration_export_storage_account_name"},
		"ContainerRegistryLoginServerUrl": sdk.FieldSpec{WireName: "container_registry_login_server_url"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Kind": sdk.FieldSpec{WireName: "kind"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"WorkspaceId": sdk.FieldSpec{WireName: "workspace_id"},
		"Authentication": sdk.FieldSpec{
			WireName: "authentication",
			Kind: "list",
			Fields: FhirService_AuthenticationFields,
		},
		"Cors": sdk.FieldSpec{
			WireName: "cors",
			Kind: "list",
			Fields: FhirService_CorsFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: FhirService_IdentityFields,
		},
		"OciArtifact": sdk.FieldSpec{
			WireName: "oci_artifact",
			Kind: "list",
			Fields: FhirService_OciArtifactFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FhirService_TimeoutsFields,
		},
	},
}
