// Code generated by `ubx sdk gen` from azurerm_managed_application_definition. DO NOT EDIT.
package managed

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ApplicationDefinition_Authorization struct {
	RoleDefinitionId any
	ServicePrincipalId any
}

type ApplicationDefinition_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ApplicationDefinition_AuthorizationFields = sdk.FieldMap{
		"RoleDefinitionId": sdk.FieldSpec{WireName: "role_definition_id"},
		"ServicePrincipalId": sdk.FieldSpec{WireName: "service_principal_id"},
	}

var ApplicationDefinition_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ApplicationDefinitionConfig struct {
	CreateUiDefinition any
	Description any
	DisplayName any
	Id any
	Location any
	LockLevel any
	MainTemplate any
	Name any
	PackageEnabled any
	PackageFileUri any
	ResourceGroupName any
	Tags any
	Authorization any
	Timeouts any
}

var ApplicationDefinition = sdk.ResourceBinding{
	WireType: "azurerm_managed_application_definition",
	Fields: sdk.FieldMap{
		"CreateUiDefinition": sdk.FieldSpec{WireName: "create_ui_definition"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"LockLevel": sdk.FieldSpec{WireName: "lock_level"},
		"MainTemplate": sdk.FieldSpec{WireName: "main_template"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PackageEnabled": sdk.FieldSpec{WireName: "package_enabled"},
		"PackageFileUri": sdk.FieldSpec{WireName: "package_file_uri"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Authorization": sdk.FieldSpec{
			WireName: "authorization",
			Kind: "set",
			Fields: ApplicationDefinition_AuthorizationFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ApplicationDefinition_TimeoutsFields,
		},
	},
}
