// Code generated by `ubx sdk gen` from azurerm_container_app_environment_custom_domain. DO NOT EDIT.
package container

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AppEnvironmentCustomDomain_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AppEnvironmentCustomDomain_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AppEnvironmentCustomDomainConfig struct {
	CertificateBlobBase64 any
	CertificatePassword any
	ContainerAppEnvironmentId any
	DnsSuffix any
	Id any
	Timeouts any
}

var AppEnvironmentCustomDomain = sdk.ResourceBinding{
	WireType: "azurerm_container_app_environment_custom_domain",
	Fields: sdk.FieldMap{
		"CertificateBlobBase64": sdk.FieldSpec{WireName: "certificate_blob_base64"},
		"CertificatePassword": sdk.FieldSpec{WireName: "certificate_password"},
		"ContainerAppEnvironmentId": sdk.FieldSpec{WireName: "container_app_environment_id"},
		"DnsSuffix": sdk.FieldSpec{WireName: "dns_suffix"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AppEnvironmentCustomDomain_TimeoutsFields,
		},
	},
}
