// Code generated by `ubx sdk gen` from azurerm_container_registry_token. DO NOT EDIT.
package container

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type RegistryToken_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var RegistryToken_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type RegistryTokenConfig struct {
	ContainerRegistryName any
	Enabled any
	Id any
	Name any
	ResourceGroupName any
	ScopeMapId any
	Timeouts any
}

var RegistryToken = sdk.ResourceBinding{
	WireType: "azurerm_container_registry_token",
	Fields: sdk.FieldMap{
		"ContainerRegistryName": sdk.FieldSpec{WireName: "container_registry_name"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ScopeMapId": sdk.FieldSpec{WireName: "scope_map_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: RegistryToken_TimeoutsFields,
		},
	},
}
