// Code generated by `ubx sdk gen` from azurerm_container_registry_task_schedule_run_now. DO NOT EDIT.
package container

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type RegistryTaskScheduleRunNow_Timeouts struct {
	Create any
	Delete any
	Read any
}

var RegistryTaskScheduleRunNow_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type RegistryTaskScheduleRunNowConfig struct {
	ContainerRegistryTaskId any
	Id any
	Timeouts any
}

var RegistryTaskScheduleRunNow = sdk.ResourceBinding{
	WireType: "azurerm_container_registry_task_schedule_run_now",
	Fields: sdk.FieldMap{
		"ContainerRegistryTaskId": sdk.FieldSpec{WireName: "container_registry_task_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: RegistryTaskScheduleRunNow_TimeoutsFields,
		},
	},
}
