// Code generated by `ubx sdk gen` from azurerm_container_registry_cache_rule. DO NOT EDIT.
package container

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type RegistryCacheRule_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var RegistryCacheRule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type RegistryCacheRuleConfig struct {
	ContainerRegistryId any
	CredentialSetId any
	Id any
	Name any
	SourceRepo any
	TargetRepo any
	Timeouts any
}

var RegistryCacheRule = sdk.ResourceBinding{
	WireType: "azurerm_container_registry_cache_rule",
	Fields: sdk.FieldMap{
		"ContainerRegistryId": sdk.FieldSpec{WireName: "container_registry_id"},
		"CredentialSetId": sdk.FieldSpec{WireName: "credential_set_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SourceRepo": sdk.FieldSpec{WireName: "source_repo"},
		"TargetRepo": sdk.FieldSpec{WireName: "target_repo"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: RegistryCacheRule_TimeoutsFields,
		},
	},
}
