// Code generated by `ubx sdk gen` from azurerm_storage_account. DO NOT EDIT.
package storage

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Account_AzureFilesAuthentication_ActiveDirectory struct {
	DomainGuid any
	DomainName any
	DomainSid any
	ForestName any
	NetbiosDomainName any
	StorageSid any
}

type Account_AzureFilesAuthentication struct {
	DefaultShareLevelPermission any
	DirectoryType any
	ActiveDirectory any
}

type Account_BlobProperties_ContainerDeleteRetentionPolicy struct {
	Days any
}

type Account_BlobProperties_CorsRule struct {
	AllowedHeaders any
	AllowedMethods any
	AllowedOrigins any
	ExposedHeaders any
	MaxAgeInSeconds any
}

type Account_BlobProperties_DeleteRetentionPolicy struct {
	Days any
	PermanentDeleteEnabled any
}

type Account_BlobProperties struct {
	ChangeFeedEnabled any
	ChangeFeedRetentionInDays any
	DefaultServiceVersion any
	LastAccessTimeEnabled any
	VersioningEnabled any
	ContainerDeleteRetentionPolicy any
	CorsRule any
	DeleteRetentionPolicy any
	RestorePolicy any
}

type Account_CustomDomain struct {
	Name any
	UseSubdomain any
}

type Account_CustomerManagedKey struct {
	KeyVaultKeyId any
	UserAssignedIdentityId any
}

type Account_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Account_ImmutabilityPolicy struct {
	AllowProtectedAppendWrites any
	PeriodSinceCreationInDays any
	State any
}

type Account_NetworkRules_PrivateLinkAccess struct {
	EndpointResourceId any
	EndpointTenantId any
}

type Account_NetworkRules struct {
	Bypass any
	DefaultAction any
	IpRules any
	VirtualNetworkSubnetIds any
	PrivateLinkAccess any
}

type Account_Routing struct {
	Choice any
	PublishInternetEndpoints any
	PublishMicrosoftEndpoints any
}

type Account_SasPolicy struct {
	ExpirationAction any
	ExpirationPeriod any
}

type Account_ShareProperties_Smb struct {
	AuthenticationTypes any
	ChannelEncryptionType any
	KerberosTicketEncryptionType any
	MultichannelEnabled any
	Versions any
}

type Account_ShareProperties struct {
	CorsRule any
	RetentionPolicy any
	Smb any
}

type Account_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Account_AzureFilesAuthentication_ActiveDirectoryFields = sdk.FieldMap{
		"DomainGuid": sdk.FieldSpec{WireName: "domain_guid"},
		"DomainName": sdk.FieldSpec{WireName: "domain_name"},
		"DomainSid": sdk.FieldSpec{WireName: "domain_sid"},
		"ForestName": sdk.FieldSpec{WireName: "forest_name"},
		"NetbiosDomainName": sdk.FieldSpec{WireName: "netbios_domain_name"},
		"StorageSid": sdk.FieldSpec{WireName: "storage_sid"},
	}

var Account_AzureFilesAuthenticationFields = sdk.FieldMap{
		"DefaultShareLevelPermission": sdk.FieldSpec{WireName: "default_share_level_permission"},
		"DirectoryType": sdk.FieldSpec{WireName: "directory_type"},
		"ActiveDirectory": sdk.FieldSpec{
			WireName: "active_directory",
			Kind: "list",
			Fields: Account_AzureFilesAuthentication_ActiveDirectoryFields,
		},
	}

var Account_BlobProperties_ContainerDeleteRetentionPolicyFields = sdk.FieldMap{
		"Days": sdk.FieldSpec{WireName: "days"},
	}

var Account_BlobProperties_CorsRuleFields = sdk.FieldMap{
		"AllowedHeaders": sdk.FieldSpec{WireName: "allowed_headers"},
		"AllowedMethods": sdk.FieldSpec{WireName: "allowed_methods"},
		"AllowedOrigins": sdk.FieldSpec{WireName: "allowed_origins"},
		"ExposedHeaders": sdk.FieldSpec{WireName: "exposed_headers"},
		"MaxAgeInSeconds": sdk.FieldSpec{WireName: "max_age_in_seconds"},
	}

var Account_BlobProperties_DeleteRetentionPolicyFields = sdk.FieldMap{
		"Days": sdk.FieldSpec{WireName: "days"},
		"PermanentDeleteEnabled": sdk.FieldSpec{WireName: "permanent_delete_enabled"},
	}

var Account_BlobPropertiesFields = sdk.FieldMap{
		"ChangeFeedEnabled": sdk.FieldSpec{WireName: "change_feed_enabled"},
		"ChangeFeedRetentionInDays": sdk.FieldSpec{WireName: "change_feed_retention_in_days"},
		"DefaultServiceVersion": sdk.FieldSpec{WireName: "default_service_version"},
		"LastAccessTimeEnabled": sdk.FieldSpec{WireName: "last_access_time_enabled"},
		"VersioningEnabled": sdk.FieldSpec{WireName: "versioning_enabled"},
		"ContainerDeleteRetentionPolicy": sdk.FieldSpec{
			WireName: "container_delete_retention_policy",
			Kind: "list",
			Fields: Account_BlobProperties_ContainerDeleteRetentionPolicyFields,
		},
		"CorsRule": sdk.FieldSpec{
			WireName: "cors_rule",
			Kind: "list",
			Fields: Account_BlobProperties_CorsRuleFields,
		},
		"DeleteRetentionPolicy": sdk.FieldSpec{
			WireName: "delete_retention_policy",
			Kind: "list",
			Fields: Account_BlobProperties_DeleteRetentionPolicyFields,
		},
		"RestorePolicy": sdk.FieldSpec{
			WireName: "restore_policy",
			Kind: "list",
			Fields: Account_BlobProperties_ContainerDeleteRetentionPolicyFields,
		},
	}

var Account_CustomDomainFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"UseSubdomain": sdk.FieldSpec{WireName: "use_subdomain"},
	}

var Account_CustomerManagedKeyFields = sdk.FieldMap{
		"KeyVaultKeyId": sdk.FieldSpec{WireName: "key_vault_key_id"},
		"UserAssignedIdentityId": sdk.FieldSpec{WireName: "user_assigned_identity_id"},
	}

var Account_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Account_ImmutabilityPolicyFields = sdk.FieldMap{
		"AllowProtectedAppendWrites": sdk.FieldSpec{WireName: "allow_protected_append_writes"},
		"PeriodSinceCreationInDays": sdk.FieldSpec{WireName: "period_since_creation_in_days"},
		"State": sdk.FieldSpec{WireName: "state"},
	}

var Account_NetworkRules_PrivateLinkAccessFields = sdk.FieldMap{
		"EndpointResourceId": sdk.FieldSpec{WireName: "endpoint_resource_id"},
		"EndpointTenantId": sdk.FieldSpec{WireName: "endpoint_tenant_id"},
	}

var Account_NetworkRulesFields = sdk.FieldMap{
		"Bypass": sdk.FieldSpec{WireName: "bypass"},
		"DefaultAction": sdk.FieldSpec{WireName: "default_action"},
		"IpRules": sdk.FieldSpec{WireName: "ip_rules"},
		"VirtualNetworkSubnetIds": sdk.FieldSpec{WireName: "virtual_network_subnet_ids"},
		"PrivateLinkAccess": sdk.FieldSpec{
			WireName: "private_link_access",
			Kind: "list",
			Fields: Account_NetworkRules_PrivateLinkAccessFields,
		},
	}

var Account_RoutingFields = sdk.FieldMap{
		"Choice": sdk.FieldSpec{WireName: "choice"},
		"PublishInternetEndpoints": sdk.FieldSpec{WireName: "publish_internet_endpoints"},
		"PublishMicrosoftEndpoints": sdk.FieldSpec{WireName: "publish_microsoft_endpoints"},
	}

var Account_SasPolicyFields = sdk.FieldMap{
		"ExpirationAction": sdk.FieldSpec{WireName: "expiration_action"},
		"ExpirationPeriod": sdk.FieldSpec{WireName: "expiration_period"},
	}

var Account_ShareProperties_SmbFields = sdk.FieldMap{
		"AuthenticationTypes": sdk.FieldSpec{WireName: "authentication_types"},
		"ChannelEncryptionType": sdk.FieldSpec{WireName: "channel_encryption_type"},
		"KerberosTicketEncryptionType": sdk.FieldSpec{WireName: "kerberos_ticket_encryption_type"},
		"MultichannelEnabled": sdk.FieldSpec{WireName: "multichannel_enabled"},
		"Versions": sdk.FieldSpec{WireName: "versions"},
	}

var Account_SharePropertiesFields = sdk.FieldMap{
		"CorsRule": sdk.FieldSpec{
			WireName: "cors_rule",
			Kind: "list",
			Fields: Account_BlobProperties_CorsRuleFields,
		},
		"RetentionPolicy": sdk.FieldSpec{
			WireName: "retention_policy",
			Kind: "list",
			Fields: Account_BlobProperties_ContainerDeleteRetentionPolicyFields,
		},
		"Smb": sdk.FieldSpec{
			WireName: "smb",
			Kind: "list",
			Fields: Account_ShareProperties_SmbFields,
		},
	}

var Account_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AccountConfig struct {
	AccessTier any
	AccountKind any
	AccountReplicationType any
	AccountTier any
	AllowNestedItemsToBePublic any
	AllowedCopyScope any
	CrossTenantReplicationEnabled any
	DefaultToOauthAuthentication any
	DnsEndpointType any
	EdgeZone any
	HttpsTrafficOnlyEnabled any
	Id any
	InfrastructureEncryptionEnabled any
	IsHnsEnabled any
	LargeFileShareEnabled any
	LocalUserEnabled any
	Location any
	MinTlsVersion any
	Name any
	Nfsv3Enabled any
	ProvisionedBillingModelVersion any
	PublicNetworkAccessEnabled any
	QueueEncryptionKeyType any
	ResourceGroupName any
	SftpEnabled any
	SharedAccessKeyEnabled any
	TableEncryptionKeyType any
	Tags any
	AzureFilesAuthentication any
	BlobProperties any
	CustomDomain any
	CustomerManagedKey any
	Identity any
	ImmutabilityPolicy any
	NetworkRules any
	Routing any
	SasPolicy any
	ShareProperties any
	Timeouts any
}

var Account = sdk.ResourceBinding{
	WireType: "azurerm_storage_account",
	Fields: sdk.FieldMap{
		"AccessTier": sdk.FieldSpec{WireName: "access_tier"},
		"AccountKind": sdk.FieldSpec{WireName: "account_kind"},
		"AccountReplicationType": sdk.FieldSpec{WireName: "account_replication_type"},
		"AccountTier": sdk.FieldSpec{WireName: "account_tier"},
		"AllowNestedItemsToBePublic": sdk.FieldSpec{WireName: "allow_nested_items_to_be_public"},
		"AllowedCopyScope": sdk.FieldSpec{WireName: "allowed_copy_scope"},
		"CrossTenantReplicationEnabled": sdk.FieldSpec{WireName: "cross_tenant_replication_enabled"},
		"DefaultToOauthAuthentication": sdk.FieldSpec{WireName: "default_to_oauth_authentication"},
		"DnsEndpointType": sdk.FieldSpec{WireName: "dns_endpoint_type"},
		"EdgeZone": sdk.FieldSpec{WireName: "edge_zone"},
		"HttpsTrafficOnlyEnabled": sdk.FieldSpec{WireName: "https_traffic_only_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"InfrastructureEncryptionEnabled": sdk.FieldSpec{WireName: "infrastructure_encryption_enabled"},
		"IsHnsEnabled": sdk.FieldSpec{WireName: "is_hns_enabled"},
		"LargeFileShareEnabled": sdk.FieldSpec{WireName: "large_file_share_enabled"},
		"LocalUserEnabled": sdk.FieldSpec{WireName: "local_user_enabled"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MinTlsVersion": sdk.FieldSpec{WireName: "min_tls_version"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Nfsv3Enabled": sdk.FieldSpec{WireName: "nfsv3_enabled"},
		"ProvisionedBillingModelVersion": sdk.FieldSpec{WireName: "provisioned_billing_model_version"},
		"PublicNetworkAccessEnabled": sdk.FieldSpec{WireName: "public_network_access_enabled"},
		"QueueEncryptionKeyType": sdk.FieldSpec{WireName: "queue_encryption_key_type"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SftpEnabled": sdk.FieldSpec{WireName: "sftp_enabled"},
		"SharedAccessKeyEnabled": sdk.FieldSpec{WireName: "shared_access_key_enabled"},
		"TableEncryptionKeyType": sdk.FieldSpec{WireName: "table_encryption_key_type"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"AzureFilesAuthentication": sdk.FieldSpec{
			WireName: "azure_files_authentication",
			Kind: "list",
			Fields: Account_AzureFilesAuthenticationFields,
		},
		"BlobProperties": sdk.FieldSpec{
			WireName: "blob_properties",
			Kind: "list",
			Fields: Account_BlobPropertiesFields,
		},
		"CustomDomain": sdk.FieldSpec{
			WireName: "custom_domain",
			Kind: "list",
			Fields: Account_CustomDomainFields,
		},
		"CustomerManagedKey": sdk.FieldSpec{
			WireName: "customer_managed_key",
			Kind: "list",
			Fields: Account_CustomerManagedKeyFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Account_IdentityFields,
		},
		"ImmutabilityPolicy": sdk.FieldSpec{
			WireName: "immutability_policy",
			Kind: "list",
			Fields: Account_ImmutabilityPolicyFields,
		},
		"NetworkRules": sdk.FieldSpec{
			WireName: "network_rules",
			Kind: "list",
			Fields: Account_NetworkRulesFields,
		},
		"Routing": sdk.FieldSpec{
			WireName: "routing",
			Kind: "list",
			Fields: Account_RoutingFields,
		},
		"SasPolicy": sdk.FieldSpec{
			WireName: "sas_policy",
			Kind: "list",
			Fields: Account_SasPolicyFields,
		},
		"ShareProperties": sdk.FieldSpec{
			WireName: "share_properties",
			Kind: "list",
			Fields: Account_SharePropertiesFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Account_TimeoutsFields,
		},
	},
}
