// Code generated by `ubx sdk gen` from azurerm_storage_data_lake_gen2_path. DO NOT EDIT.
package storage

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DataLakeGen2Path_Ace struct {
	Id any
	Permissions any
	Scope any
	Type any
}

type DataLakeGen2Path_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DataLakeGen2Path_AceFields = sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Permissions": sdk.FieldSpec{WireName: "permissions"},
		"Scope": sdk.FieldSpec{WireName: "scope"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var DataLakeGen2Path_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DataLakeGen2PathConfig struct {
	FilesystemName any
	Group any
	Id any
	Owner any
	Path any
	Resource any
	StorageAccountId any
	Ace any
	Timeouts any
}

var DataLakeGen2Path = sdk.ResourceBinding{
	WireType: "azurerm_storage_data_lake_gen2_path",
	Fields: sdk.FieldMap{
		"FilesystemName": sdk.FieldSpec{WireName: "filesystem_name"},
		"Group": sdk.FieldSpec{WireName: "group"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Owner": sdk.FieldSpec{WireName: "owner"},
		"Path": sdk.FieldSpec{WireName: "path"},
		"Resource": sdk.FieldSpec{WireName: "resource"},
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
		"Ace": sdk.FieldSpec{
			WireName: "ace",
			Kind: "set",
			Fields: DataLakeGen2Path_AceFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DataLakeGen2Path_TimeoutsFields,
		},
	},
}
