// Code generated by `ubx sdk gen` from azurerm_storage_mover_job_definition. DO NOT EDIT.
package storage

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type MoverJobDefinition_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var MoverJobDefinition_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type MoverJobDefinitionConfig struct {
	AgentName any
	CopyMode any
	Description any
	Id any
	Name any
	SourceName any
	SourceSubPath any
	StorageMoverProjectId any
	TargetName any
	TargetSubPath any
	Timeouts any
}

var MoverJobDefinition = sdk.ResourceBinding{
	WireType: "azurerm_storage_mover_job_definition",
	Fields: sdk.FieldMap{
		"AgentName": sdk.FieldSpec{WireName: "agent_name"},
		"CopyMode": sdk.FieldSpec{WireName: "copy_mode"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SourceName": sdk.FieldSpec{WireName: "source_name"},
		"SourceSubPath": sdk.FieldSpec{WireName: "source_sub_path"},
		"StorageMoverProjectId": sdk.FieldSpec{WireName: "storage_mover_project_id"},
		"TargetName": sdk.FieldSpec{WireName: "target_name"},
		"TargetSubPath": sdk.FieldSpec{WireName: "target_sub_path"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: MoverJobDefinition_TimeoutsFields,
		},
	},
}
