// Code generated by `ubx sdk gen` from azurerm_storage_sync_server_endpoint. DO NOT EDIT.
package storage

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SyncServerEndpoint_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var SyncServerEndpoint_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type SyncServerEndpointConfig struct {
	CloudTieringEnabled any
	Id any
	InitialDownloadPolicy any
	LocalCacheMode any
	Name any
	RegisteredServerId any
	ServerLocalPath any
	StorageSyncGroupId any
	TierFilesOlderThanDays any
	VolumeFreeSpacePercent any
	Timeouts any
}

var SyncServerEndpoint = sdk.ResourceBinding{
	WireType: "azurerm_storage_sync_server_endpoint",
	Fields: sdk.FieldMap{
		"CloudTieringEnabled": sdk.FieldSpec{WireName: "cloud_tiering_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"InitialDownloadPolicy": sdk.FieldSpec{WireName: "initial_download_policy"},
		"LocalCacheMode": sdk.FieldSpec{WireName: "local_cache_mode"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RegisteredServerId": sdk.FieldSpec{WireName: "registered_server_id"},
		"ServerLocalPath": sdk.FieldSpec{WireName: "server_local_path"},
		"StorageSyncGroupId": sdk.FieldSpec{WireName: "storage_sync_group_id"},
		"TierFilesOlderThanDays": sdk.FieldSpec{WireName: "tier_files_older_than_days"},
		"VolumeFreeSpacePercent": sdk.FieldSpec{WireName: "volume_free_space_percent"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SyncServerEndpoint_TimeoutsFields,
		},
	},
}
