// Code generated by `ubx sdk gen` from azurerm_storage_sync_cloud_endpoint. DO NOT EDIT.
package storage

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SyncCloudEndpoint_Timeouts struct {
	Create any
	Delete any
	Read any
}

var SyncCloudEndpoint_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type SyncCloudEndpointConfig struct {
	FileShareName any
	Id any
	Name any
	StorageAccountId any
	StorageAccountTenantId any
	StorageSyncGroupId any
	Timeouts any
}

var SyncCloudEndpoint = sdk.ResourceBinding{
	WireType: "azurerm_storage_sync_cloud_endpoint",
	Fields: sdk.FieldMap{
		"FileShareName": sdk.FieldSpec{WireName: "file_share_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
		"StorageAccountTenantId": sdk.FieldSpec{WireName: "storage_account_tenant_id"},
		"StorageSyncGroupId": sdk.FieldSpec{WireName: "storage_sync_group_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SyncCloudEndpoint_TimeoutsFields,
		},
	},
}
