// Code generated by `ubx sdk gen` from azurerm_private_dns_resolver_outbound_endpoint. DO NOT EDIT.
package private

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DnsResolverOutboundEndpoint_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DnsResolverOutboundEndpoint_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DnsResolverOutboundEndpointConfig struct {
	Id any
	Location any
	Name any
	PrivateDnsResolverId any
	SubnetId any
	Tags any
	Timeouts any
}

var DnsResolverOutboundEndpoint = sdk.ResourceBinding{
	WireType: "azurerm_private_dns_resolver_outbound_endpoint",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateDnsResolverId": sdk.FieldSpec{WireName: "private_dns_resolver_id"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DnsResolverOutboundEndpoint_TimeoutsFields,
		},
	},
}
