// Code generated by `ubx sdk gen` from azurerm_private_dns_aaaa_record. DO NOT EDIT.
package private

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DnsAaaaRecord_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DnsAaaaRecord_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DnsAaaaRecordConfig struct {
	Id any
	Name any
	PrivateDnsZoneId any
	Records any
	Tags any
	Ttl any
	Timeouts any
}

var DnsAaaaRecord = sdk.ResourceBinding{
	WireType: "azurerm_private_dns_aaaa_record",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateDnsZoneId": sdk.FieldSpec{WireName: "private_dns_zone_id"},
		"Records": sdk.FieldSpec{WireName: "records"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Ttl": sdk.FieldSpec{WireName: "ttl"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DnsAaaaRecord_TimeoutsFields,
		},
	},
}
