// Code generated by `ubx sdk gen` from azurerm_private_link_service. DO NOT EDIT.
package private

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type LinkService_NatIpConfiguration struct {
	Name any
	Primary any
	PrivateIpAddress any
	PrivateIpAddressVersion any
	SubnetId any
}

type LinkService_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var LinkService_NatIpConfigurationFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Primary": sdk.FieldSpec{WireName: "primary"},
		"PrivateIpAddress": sdk.FieldSpec{WireName: "private_ip_address"},
		"PrivateIpAddressVersion": sdk.FieldSpec{WireName: "private_ip_address_version"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
	}

var LinkService_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type LinkServiceConfig struct {
	AutoApprovalSubscriptionIds any
	DestinationIpAddress any
	Fqdns any
	Id any
	LoadBalancerFrontendIpConfigurationIds any
	Location any
	Name any
	ProxyProtocolEnabled any
	ResourceGroupName any
	Tags any
	VisibilitySubscriptionIds any
	NatIpConfiguration any
	Timeouts any
}

var LinkService = sdk.ResourceBinding{
	WireType: "azurerm_private_link_service",
	Fields: sdk.FieldMap{
		"AutoApprovalSubscriptionIds": sdk.FieldSpec{WireName: "auto_approval_subscription_ids"},
		"DestinationIpAddress": sdk.FieldSpec{WireName: "destination_ip_address"},
		"Fqdns": sdk.FieldSpec{WireName: "fqdns"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LoadBalancerFrontendIpConfigurationIds": sdk.FieldSpec{WireName: "load_balancer_frontend_ip_configuration_ids"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ProxyProtocolEnabled": sdk.FieldSpec{WireName: "proxy_protocol_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"VisibilitySubscriptionIds": sdk.FieldSpec{WireName: "visibility_subscription_ids"},
		"NatIpConfiguration": sdk.FieldSpec{
			WireName: "nat_ip_configuration",
			Kind: "list",
			Fields: LinkService_NatIpConfigurationFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: LinkService_TimeoutsFields,
		},
	},
}
