// Code generated by `ubx sdk gen` from azurerm_app_configuration_key. DO NOT EDIT.
package app

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ConfigurationKey_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ConfigurationKey_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ConfigurationKeyConfig struct {
	ConfigurationStoreId any
	ContentType any
	Etag any
	Id any
	Key any
	Label any
	Locked any
	Tags any
	Type any
	Value any
	VaultKeyReference any
	Timeouts any
}

var ConfigurationKey = sdk.ResourceBinding{
	WireType: "azurerm_app_configuration_key",
	Fields: sdk.FieldMap{
		"ConfigurationStoreId": sdk.FieldSpec{WireName: "configuration_store_id"},
		"ContentType": sdk.FieldSpec{WireName: "content_type"},
		"Etag": sdk.FieldSpec{WireName: "etag"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Key": sdk.FieldSpec{WireName: "key"},
		"Label": sdk.FieldSpec{WireName: "label"},
		"Locked": sdk.FieldSpec{WireName: "locked"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Value": sdk.FieldSpec{WireName: "value"},
		"VaultKeyReference": sdk.FieldSpec{WireName: "vault_key_reference"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ConfigurationKey_TimeoutsFields,
		},
	},
}
