// Code generated by `ubx sdk gen` from azurerm_app_service_environment_v3. DO NOT EDIT.
package app

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ServiceEnvironmentV3_ClusterSetting struct {
	Name any
	Value any
}

type ServiceEnvironmentV3_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ServiceEnvironmentV3_ClusterSettingFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var ServiceEnvironmentV3_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ServiceEnvironmentV3Config struct {
	AllowNewPrivateEndpointConnections any
	DedicatedHostCount any
	Id any
	InternalLoadBalancingMode any
	Name any
	RemoteDebuggingEnabled any
	ResourceGroupName any
	SubnetId any
	Tags any
	ZoneRedundant any
	ClusterSetting any
	Timeouts any
}

var ServiceEnvironmentV3 = sdk.ResourceBinding{
	WireType: "azurerm_app_service_environment_v3",
	Fields: sdk.FieldMap{
		"AllowNewPrivateEndpointConnections": sdk.FieldSpec{WireName: "allow_new_private_endpoint_connections"},
		"DedicatedHostCount": sdk.FieldSpec{WireName: "dedicated_host_count"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"InternalLoadBalancingMode": sdk.FieldSpec{WireName: "internal_load_balancing_mode"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RemoteDebuggingEnabled": sdk.FieldSpec{WireName: "remote_debugging_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"ZoneRedundant": sdk.FieldSpec{WireName: "zone_redundant"},
		"ClusterSetting": sdk.FieldSpec{
			WireName: "cluster_setting",
			Kind: "list",
			Fields: ServiceEnvironmentV3_ClusterSettingFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ServiceEnvironmentV3_TimeoutsFields,
		},
	},
}
