// Code generated by `ubx sdk gen` from azurerm_app_service_certificate_order. DO NOT EDIT.
package app

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ServiceCertificateOrder_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ServiceCertificateOrder_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ServiceCertificateOrderConfig struct {
	AutoRenew any
	Csr any
	DistinguishedName any
	Id any
	KeySize any
	Location any
	Name any
	ProductType any
	ResourceGroupName any
	Tags any
	ValidityInYears any
	Timeouts any
}

var ServiceCertificateOrder = sdk.ResourceBinding{
	WireType: "azurerm_app_service_certificate_order",
	Fields: sdk.FieldMap{
		"AutoRenew": sdk.FieldSpec{WireName: "auto_renew"},
		"Csr": sdk.FieldSpec{WireName: "csr"},
		"DistinguishedName": sdk.FieldSpec{WireName: "distinguished_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"KeySize": sdk.FieldSpec{WireName: "key_size"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ProductType": sdk.FieldSpec{WireName: "product_type"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"ValidityInYears": sdk.FieldSpec{WireName: "validity_in_years"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ServiceCertificateOrder_TimeoutsFields,
		},
	},
}
