// Code generated by `ubx sdk gen` from azurerm_consumption_budget_resource_group. DO NOT EDIT.
package consumption

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type BudgetResourceGroup_Filter_Dimension struct {
	Name any
	Operator any
	Values any
}

type BudgetResourceGroup_Filter struct {
	Dimension any
	Tag any
}

type BudgetResourceGroup_Notification struct {
	ContactEmails any
	ContactGroups any
	ContactRoles any
	Enabled any
	Operator any
	Threshold any
	ThresholdType any
}

type BudgetResourceGroup_TimePeriod struct {
	EndDate any
	StartDate any
}

type BudgetResourceGroup_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var BudgetResourceGroup_Filter_DimensionFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Values": sdk.FieldSpec{WireName: "values"},
	}

var BudgetResourceGroup_FilterFields = sdk.FieldMap{
		"Dimension": sdk.FieldSpec{
			WireName: "dimension",
			Kind: "set",
			Fields: BudgetResourceGroup_Filter_DimensionFields,
		},
		"Tag": sdk.FieldSpec{
			WireName: "tag",
			Kind: "set",
			Fields: BudgetResourceGroup_Filter_DimensionFields,
		},
	}

var BudgetResourceGroup_NotificationFields = sdk.FieldMap{
		"ContactEmails": sdk.FieldSpec{WireName: "contact_emails"},
		"ContactGroups": sdk.FieldSpec{WireName: "contact_groups"},
		"ContactRoles": sdk.FieldSpec{WireName: "contact_roles"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Threshold": sdk.FieldSpec{WireName: "threshold"},
		"ThresholdType": sdk.FieldSpec{WireName: "threshold_type"},
	}

var BudgetResourceGroup_TimePeriodFields = sdk.FieldMap{
		"EndDate": sdk.FieldSpec{WireName: "end_date"},
		"StartDate": sdk.FieldSpec{WireName: "start_date"},
	}

var BudgetResourceGroup_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type BudgetResourceGroupConfig struct {
	Amount any
	Etag any
	Id any
	Name any
	ResourceGroupId any
	TimeGrain any
	Filter any
	Notification any
	TimePeriod any
	Timeouts any
}

var BudgetResourceGroup = sdk.ResourceBinding{
	WireType: "azurerm_consumption_budget_resource_group",
	Fields: sdk.FieldMap{
		"Amount": sdk.FieldSpec{WireName: "amount"},
		"Etag": sdk.FieldSpec{WireName: "etag"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupId": sdk.FieldSpec{WireName: "resource_group_id"},
		"TimeGrain": sdk.FieldSpec{WireName: "time_grain"},
		"Filter": sdk.FieldSpec{
			WireName: "filter",
			Kind: "list",
			Fields: BudgetResourceGroup_FilterFields,
		},
		"Notification": sdk.FieldSpec{
			WireName: "notification",
			Kind: "set",
			Fields: BudgetResourceGroup_NotificationFields,
		},
		"TimePeriod": sdk.FieldSpec{
			WireName: "time_period",
			Kind: "list",
			Fields: BudgetResourceGroup_TimePeriodFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: BudgetResourceGroup_TimeoutsFields,
		},
	},
}
