// Code generated by `ubx sdk gen` from azurerm_function_app_active_slot. DO NOT EDIT.
package function

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AppActiveSlot_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AppActiveSlot_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AppActiveSlotConfig struct {
	Id any
	OverwriteNetworkConfig any
	SlotId any
	Timeouts any
}

var AppActiveSlot = sdk.ResourceBinding{
	WireType: "azurerm_function_app_active_slot",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"OverwriteNetworkConfig": sdk.FieldSpec{WireName: "overwrite_network_config"},
		"SlotId": sdk.FieldSpec{WireName: "slot_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AppActiveSlot_TimeoutsFields,
		},
	},
}
