// Code generated by `ubx sdk gen` from azurerm_traffic_manager_nested_endpoint. DO NOT EDIT.
package traffic

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerNestedEndpoint_CustomHeader struct {
	Name any
	Value any
}

type ManagerNestedEndpoint_Subnet struct {
	First any
	Last any
	Scope any
}

type ManagerNestedEndpoint_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagerNestedEndpoint_CustomHeaderFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var ManagerNestedEndpoint_SubnetFields = sdk.FieldMap{
		"First": sdk.FieldSpec{WireName: "first"},
		"Last": sdk.FieldSpec{WireName: "last"},
		"Scope": sdk.FieldSpec{WireName: "scope"},
	}

var ManagerNestedEndpoint_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagerNestedEndpointConfig struct {
	Enabled any
	EndpointLocation any
	GeoMappings any
	Id any
	MinimumChildEndpoints any
	MinimumRequiredChildEndpointsIpv4 any
	MinimumRequiredChildEndpointsIpv6 any
	Name any
	Priority any
	ProfileId any
	TargetResourceId any
	Weight any
	CustomHeader any
	Subnet any
	Timeouts any
}

var ManagerNestedEndpoint = sdk.ResourceBinding{
	WireType: "azurerm_traffic_manager_nested_endpoint",
	Fields: sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"EndpointLocation": sdk.FieldSpec{WireName: "endpoint_location"},
		"GeoMappings": sdk.FieldSpec{WireName: "geo_mappings"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"MinimumChildEndpoints": sdk.FieldSpec{WireName: "minimum_child_endpoints"},
		"MinimumRequiredChildEndpointsIpv4": sdk.FieldSpec{WireName: "minimum_required_child_endpoints_ipv4"},
		"MinimumRequiredChildEndpointsIpv6": sdk.FieldSpec{WireName: "minimum_required_child_endpoints_ipv6"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"ProfileId": sdk.FieldSpec{WireName: "profile_id"},
		"TargetResourceId": sdk.FieldSpec{WireName: "target_resource_id"},
		"Weight": sdk.FieldSpec{WireName: "weight"},
		"CustomHeader": sdk.FieldSpec{
			WireName: "custom_header",
			Kind: "list",
			Fields: ManagerNestedEndpoint_CustomHeaderFields,
		},
		"Subnet": sdk.FieldSpec{
			WireName: "subnet",
			Kind: "list",
			Fields: ManagerNestedEndpoint_SubnetFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagerNestedEndpoint_TimeoutsFields,
		},
	},
}
