// Code generated by `ubx sdk gen` from azurerm_machine_learning_compute_instance. DO NOT EDIT.
package machine

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type LearningComputeInstance_AssignToUser struct {
	ObjectId any
	TenantId any
}

type LearningComputeInstance_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type LearningComputeInstance_Ssh struct {
	Port any
	PublicKey any
	Username any
}

type LearningComputeInstance_Timeouts struct {
	Create any
	Delete any
	Read any
}

var LearningComputeInstance_AssignToUserFields = sdk.FieldMap{
		"ObjectId": sdk.FieldSpec{WireName: "object_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
	}

var LearningComputeInstance_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var LearningComputeInstance_SshFields = sdk.FieldMap{
		"Port": sdk.FieldSpec{WireName: "port"},
		"PublicKey": sdk.FieldSpec{WireName: "public_key"},
		"Username": sdk.FieldSpec{WireName: "username"},
	}

var LearningComputeInstance_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type LearningComputeInstanceConfig struct {
	AuthorizationType any
	Description any
	Id any
	LocalAuthEnabled any
	MachineLearningWorkspaceId any
	Name any
	NodePublicIpEnabled any
	SubnetResourceId any
	Tags any
	VirtualMachineSize any
	AssignToUser any
	Identity any
	Ssh any
	Timeouts any
}

var LearningComputeInstance = sdk.ResourceBinding{
	WireType: "azurerm_machine_learning_compute_instance",
	Fields: sdk.FieldMap{
		"AuthorizationType": sdk.FieldSpec{WireName: "authorization_type"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LocalAuthEnabled": sdk.FieldSpec{WireName: "local_auth_enabled"},
		"MachineLearningWorkspaceId": sdk.FieldSpec{WireName: "machine_learning_workspace_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NodePublicIpEnabled": sdk.FieldSpec{WireName: "node_public_ip_enabled"},
		"SubnetResourceId": sdk.FieldSpec{WireName: "subnet_resource_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"VirtualMachineSize": sdk.FieldSpec{WireName: "virtual_machine_size"},
		"AssignToUser": sdk.FieldSpec{
			WireName: "assign_to_user",
			Kind: "list",
			Fields: LearningComputeInstance_AssignToUserFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: LearningComputeInstance_IdentityFields,
		},
		"Ssh": sdk.FieldSpec{
			WireName: "ssh",
			Kind: "list",
			Fields: LearningComputeInstance_SshFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: LearningComputeInstance_TimeoutsFields,
		},
	},
}
