// Code generated by `ubx sdk gen` from azurerm_system_center_virtual_machine_manager_server. DO NOT EDIT.
package system

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CenterVirtualMachineManagerServer_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CenterVirtualMachineManagerServer_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CenterVirtualMachineManagerServerConfig struct {
	CustomLocationId any
	Fqdn any
	Id any
	Location any
	Name any
	Password any
	Port any
	ResourceGroupName any
	Tags any
	Username any
	Timeouts any
}

var CenterVirtualMachineManagerServer = sdk.ResourceBinding{
	WireType: "azurerm_system_center_virtual_machine_manager_server",
	Fields: sdk.FieldMap{
		"CustomLocationId": sdk.FieldSpec{WireName: "custom_location_id"},
		"Fqdn": sdk.FieldSpec{WireName: "fqdn"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Password": sdk.FieldSpec{WireName: "password"},
		"Port": sdk.FieldSpec{WireName: "port"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Username": sdk.FieldSpec{WireName: "username"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CenterVirtualMachineManagerServer_TimeoutsFields,
		},
	},
}
