// Code generated by `ubx sdk gen` from azurerm_system_center_virtual_machine_manager_cloud. DO NOT EDIT.
package system

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CenterVirtualMachineManagerCloud_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CenterVirtualMachineManagerCloud_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CenterVirtualMachineManagerCloudConfig struct {
	CustomLocationId any
	Id any
	Location any
	Name any
	ResourceGroupName any
	SystemCenterVirtualMachineManagerServerInventoryItemId any
	Tags any
	Timeouts any
}

var CenterVirtualMachineManagerCloud = sdk.ResourceBinding{
	WireType: "azurerm_system_center_virtual_machine_manager_cloud",
	Fields: sdk.FieldMap{
		"CustomLocationId": sdk.FieldSpec{WireName: "custom_location_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SystemCenterVirtualMachineManagerServerInventoryItemId": sdk.FieldSpec{WireName: "system_center_virtual_machine_manager_server_inventory_item_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CenterVirtualMachineManagerCloud_TimeoutsFields,
		},
	},
}
