// Code generated by `ubx sdk gen` from azurerm_lb. DO NOT EDIT.
package lb

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Lb_FrontendIpConfiguration struct {
	GatewayLoadBalancerFrontendIpConfigurationId any
	Id any
	InboundNatRules any
	LoadBalancerRules any
	Name any
	OutboundRules any
	PrivateIpAddress any
	PrivateIpAddressAllocation any
	PrivateIpAddressVersion any
	PublicIpAddressId any
	PublicIpPrefixId any
	SubnetId any
	Zones any
}

type Lb_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Lb_FrontendIpConfigurationFields = sdk.FieldMap{
		"GatewayLoadBalancerFrontendIpConfigurationId": sdk.FieldSpec{WireName: "gateway_load_balancer_frontend_ip_configuration_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"InboundNatRules": sdk.FieldSpec{WireName: "inbound_nat_rules"},
		"LoadBalancerRules": sdk.FieldSpec{WireName: "load_balancer_rules"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OutboundRules": sdk.FieldSpec{WireName: "outbound_rules"},
		"PrivateIpAddress": sdk.FieldSpec{WireName: "private_ip_address"},
		"PrivateIpAddressAllocation": sdk.FieldSpec{WireName: "private_ip_address_allocation"},
		"PrivateIpAddressVersion": sdk.FieldSpec{WireName: "private_ip_address_version"},
		"PublicIpAddressId": sdk.FieldSpec{WireName: "public_ip_address_id"},
		"PublicIpPrefixId": sdk.FieldSpec{WireName: "public_ip_prefix_id"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
		"Zones": sdk.FieldSpec{WireName: "zones"},
	}

var Lb_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type LbConfig struct {
	EdgeZone any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Sku any
	SkuTier any
	Tags any
	FrontendIpConfiguration any
	Timeouts any
}

var Lb = sdk.ResourceBinding{
	WireType: "azurerm_lb",
	Fields: sdk.FieldMap{
		"EdgeZone": sdk.FieldSpec{WireName: "edge_zone"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"SkuTier": sdk.FieldSpec{WireName: "sku_tier"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"FrontendIpConfiguration": sdk.FieldSpec{
			WireName: "frontend_ip_configuration",
			Kind: "list",
			Fields: Lb_FrontendIpConfigurationFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Lb_TimeoutsFields,
		},
	},
}
