// Code generated by `ubx sdk gen` from azurerm_source_control_token. DO NOT EDIT.
package source

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ControlToken_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ControlToken_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ControlTokenConfig struct {
	Id any
	Token any
	TokenSecret any
	Type any
	Timeouts any
}

var ControlToken = sdk.ResourceBinding{
	WireType: "azurerm_source_control_token",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Token": sdk.FieldSpec{WireName: "token"},
		"TokenSecret": sdk.FieldSpec{WireName: "token_secret"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ControlToken_TimeoutsFields,
		},
	},
}
