// Code generated by `ubx sdk gen` from azurerm_eventgrid_partner_configuration. DO NOT EDIT.
package eventgrid

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type PartnerConfiguration_PartnerAuthorization struct {
	AuthorizationExpirationTimeInUtc any
	PartnerName any
	PartnerRegistrationId any
}

type PartnerConfiguration_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var PartnerConfiguration_PartnerAuthorizationFields = sdk.FieldMap{
		"AuthorizationExpirationTimeInUtc": sdk.FieldSpec{WireName: "authorization_expiration_time_in_utc"},
		"PartnerName": sdk.FieldSpec{WireName: "partner_name"},
		"PartnerRegistrationId": sdk.FieldSpec{WireName: "partner_registration_id"},
	}

var PartnerConfiguration_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type PartnerConfigurationConfig struct {
	DefaultMaximumExpirationTimeInDays any
	Id any
	ResourceGroupName any
	Tags any
	PartnerAuthorization any
	Timeouts any
}

var PartnerConfiguration = sdk.ResourceBinding{
	WireType: "azurerm_eventgrid_partner_configuration",
	Fields: sdk.FieldMap{
		"DefaultMaximumExpirationTimeInDays": sdk.FieldSpec{WireName: "default_maximum_expiration_time_in_days"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"PartnerAuthorization": sdk.FieldSpec{
			WireName: "partner_authorization",
			Kind: "list",
			Fields: PartnerConfiguration_PartnerAuthorizationFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PartnerConfiguration_TimeoutsFields,
		},
	},
}
