// Code generated by `ubx sdk gen` from azurerm_eventgrid_system_topic_event_subscription. DO NOT EDIT.
package eventgrid

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type SystemTopicEventSubscription_AdvancedFilter_BoolEquals struct {
	Key any
	Value any
}

type SystemTopicEventSubscription_AdvancedFilter_IsNotNull struct {
	Key any
}

type SystemTopicEventSubscription_AdvancedFilter_NumberGreaterThan struct {
	Key any
	Value any
}

type SystemTopicEventSubscription_AdvancedFilter_NumberIn struct {
	Key any
	Values any
}

type SystemTopicEventSubscription_AdvancedFilter_NumberInRange struct {
	Key any
	Values any
}

type SystemTopicEventSubscription_AdvancedFilter_StringBeginsWith struct {
	Key any
	Values any
}

type SystemTopicEventSubscription_AdvancedFilter struct {
	BoolEquals any
	IsNotNull any
	IsNullOrUndefined any
	NumberGreaterThan any
	NumberGreaterThanOrEquals any
	NumberIn any
	NumberInRange any
	NumberLessThan any
	NumberLessThanOrEquals any
	NumberNotIn any
	NumberNotInRange any
	StringBeginsWith any
	StringContains any
	StringEndsWith any
	StringIn any
	StringNotBeginsWith any
	StringNotContains any
	StringNotEndsWith any
	StringNotIn any
}

type SystemTopicEventSubscription_AzureFunctionEndpoint struct {
	FunctionId any
	MaxEventsPerBatch any
	PreferredBatchSizeInKilobytes any
}

type SystemTopicEventSubscription_DeadLetterIdentity struct {
	Type any
	UserAssignedIdentity any
}

type SystemTopicEventSubscription_DeliveryProperty struct {
	HeaderName any
	Secret any
	SourceField any
	Type any
	Value any
}

type SystemTopicEventSubscription_RetryPolicy struct {
	EventTimeToLive any
	MaxDeliveryAttempts any
}

type SystemTopicEventSubscription_StorageBlobDeadLetterDestination struct {
	StorageAccountId any
	StorageBlobContainerName any
}

type SystemTopicEventSubscription_StorageQueueEndpoint struct {
	QueueMessageTimeToLiveInSeconds any
	QueueName any
	StorageAccountId any
}

type SystemTopicEventSubscription_SubjectFilter struct {
	CaseSensitive any
	SubjectBeginsWith any
	SubjectEndsWith any
}

type SystemTopicEventSubscription_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type SystemTopicEventSubscription_WebhookEndpoint struct {
	ActiveDirectoryAppIdOrUri any
	ActiveDirectoryTenantId any
	BaseUrl any
	MaxEventsPerBatch any
	PreferredBatchSizeInKilobytes any
	Url any
}

var SystemTopicEventSubscription_AdvancedFilter_BoolEqualsFields = sdk.FieldMap{
		"Key": sdk.FieldSpec{WireName: "key"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var SystemTopicEventSubscription_AdvancedFilter_IsNotNullFields = sdk.FieldMap{
		"Key": sdk.FieldSpec{WireName: "key"},
	}

var SystemTopicEventSubscription_AdvancedFilter_NumberGreaterThanFields = sdk.FieldMap{
		"Key": sdk.FieldSpec{WireName: "key"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var SystemTopicEventSubscription_AdvancedFilter_NumberInFields = sdk.FieldMap{
		"Key": sdk.FieldSpec{WireName: "key"},
		"Values": sdk.FieldSpec{WireName: "values"},
	}

var SystemTopicEventSubscription_AdvancedFilter_NumberInRangeFields = sdk.FieldMap{
		"Key": sdk.FieldSpec{WireName: "key"},
		"Values": sdk.FieldSpec{WireName: "values"},
	}

var SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields = sdk.FieldMap{
		"Key": sdk.FieldSpec{WireName: "key"},
		"Values": sdk.FieldSpec{WireName: "values"},
	}

var SystemTopicEventSubscription_AdvancedFilterFields = sdk.FieldMap{
		"BoolEquals": sdk.FieldSpec{
			WireName: "bool_equals",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_BoolEqualsFields,
		},
		"IsNotNull": sdk.FieldSpec{
			WireName: "is_not_null",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_IsNotNullFields,
		},
		"IsNullOrUndefined": sdk.FieldSpec{
			WireName: "is_null_or_undefined",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_IsNotNullFields,
		},
		"NumberGreaterThan": sdk.FieldSpec{
			WireName: "number_greater_than",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberGreaterThanFields,
		},
		"NumberGreaterThanOrEquals": sdk.FieldSpec{
			WireName: "number_greater_than_or_equals",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberGreaterThanFields,
		},
		"NumberIn": sdk.FieldSpec{
			WireName: "number_in",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberInFields,
		},
		"NumberInRange": sdk.FieldSpec{
			WireName: "number_in_range",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberInRangeFields,
		},
		"NumberLessThan": sdk.FieldSpec{
			WireName: "number_less_than",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberGreaterThanFields,
		},
		"NumberLessThanOrEquals": sdk.FieldSpec{
			WireName: "number_less_than_or_equals",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberGreaterThanFields,
		},
		"NumberNotIn": sdk.FieldSpec{
			WireName: "number_not_in",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberInFields,
		},
		"NumberNotInRange": sdk.FieldSpec{
			WireName: "number_not_in_range",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_NumberInRangeFields,
		},
		"StringBeginsWith": sdk.FieldSpec{
			WireName: "string_begins_with",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
		"StringContains": sdk.FieldSpec{
			WireName: "string_contains",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
		"StringEndsWith": sdk.FieldSpec{
			WireName: "string_ends_with",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
		"StringIn": sdk.FieldSpec{
			WireName: "string_in",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
		"StringNotBeginsWith": sdk.FieldSpec{
			WireName: "string_not_begins_with",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
		"StringNotContains": sdk.FieldSpec{
			WireName: "string_not_contains",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
		"StringNotEndsWith": sdk.FieldSpec{
			WireName: "string_not_ends_with",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
		"StringNotIn": sdk.FieldSpec{
			WireName: "string_not_in",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilter_StringBeginsWithFields,
		},
	}

var SystemTopicEventSubscription_AzureFunctionEndpointFields = sdk.FieldMap{
		"FunctionId": sdk.FieldSpec{WireName: "function_id"},
		"MaxEventsPerBatch": sdk.FieldSpec{WireName: "max_events_per_batch"},
		"PreferredBatchSizeInKilobytes": sdk.FieldSpec{WireName: "preferred_batch_size_in_kilobytes"},
	}

var SystemTopicEventSubscription_DeadLetterIdentityFields = sdk.FieldMap{
		"Type": sdk.FieldSpec{WireName: "type"},
		"UserAssignedIdentity": sdk.FieldSpec{WireName: "user_assigned_identity"},
	}

var SystemTopicEventSubscription_DeliveryPropertyFields = sdk.FieldMap{
		"HeaderName": sdk.FieldSpec{WireName: "header_name"},
		"Secret": sdk.FieldSpec{WireName: "secret"},
		"SourceField": sdk.FieldSpec{WireName: "source_field"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var SystemTopicEventSubscription_RetryPolicyFields = sdk.FieldMap{
		"EventTimeToLive": sdk.FieldSpec{WireName: "event_time_to_live"},
		"MaxDeliveryAttempts": sdk.FieldSpec{WireName: "max_delivery_attempts"},
	}

var SystemTopicEventSubscription_StorageBlobDeadLetterDestinationFields = sdk.FieldMap{
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
		"StorageBlobContainerName": sdk.FieldSpec{WireName: "storage_blob_container_name"},
	}

var SystemTopicEventSubscription_StorageQueueEndpointFields = sdk.FieldMap{
		"QueueMessageTimeToLiveInSeconds": sdk.FieldSpec{WireName: "queue_message_time_to_live_in_seconds"},
		"QueueName": sdk.FieldSpec{WireName: "queue_name"},
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
	}

var SystemTopicEventSubscription_SubjectFilterFields = sdk.FieldMap{
		"CaseSensitive": sdk.FieldSpec{WireName: "case_sensitive"},
		"SubjectBeginsWith": sdk.FieldSpec{WireName: "subject_begins_with"},
		"SubjectEndsWith": sdk.FieldSpec{WireName: "subject_ends_with"},
	}

var SystemTopicEventSubscription_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var SystemTopicEventSubscription_WebhookEndpointFields = sdk.FieldMap{
		"ActiveDirectoryAppIdOrUri": sdk.FieldSpec{WireName: "active_directory_app_id_or_uri"},
		"ActiveDirectoryTenantId": sdk.FieldSpec{WireName: "active_directory_tenant_id"},
		"BaseUrl": sdk.FieldSpec{WireName: "base_url"},
		"MaxEventsPerBatch": sdk.FieldSpec{WireName: "max_events_per_batch"},
		"PreferredBatchSizeInKilobytes": sdk.FieldSpec{WireName: "preferred_batch_size_in_kilobytes"},
		"Url": sdk.FieldSpec{WireName: "url"},
	}

type SystemTopicEventSubscriptionConfig struct {
	AdvancedFilteringOnArraysEnabled any
	EventDeliverySchema any
	EventhubId any
	ExpirationTimeUtc any
	HybridConnectionId any
	Id any
	IncludedEventTypes any
	Labels any
	Name any
	ResourceGroupName any
	ServiceBusQueueId any
	ServiceBusTopicId any
	SystemTopic any
	AdvancedFilter any
	AzureFunctionEndpoint any
	DeadLetterIdentity any
	DeliveryIdentity any
	DeliveryProperty any
	RetryPolicy any
	StorageBlobDeadLetterDestination any
	StorageQueueEndpoint any
	SubjectFilter any
	Timeouts any
	WebhookEndpoint any
}

var SystemTopicEventSubscription = sdk.ResourceBinding{
	WireType: "azurerm_eventgrid_system_topic_event_subscription",
	Fields: sdk.FieldMap{
		"AdvancedFilteringOnArraysEnabled": sdk.FieldSpec{WireName: "advanced_filtering_on_arrays_enabled"},
		"EventDeliverySchema": sdk.FieldSpec{WireName: "event_delivery_schema"},
		"EventhubId": sdk.FieldSpec{WireName: "eventhub_id"},
		"ExpirationTimeUtc": sdk.FieldSpec{WireName: "expiration_time_utc"},
		"HybridConnectionId": sdk.FieldSpec{WireName: "hybrid_connection_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IncludedEventTypes": sdk.FieldSpec{WireName: "included_event_types"},
		"Labels": sdk.FieldSpec{WireName: "labels"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ServiceBusQueueId": sdk.FieldSpec{WireName: "service_bus_queue_id"},
		"ServiceBusTopicId": sdk.FieldSpec{WireName: "service_bus_topic_id"},
		"SystemTopic": sdk.FieldSpec{WireName: "system_topic"},
		"AdvancedFilter": sdk.FieldSpec{
			WireName: "advanced_filter",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AdvancedFilterFields,
		},
		"AzureFunctionEndpoint": sdk.FieldSpec{
			WireName: "azure_function_endpoint",
			Kind: "list",
			Fields: SystemTopicEventSubscription_AzureFunctionEndpointFields,
		},
		"DeadLetterIdentity": sdk.FieldSpec{
			WireName: "dead_letter_identity",
			Kind: "list",
			Fields: SystemTopicEventSubscription_DeadLetterIdentityFields,
		},
		"DeliveryIdentity": sdk.FieldSpec{
			WireName: "delivery_identity",
			Kind: "list",
			Fields: SystemTopicEventSubscription_DeadLetterIdentityFields,
		},
		"DeliveryProperty": sdk.FieldSpec{
			WireName: "delivery_property",
			Kind: "list",
			Fields: SystemTopicEventSubscription_DeliveryPropertyFields,
		},
		"RetryPolicy": sdk.FieldSpec{
			WireName: "retry_policy",
			Kind: "list",
			Fields: SystemTopicEventSubscription_RetryPolicyFields,
		},
		"StorageBlobDeadLetterDestination": sdk.FieldSpec{
			WireName: "storage_blob_dead_letter_destination",
			Kind: "list",
			Fields: SystemTopicEventSubscription_StorageBlobDeadLetterDestinationFields,
		},
		"StorageQueueEndpoint": sdk.FieldSpec{
			WireName: "storage_queue_endpoint",
			Kind: "list",
			Fields: SystemTopicEventSubscription_StorageQueueEndpointFields,
		},
		"SubjectFilter": sdk.FieldSpec{
			WireName: "subject_filter",
			Kind: "list",
			Fields: SystemTopicEventSubscription_SubjectFilterFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: SystemTopicEventSubscription_TimeoutsFields,
		},
		"WebhookEndpoint": sdk.FieldSpec{
			WireName: "webhook_endpoint",
			Kind: "list",
			Fields: SystemTopicEventSubscription_WebhookEndpointFields,
		},
	},
}
