// Code generated by `ubx sdk gen` from azurerm_firewall_nat_rule_collection. DO NOT EDIT.
package firewall

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type NatRuleCollection_Rule struct {
	Description any
	DestinationAddresses any
	DestinationPorts any
	Name any
	Protocols any
	SourceAddresses any
	SourceIpGroups any
	TranslatedAddress any
	TranslatedPort any
}

type NatRuleCollection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var NatRuleCollection_RuleFields = sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"DestinationAddresses": sdk.FieldSpec{WireName: "destination_addresses"},
		"DestinationPorts": sdk.FieldSpec{WireName: "destination_ports"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Protocols": sdk.FieldSpec{WireName: "protocols"},
		"SourceAddresses": sdk.FieldSpec{WireName: "source_addresses"},
		"SourceIpGroups": sdk.FieldSpec{WireName: "source_ip_groups"},
		"TranslatedAddress": sdk.FieldSpec{WireName: "translated_address"},
		"TranslatedPort": sdk.FieldSpec{WireName: "translated_port"},
	}

var NatRuleCollection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type NatRuleCollectionConfig struct {
	Action any
	AzureFirewallName any
	Id any
	Name any
	Priority any
	ResourceGroupName any
	Rule any
	Timeouts any
}

var NatRuleCollection = sdk.ResourceBinding{
	WireType: "azurerm_firewall_nat_rule_collection",
	Fields: sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"AzureFirewallName": sdk.FieldSpec{WireName: "azure_firewall_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Rule": sdk.FieldSpec{
			WireName: "rule",
			Kind: "list",
			Fields: NatRuleCollection_RuleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: NatRuleCollection_TimeoutsFields,
		},
	},
}
