// Code generated by `ubx sdk gen` from azurerm_databox_edge_device. DO NOT EDIT.
package databox

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type EdgeDevice_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var EdgeDevice_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type EdgeDeviceConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	SkuName any
	Tags any
	Timeouts any
}

var EdgeDevice = sdk.ResourceBinding{
	WireType: "azurerm_databox_edge_device",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SkuName": sdk.FieldSpec{WireName: "sku_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: EdgeDevice_TimeoutsFields,
		},
	},
}
