// Code generated by `ubx sdk gen` from azurerm_arc_kubernetes_cluster. DO NOT EDIT.
package arc

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type KubernetesCluster_Identity struct {
	PrincipalId any
	TenantId any
	Type any
}

type KubernetesCluster_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var KubernetesCluster_IdentityFields = sdk.FieldMap{
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var KubernetesCluster_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type KubernetesClusterConfig struct {
	AgentPublicKeyCertificate any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	Identity any
	Timeouts any
}

var KubernetesCluster = sdk.ResourceBinding{
	WireType: "azurerm_arc_kubernetes_cluster",
	Fields: sdk.FieldMap{
		"AgentPublicKeyCertificate": sdk.FieldSpec{WireName: "agent_public_key_certificate"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: KubernetesCluster_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: KubernetesCluster_TimeoutsFields,
		},
	},
}
