// Code generated by `ubx sdk gen` from azurerm_arc_machine_automanage_configuration_assignment. DO NOT EDIT.
package arc

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type MachineAutomanageConfigurationAssignment_Timeouts struct {
	Create any
	Delete any
	Read any
}

var MachineAutomanageConfigurationAssignment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type MachineAutomanageConfigurationAssignmentConfig struct {
	ArcMachineId any
	ConfigurationId any
	Id any
	Timeouts any
}

var MachineAutomanageConfigurationAssignment = sdk.ResourceBinding{
	WireType: "azurerm_arc_machine_automanage_configuration_assignment",
	Fields: sdk.FieldMap{
		"ArcMachineId": sdk.FieldSpec{WireName: "arc_machine_id"},
		"ConfigurationId": sdk.FieldSpec{WireName: "configuration_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: MachineAutomanageConfigurationAssignment_TimeoutsFields,
		},
	},
}
