// Code generated by `ubx sdk gen` from azurerm_route_map. DO NOT EDIT.
package route

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Map_Rule_Action_Parameter struct {
	AsPath any
	Community any
	RoutePrefix any
}

type Map_Rule_Action struct {
	Type any
	Parameter any
}

type Map_Rule_MatchCriterion struct {
	AsPath any
	Community any
	MatchCondition any
	RoutePrefix any
}

type Map_Rule struct {
	Name any
	NextStepIfMatched any
	Action any
	MatchCriterion any
}

type Map_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Map_Rule_Action_ParameterFields = sdk.FieldMap{
		"AsPath": sdk.FieldSpec{WireName: "as_path"},
		"Community": sdk.FieldSpec{WireName: "community"},
		"RoutePrefix": sdk.FieldSpec{WireName: "route_prefix"},
	}

var Map_Rule_ActionFields = sdk.FieldMap{
		"Type": sdk.FieldSpec{WireName: "type"},
		"Parameter": sdk.FieldSpec{
			WireName: "parameter",
			Kind: "list",
			Fields: Map_Rule_Action_ParameterFields,
		},
	}

var Map_Rule_MatchCriterionFields = sdk.FieldMap{
		"AsPath": sdk.FieldSpec{WireName: "as_path"},
		"Community": sdk.FieldSpec{WireName: "community"},
		"MatchCondition": sdk.FieldSpec{WireName: "match_condition"},
		"RoutePrefix": sdk.FieldSpec{WireName: "route_prefix"},
	}

var Map_RuleFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"NextStepIfMatched": sdk.FieldSpec{WireName: "next_step_if_matched"},
		"Action": sdk.FieldSpec{
			WireName: "action",
			Kind: "list",
			Fields: Map_Rule_ActionFields,
		},
		"MatchCriterion": sdk.FieldSpec{
			WireName: "match_criterion",
			Kind: "list",
			Fields: Map_Rule_MatchCriterionFields,
		},
	}

var Map_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type MapConfig struct {
	Id any
	Name any
	VirtualHubId any
	Rule any
	Timeouts any
}

var Map = sdk.ResourceBinding{
	WireType: "azurerm_route_map",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"VirtualHubId": sdk.FieldSpec{WireName: "virtual_hub_id"},
		"Rule": sdk.FieldSpec{
			WireName: "rule",
			Kind: "list",
			Fields: Map_RuleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Map_TimeoutsFields,
		},
	},
}
