// Code generated by `ubx sdk gen` from azurerm_route. DO NOT EDIT.
package route

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Route_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Route_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type RouteConfig struct {
	AddressPrefix any
	Id any
	Name any
	NextHopInIpAddress any
	NextHopType any
	ResourceGroupName any
	RouteTableName any
	Timeouts any
}

var Route = sdk.ResourceBinding{
	WireType: "azurerm_route",
	Fields: sdk.FieldMap{
		"AddressPrefix": sdk.FieldSpec{WireName: "address_prefix"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NextHopInIpAddress": sdk.FieldSpec{WireName: "next_hop_in_ip_address"},
		"NextHopType": sdk.FieldSpec{WireName: "next_hop_type"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"RouteTableName": sdk.FieldSpec{WireName: "route_table_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Route_TimeoutsFields,
		},
	},
}
