// Code generated by `ubx sdk gen` from azurerm_signalr_service. DO NOT EDIT.
package signalr

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Service_Cors struct {
	AllowedOrigins any
}

type Service_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Service_LiveTrace struct {
	ConnectivityLogsEnabled any
	Enabled any
	HttpRequestLogsEnabled any
	MessagingLogsEnabled any
}

type Service_Sku struct {
	Capacity any
	Name any
}

type Service_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type Service_UpstreamEndpoint struct {
	CategoryPattern any
	EventPattern any
	HubPattern any
	UrlTemplate any
	UserAssignedIdentityId any
}

var Service_CorsFields = sdk.FieldMap{
		"AllowedOrigins": sdk.FieldSpec{WireName: "allowed_origins"},
	}

var Service_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Service_LiveTraceFields = sdk.FieldMap{
		"ConnectivityLogsEnabled": sdk.FieldSpec{WireName: "connectivity_logs_enabled"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"HttpRequestLogsEnabled": sdk.FieldSpec{WireName: "http_request_logs_enabled"},
		"MessagingLogsEnabled": sdk.FieldSpec{WireName: "messaging_logs_enabled"},
	}

var Service_SkuFields = sdk.FieldMap{
		"Capacity": sdk.FieldSpec{WireName: "capacity"},
		"Name": sdk.FieldSpec{WireName: "name"},
	}

var Service_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var Service_UpstreamEndpointFields = sdk.FieldMap{
		"CategoryPattern": sdk.FieldSpec{WireName: "category_pattern"},
		"EventPattern": sdk.FieldSpec{WireName: "event_pattern"},
		"HubPattern": sdk.FieldSpec{WireName: "hub_pattern"},
		"UrlTemplate": sdk.FieldSpec{WireName: "url_template"},
		"UserAssignedIdentityId": sdk.FieldSpec{WireName: "user_assigned_identity_id"},
	}

type ServiceConfig struct {
	AadAuthEnabled any
	ConnectivityLogsEnabled any
	HttpRequestLogsEnabled any
	Id any
	LiveTraceEnabled any
	LocalAuthEnabled any
	Location any
	MessagingLogsEnabled any
	Name any
	PublicNetworkAccessEnabled any
	ResourceGroupName any
	ServerlessConnectionTimeoutInSeconds any
	ServiceMode any
	Tags any
	TlsClientCertEnabled any
	Cors any
	Identity any
	LiveTrace any
	Sku any
	Timeouts any
	UpstreamEndpoint any
}

var Service = sdk.ResourceBinding{
	WireType: "azurerm_signalr_service",
	Fields: sdk.FieldMap{
		"AadAuthEnabled": sdk.FieldSpec{WireName: "aad_auth_enabled"},
		"ConnectivityLogsEnabled": sdk.FieldSpec{WireName: "connectivity_logs_enabled"},
		"HttpRequestLogsEnabled": sdk.FieldSpec{WireName: "http_request_logs_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LiveTraceEnabled": sdk.FieldSpec{WireName: "live_trace_enabled"},
		"LocalAuthEnabled": sdk.FieldSpec{WireName: "local_auth_enabled"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MessagingLogsEnabled": sdk.FieldSpec{WireName: "messaging_logs_enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PublicNetworkAccessEnabled": sdk.FieldSpec{WireName: "public_network_access_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ServerlessConnectionTimeoutInSeconds": sdk.FieldSpec{WireName: "serverless_connection_timeout_in_seconds"},
		"ServiceMode": sdk.FieldSpec{WireName: "service_mode"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TlsClientCertEnabled": sdk.FieldSpec{WireName: "tls_client_cert_enabled"},
		"Cors": sdk.FieldSpec{
			WireName: "cors",
			Kind: "list",
			Fields: Service_CorsFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Service_IdentityFields,
		},
		"LiveTrace": sdk.FieldSpec{
			WireName: "live_trace",
			Kind: "list",
			Fields: Service_LiveTraceFields,
		},
		"Sku": sdk.FieldSpec{
			WireName: "sku",
			Kind: "list",
			Fields: Service_SkuFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Service_TimeoutsFields,
		},
		"UpstreamEndpoint": sdk.FieldSpec{
			WireName: "upstream_endpoint",
			Kind: "set",
			Fields: Service_UpstreamEndpointFields,
		},
	},
}
