// Code generated by `ubx sdk gen` from azurerm_data_factory_trigger_tumbling_window. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryTriggerTumblingWindow_Pipeline struct {
	Name any
	Parameters any
}

type FactoryTriggerTumblingWindow_Retry struct {
	Count any
	Interval any
}

type FactoryTriggerTumblingWindow_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type FactoryTriggerTumblingWindow_TriggerDependency struct {
	Offset any
	Size any
	TriggerName any
}

var FactoryTriggerTumblingWindow_PipelineFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
	}

var FactoryTriggerTumblingWindow_RetryFields = sdk.FieldMap{
		"Count": sdk.FieldSpec{WireName: "count"},
		"Interval": sdk.FieldSpec{WireName: "interval"},
	}

var FactoryTriggerTumblingWindow_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var FactoryTriggerTumblingWindow_TriggerDependencyFields = sdk.FieldMap{
		"Offset": sdk.FieldSpec{WireName: "offset"},
		"Size": sdk.FieldSpec{WireName: "size"},
		"TriggerName": sdk.FieldSpec{WireName: "trigger_name"},
	}

type FactoryTriggerTumblingWindowConfig struct {
	Activated any
	AdditionalProperties any
	Annotations any
	DataFactoryId any
	Delay any
	Description any
	EndTime any
	Frequency any
	Id any
	Interval any
	MaxConcurrency any
	Name any
	StartTime any
	Pipeline any
	Retry any
	Timeouts any
	TriggerDependency any
}

var FactoryTriggerTumblingWindow = sdk.ResourceBinding{
	WireType: "azurerm_data_factory_trigger_tumbling_window",
	Fields: sdk.FieldMap{
		"Activated": sdk.FieldSpec{WireName: "activated"},
		"AdditionalProperties": sdk.FieldSpec{WireName: "additional_properties"},
		"Annotations": sdk.FieldSpec{WireName: "annotations"},
		"DataFactoryId": sdk.FieldSpec{WireName: "data_factory_id"},
		"Delay": sdk.FieldSpec{WireName: "delay"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"EndTime": sdk.FieldSpec{WireName: "end_time"},
		"Frequency": sdk.FieldSpec{WireName: "frequency"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Interval": sdk.FieldSpec{WireName: "interval"},
		"MaxConcurrency": sdk.FieldSpec{WireName: "max_concurrency"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"StartTime": sdk.FieldSpec{WireName: "start_time"},
		"Pipeline": sdk.FieldSpec{
			WireName: "pipeline",
			Kind: "list",
			Fields: FactoryTriggerTumblingWindow_PipelineFields,
		},
		"Retry": sdk.FieldSpec{
			WireName: "retry",
			Kind: "list",
			Fields: FactoryTriggerTumblingWindow_RetryFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryTriggerTumblingWindow_TimeoutsFields,
		},
		"TriggerDependency": sdk.FieldSpec{
			WireName: "trigger_dependency",
			Kind: "set",
			Fields: FactoryTriggerTumblingWindow_TriggerDependencyFields,
		},
	},
}
