// Code generated by `ubx sdk gen` from azurerm_data_factory_trigger_schedule. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryTriggerSchedule_Pipeline struct {
	Name any
	Parameters any
}

type FactoryTriggerSchedule_Schedule_Monthly struct {
	Week any
	Weekday any
}

type FactoryTriggerSchedule_Schedule struct {
	DaysOfMonth any
	DaysOfWeek any
	Hours any
	Minutes any
	Monthly any
}

type FactoryTriggerSchedule_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FactoryTriggerSchedule_PipelineFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
	}

var FactoryTriggerSchedule_Schedule_MonthlyFields = sdk.FieldMap{
		"Week": sdk.FieldSpec{WireName: "week"},
		"Weekday": sdk.FieldSpec{WireName: "weekday"},
	}

var FactoryTriggerSchedule_ScheduleFields = sdk.FieldMap{
		"DaysOfMonth": sdk.FieldSpec{WireName: "days_of_month"},
		"DaysOfWeek": sdk.FieldSpec{WireName: "days_of_week"},
		"Hours": sdk.FieldSpec{WireName: "hours"},
		"Minutes": sdk.FieldSpec{WireName: "minutes"},
		"Monthly": sdk.FieldSpec{
			WireName: "monthly",
			Kind: "list",
			Fields: FactoryTriggerSchedule_Schedule_MonthlyFields,
		},
	}

var FactoryTriggerSchedule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FactoryTriggerScheduleConfig struct {
	Activated any
	Annotations any
	DataFactoryId any
	Description any
	EndTime any
	Frequency any
	Id any
	Interval any
	Name any
	PipelineName any
	PipelineParameters any
	StartTime any
	TimeZone any
	Pipeline any
	Schedule any
	Timeouts any
}

var FactoryTriggerSchedule = sdk.ResourceBinding{
	WireType: "azurerm_data_factory_trigger_schedule",
	Fields: sdk.FieldMap{
		"Activated": sdk.FieldSpec{WireName: "activated"},
		"Annotations": sdk.FieldSpec{WireName: "annotations"},
		"DataFactoryId": sdk.FieldSpec{WireName: "data_factory_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"EndTime": sdk.FieldSpec{WireName: "end_time"},
		"Frequency": sdk.FieldSpec{WireName: "frequency"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Interval": sdk.FieldSpec{WireName: "interval"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PipelineName": sdk.FieldSpec{WireName: "pipeline_name"},
		"PipelineParameters": sdk.FieldSpec{WireName: "pipeline_parameters"},
		"StartTime": sdk.FieldSpec{WireName: "start_time"},
		"TimeZone": sdk.FieldSpec{WireName: "time_zone"},
		"Pipeline": sdk.FieldSpec{
			WireName: "pipeline",
			Kind: "list",
			Fields: FactoryTriggerSchedule_PipelineFields,
		},
		"Schedule": sdk.FieldSpec{
			WireName: "schedule",
			Kind: "list",
			Fields: FactoryTriggerSchedule_ScheduleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryTriggerSchedule_TimeoutsFields,
		},
	},
}
