// Code generated by `ubx sdk gen` from azurerm_data_factory_linked_service_azure_sql_database. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryLinkedServiceAzureSqlDatabase_KeyVaultConnectionString struct {
	LinkedServiceName any
	SecretName any
}

type FactoryLinkedServiceAzureSqlDatabase_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FactoryLinkedServiceAzureSqlDatabase_KeyVaultConnectionStringFields = sdk.FieldMap{
		"LinkedServiceName": sdk.FieldSpec{WireName: "linked_service_name"},
		"SecretName": sdk.FieldSpec{WireName: "secret_name"},
	}

var FactoryLinkedServiceAzureSqlDatabase_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FactoryLinkedServiceAzureSqlDatabaseConfig struct {
	AdditionalProperties any
	Annotations any
	ConnectionString any
	CredentialName any
	DataFactoryId any
	Description any
	Id any
	IntegrationRuntimeName any
	Name any
	Parameters any
	ServicePrincipalId any
	ServicePrincipalKey any
	TenantId any
	UseManagedIdentity any
	KeyVaultConnectionString any
	KeyVaultPassword any
	Timeouts any
}

var FactoryLinkedServiceAzureSqlDatabase = sdk.ResourceBinding{
	WireType: "azurerm_data_factory_linked_service_azure_sql_database",
	Fields: sdk.FieldMap{
		"AdditionalProperties": sdk.FieldSpec{WireName: "additional_properties"},
		"Annotations": sdk.FieldSpec{WireName: "annotations"},
		"ConnectionString": sdk.FieldSpec{WireName: "connection_string"},
		"CredentialName": sdk.FieldSpec{WireName: "credential_name"},
		"DataFactoryId": sdk.FieldSpec{WireName: "data_factory_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IntegrationRuntimeName": sdk.FieldSpec{WireName: "integration_runtime_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
		"ServicePrincipalId": sdk.FieldSpec{WireName: "service_principal_id"},
		"ServicePrincipalKey": sdk.FieldSpec{WireName: "service_principal_key"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"UseManagedIdentity": sdk.FieldSpec{WireName: "use_managed_identity"},
		"KeyVaultConnectionString": sdk.FieldSpec{
			WireName: "key_vault_connection_string",
			Kind: "list",
			Fields: FactoryLinkedServiceAzureSqlDatabase_KeyVaultConnectionStringFields,
		},
		"KeyVaultPassword": sdk.FieldSpec{
			WireName: "key_vault_password",
			Kind: "list",
			Fields: FactoryLinkedServiceAzureSqlDatabase_KeyVaultConnectionStringFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryLinkedServiceAzureSqlDatabase_TimeoutsFields,
		},
	},
}
