// Code generated by `ubx sdk gen` from azurerm_data_factory_linked_service_odata. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryLinkedServiceOdata_BasicAuthentication struct {
	Password any
	Username any
}

type FactoryLinkedServiceOdata_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FactoryLinkedServiceOdata_BasicAuthenticationFields = sdk.FieldMap{
		"Password": sdk.FieldSpec{WireName: "password"},
		"Username": sdk.FieldSpec{WireName: "username"},
	}

var FactoryLinkedServiceOdata_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FactoryLinkedServiceOdataConfig struct {
	AdditionalProperties any
	Annotations any
	DataFactoryId any
	Description any
	Id any
	IntegrationRuntimeName any
	Name any
	Parameters any
	Url any
	BasicAuthentication any
	Timeouts any
}

var FactoryLinkedServiceOdata = sdk.ResourceBinding{
	WireType: "azurerm_data_factory_linked_service_odata",
	Fields: sdk.FieldMap{
		"AdditionalProperties": sdk.FieldSpec{WireName: "additional_properties"},
		"Annotations": sdk.FieldSpec{WireName: "annotations"},
		"DataFactoryId": sdk.FieldSpec{WireName: "data_factory_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IntegrationRuntimeName": sdk.FieldSpec{WireName: "integration_runtime_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
		"Url": sdk.FieldSpec{WireName: "url"},
		"BasicAuthentication": sdk.FieldSpec{
			WireName: "basic_authentication",
			Kind: "list",
			Fields: FactoryLinkedServiceOdata_BasicAuthenticationFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryLinkedServiceOdata_TimeoutsFields,
		},
	},
}
