// Code generated by `ubx sdk gen` from azurerm_data_factory_linked_service_sql_managed_instance. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryLinkedServiceSqlManagedInstance_KeyVaultConnectionString struct {
	LinkedServiceName any
	SecretName any
}

type FactoryLinkedServiceSqlManagedInstance_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FactoryLinkedServiceSqlManagedInstance_KeyVaultConnectionStringFields = sdk.FieldMap{
		"LinkedServiceName": sdk.FieldSpec{WireName: "linked_service_name"},
		"SecretName": sdk.FieldSpec{WireName: "secret_name"},
	}

var FactoryLinkedServiceSqlManagedInstance_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FactoryLinkedServiceSqlManagedInstanceConfig struct {
	Annotations any
	ConnectionString any
	DataFactoryId any
	Description any
	Id any
	IntegrationRuntimeName any
	Name any
	Parameters any
	ServicePrincipalId any
	ServicePrincipalKey any
	Tenant any
	KeyVaultConnectionString any
	KeyVaultPassword any
	Timeouts any
}

var FactoryLinkedServiceSqlManagedInstance = sdk.ResourceBinding{
	WireType: "azurerm_data_factory_linked_service_sql_managed_instance",
	Fields: sdk.FieldMap{
		"Annotations": sdk.FieldSpec{WireName: "annotations"},
		"ConnectionString": sdk.FieldSpec{WireName: "connection_string"},
		"DataFactoryId": sdk.FieldSpec{WireName: "data_factory_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IntegrationRuntimeName": sdk.FieldSpec{WireName: "integration_runtime_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
		"ServicePrincipalId": sdk.FieldSpec{WireName: "service_principal_id"},
		"ServicePrincipalKey": sdk.FieldSpec{WireName: "service_principal_key"},
		"Tenant": sdk.FieldSpec{WireName: "tenant"},
		"KeyVaultConnectionString": sdk.FieldSpec{
			WireName: "key_vault_connection_string",
			Kind: "list",
			Fields: FactoryLinkedServiceSqlManagedInstance_KeyVaultConnectionStringFields,
		},
		"KeyVaultPassword": sdk.FieldSpec{
			WireName: "key_vault_password",
			Kind: "list",
			Fields: FactoryLinkedServiceSqlManagedInstance_KeyVaultConnectionStringFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryLinkedServiceSqlManagedInstance_TimeoutsFields,
		},
	},
}
