// Code generated by `ubx sdk gen` from azurerm_data_factory_linked_service_sql_server. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FactoryLinkedServiceSqlServer_KeyVaultConnectionString struct {
	LinkedServiceName any
	SecretName any
}

type FactoryLinkedServiceSqlServer_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FactoryLinkedServiceSqlServer_KeyVaultConnectionStringFields = sdk.FieldMap{
		"LinkedServiceName": sdk.FieldSpec{WireName: "linked_service_name"},
		"SecretName": sdk.FieldSpec{WireName: "secret_name"},
	}

var FactoryLinkedServiceSqlServer_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FactoryLinkedServiceSqlServerConfig struct {
	AdditionalProperties any
	Annotations any
	ConnectionString any
	DataFactoryId any
	Description any
	Id any
	IntegrationRuntimeName any
	Name any
	Parameters any
	UserName any
	KeyVaultConnectionString any
	KeyVaultPassword any
	Timeouts any
}

var FactoryLinkedServiceSqlServer = sdk.ResourceBinding{
	WireType: "azurerm_data_factory_linked_service_sql_server",
	Fields: sdk.FieldMap{
		"AdditionalProperties": sdk.FieldSpec{WireName: "additional_properties"},
		"Annotations": sdk.FieldSpec{WireName: "annotations"},
		"ConnectionString": sdk.FieldSpec{WireName: "connection_string"},
		"DataFactoryId": sdk.FieldSpec{WireName: "data_factory_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IntegrationRuntimeName": sdk.FieldSpec{WireName: "integration_runtime_name"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Parameters": sdk.FieldSpec{WireName: "parameters"},
		"UserName": sdk.FieldSpec{WireName: "user_name"},
		"KeyVaultConnectionString": sdk.FieldSpec{
			WireName: "key_vault_connection_string",
			Kind: "list",
			Fields: FactoryLinkedServiceSqlServer_KeyVaultConnectionStringFields,
		},
		"KeyVaultPassword": sdk.FieldSpec{
			WireName: "key_vault_password",
			Kind: "list",
			Fields: FactoryLinkedServiceSqlServer_KeyVaultConnectionStringFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FactoryLinkedServiceSqlServer_TimeoutsFields,
		},
	},
}
