// Code generated by `ubx sdk gen` from azurerm_data_protection_backup_instance_kubernetes_cluster. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ProtectionBackupInstanceKubernetesCluster_BackupDatasourceParameters struct {
	ClusterScopedResourcesEnabled any
	ExcludedNamespaces any
	ExcludedResourceTypes any
	IncludedNamespaces any
	IncludedResourceTypes any
	LabelSelectors any
	VolumeSnapshotEnabled any
}

type ProtectionBackupInstanceKubernetesCluster_Timeouts struct {
	Create any
	Delete any
	Read any
}

var ProtectionBackupInstanceKubernetesCluster_BackupDatasourceParametersFields = sdk.FieldMap{
		"ClusterScopedResourcesEnabled": sdk.FieldSpec{WireName: "cluster_scoped_resources_enabled"},
		"ExcludedNamespaces": sdk.FieldSpec{WireName: "excluded_namespaces"},
		"ExcludedResourceTypes": sdk.FieldSpec{WireName: "excluded_resource_types"},
		"IncludedNamespaces": sdk.FieldSpec{WireName: "included_namespaces"},
		"IncludedResourceTypes": sdk.FieldSpec{WireName: "included_resource_types"},
		"LabelSelectors": sdk.FieldSpec{WireName: "label_selectors"},
		"VolumeSnapshotEnabled": sdk.FieldSpec{WireName: "volume_snapshot_enabled"},
	}

var ProtectionBackupInstanceKubernetesCluster_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type ProtectionBackupInstanceKubernetesClusterConfig struct {
	BackupPolicyId any
	Id any
	KubernetesClusterId any
	Location any
	Name any
	SnapshotResourceGroupName any
	VaultId any
	BackupDatasourceParameters any
	Timeouts any
}

var ProtectionBackupInstanceKubernetesCluster = sdk.ResourceBinding{
	WireType: "azurerm_data_protection_backup_instance_kubernetes_cluster",
	Fields: sdk.FieldMap{
		"BackupPolicyId": sdk.FieldSpec{WireName: "backup_policy_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"KubernetesClusterId": sdk.FieldSpec{WireName: "kubernetes_cluster_id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SnapshotResourceGroupName": sdk.FieldSpec{WireName: "snapshot_resource_group_name"},
		"VaultId": sdk.FieldSpec{WireName: "vault_id"},
		"BackupDatasourceParameters": sdk.FieldSpec{
			WireName: "backup_datasource_parameters",
			Kind: "list",
			Fields: ProtectionBackupInstanceKubernetesCluster_BackupDatasourceParametersFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ProtectionBackupInstanceKubernetesCluster_TimeoutsFields,
		},
	},
}
