// Code generated by `ubx sdk gen` from azurerm_data_protection_resource_guard. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ProtectionResourceGuard_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ProtectionResourceGuard_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ProtectionResourceGuardConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	VaultCriticalOperationExclusionList any
	Timeouts any
}

var ProtectionResourceGuard = sdk.ResourceBinding{
	WireType: "azurerm_data_protection_resource_guard",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"VaultCriticalOperationExclusionList": sdk.FieldSpec{WireName: "vault_critical_operation_exclusion_list"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ProtectionResourceGuard_TimeoutsFields,
		},
	},
}
