// Code generated by `ubx sdk gen` from azurerm_data_protection_backup_vault_customer_managed_key. DO NOT EDIT.
package data

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ProtectionBackupVaultCustomerManagedKey_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ProtectionBackupVaultCustomerManagedKey_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ProtectionBackupVaultCustomerManagedKeyConfig struct {
	DataProtectionBackupVaultId any
	Id any
	KeyVaultKeyId any
	Timeouts any
}

var ProtectionBackupVaultCustomerManagedKey = sdk.ResourceBinding{
	WireType: "azurerm_data_protection_backup_vault_customer_managed_key",
	Fields: sdk.FieldMap{
		"DataProtectionBackupVaultId": sdk.FieldSpec{WireName: "data_protection_backup_vault_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"KeyVaultKeyId": sdk.FieldSpec{WireName: "key_vault_key_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ProtectionBackupVaultCustomerManagedKey_TimeoutsFields,
		},
	},
}
