// Code generated by `ubx sdk gen` from azurerm_cdn_frontdoor_firewall_policy. DO NOT EDIT.
package cdn

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FrontdoorFirewallPolicy_CustomRule_MatchCondition struct {
	MatchValues any
	MatchVariable any
	NegationCondition any
	Operator any
	Selector any
	Transforms any
}

type FrontdoorFirewallPolicy_CustomRule struct {
	Action any
	Enabled any
	Name any
	Priority any
	RateLimitDurationInMinutes any
	RateLimitThreshold any
	Type any
	MatchCondition any
}

type FrontdoorFirewallPolicy_LogScrubbing_ScrubbingRule struct {
	Enabled any
	MatchVariable any
	Operator any
	Selector any
}

type FrontdoorFirewallPolicy_LogScrubbing struct {
	Enabled any
	ScrubbingRule any
}

type FrontdoorFirewallPolicy_ManagedRule_Exclusion struct {
	MatchVariable any
	Operator any
	Selector any
}

type FrontdoorFirewallPolicy_ManagedRule_Override_Rule struct {
	Action any
	Enabled any
	RuleId any
	Exclusion any
}

type FrontdoorFirewallPolicy_ManagedRule_Override struct {
	RuleGroupName any
	Exclusion any
	Rule any
}

type FrontdoorFirewallPolicy_ManagedRule struct {
	Action any
	Type any
	Version any
	Exclusion any
	Override any
}

type FrontdoorFirewallPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FrontdoorFirewallPolicy_CustomRule_MatchConditionFields = sdk.FieldMap{
		"MatchValues": sdk.FieldSpec{WireName: "match_values"},
		"MatchVariable": sdk.FieldSpec{WireName: "match_variable"},
		"NegationCondition": sdk.FieldSpec{WireName: "negation_condition"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Selector": sdk.FieldSpec{WireName: "selector"},
		"Transforms": sdk.FieldSpec{WireName: "transforms"},
	}

var FrontdoorFirewallPolicy_CustomRuleFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"RateLimitDurationInMinutes": sdk.FieldSpec{WireName: "rate_limit_duration_in_minutes"},
		"RateLimitThreshold": sdk.FieldSpec{WireName: "rate_limit_threshold"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"MatchCondition": sdk.FieldSpec{
			WireName: "match_condition",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_CustomRule_MatchConditionFields,
		},
	}

var FrontdoorFirewallPolicy_LogScrubbing_ScrubbingRuleFields = sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"MatchVariable": sdk.FieldSpec{WireName: "match_variable"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Selector": sdk.FieldSpec{WireName: "selector"},
	}

var FrontdoorFirewallPolicy_LogScrubbingFields = sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"ScrubbingRule": sdk.FieldSpec{
			WireName: "scrubbing_rule",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_LogScrubbing_ScrubbingRuleFields,
		},
	}

var FrontdoorFirewallPolicy_ManagedRule_ExclusionFields = sdk.FieldMap{
		"MatchVariable": sdk.FieldSpec{WireName: "match_variable"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Selector": sdk.FieldSpec{WireName: "selector"},
	}

var FrontdoorFirewallPolicy_ManagedRule_Override_RuleFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"RuleId": sdk.FieldSpec{WireName: "rule_id"},
		"Exclusion": sdk.FieldSpec{
			WireName: "exclusion",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_ManagedRule_ExclusionFields,
		},
	}

var FrontdoorFirewallPolicy_ManagedRule_OverrideFields = sdk.FieldMap{
		"RuleGroupName": sdk.FieldSpec{WireName: "rule_group_name"},
		"Exclusion": sdk.FieldSpec{
			WireName: "exclusion",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_ManagedRule_ExclusionFields,
		},
		"Rule": sdk.FieldSpec{
			WireName: "rule",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_ManagedRule_Override_RuleFields,
		},
	}

var FrontdoorFirewallPolicy_ManagedRuleFields = sdk.FieldMap{
		"Action": sdk.FieldSpec{WireName: "action"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Version": sdk.FieldSpec{WireName: "version"},
		"Exclusion": sdk.FieldSpec{
			WireName: "exclusion",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_ManagedRule_ExclusionFields,
		},
		"Override": sdk.FieldSpec{
			WireName: "override",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_ManagedRule_OverrideFields,
		},
	}

var FrontdoorFirewallPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FrontdoorFirewallPolicyConfig struct {
	CaptchaCookieExpirationInMinutes any
	CustomBlockResponseBody any
	CustomBlockResponseStatusCode any
	Enabled any
	Id any
	JsChallengeCookieExpirationInMinutes any
	Mode any
	Name any
	RedirectUrl any
	RequestBodyCheckEnabled any
	ResourceGroupName any
	SkuName any
	Tags any
	CustomRule any
	LogScrubbing any
	ManagedRule any
	Timeouts any
}

var FrontdoorFirewallPolicy = sdk.ResourceBinding{
	WireType: "azurerm_cdn_frontdoor_firewall_policy",
	Fields: sdk.FieldMap{
		"CaptchaCookieExpirationInMinutes": sdk.FieldSpec{WireName: "captcha_cookie_expiration_in_minutes"},
		"CustomBlockResponseBody": sdk.FieldSpec{WireName: "custom_block_response_body"},
		"CustomBlockResponseStatusCode": sdk.FieldSpec{WireName: "custom_block_response_status_code"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"JsChallengeCookieExpirationInMinutes": sdk.FieldSpec{WireName: "js_challenge_cookie_expiration_in_minutes"},
		"Mode": sdk.FieldSpec{WireName: "mode"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RedirectUrl": sdk.FieldSpec{WireName: "redirect_url"},
		"RequestBodyCheckEnabled": sdk.FieldSpec{WireName: "request_body_check_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SkuName": sdk.FieldSpec{WireName: "sku_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"CustomRule": sdk.FieldSpec{
			WireName: "custom_rule",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_CustomRuleFields,
		},
		"LogScrubbing": sdk.FieldSpec{
			WireName: "log_scrubbing",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_LogScrubbingFields,
		},
		"ManagedRule": sdk.FieldSpec{
			WireName: "managed_rule",
			Kind: "list",
			Fields: FrontdoorFirewallPolicy_ManagedRuleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FrontdoorFirewallPolicy_TimeoutsFields,
		},
	},
}
