// Code generated by `ubx sdk gen` from azurerm_cdn_profile. DO NOT EDIT.
package cdn

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Profile_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Profile_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ProfileConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	Sku any
	Tags any
	Timeouts any
}

var Profile = sdk.ResourceBinding{
	WireType: "azurerm_cdn_profile",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Profile_TimeoutsFields,
		},
	},
}
