// Code generated by `ubx sdk gen` from azurerm_shared_image_gallery. DO NOT EDIT.
package shared

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ImageGallery_Sharing_CommunityGallery struct {
	Eula any
	Name any
	Prefix any
	PublisherEmail any
	PublisherUri any
}

type ImageGallery_Sharing struct {
	Permission any
	CommunityGallery any
}

type ImageGallery_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ImageGallery_Sharing_CommunityGalleryFields = sdk.FieldMap{
		"Eula": sdk.FieldSpec{WireName: "eula"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Prefix": sdk.FieldSpec{WireName: "prefix"},
		"PublisherEmail": sdk.FieldSpec{WireName: "publisher_email"},
		"PublisherUri": sdk.FieldSpec{WireName: "publisher_uri"},
	}

var ImageGallery_SharingFields = sdk.FieldMap{
		"Permission": sdk.FieldSpec{WireName: "permission"},
		"CommunityGallery": sdk.FieldSpec{
			WireName: "community_gallery",
			Kind: "list",
			Fields: ImageGallery_Sharing_CommunityGalleryFields,
		},
	}

var ImageGallery_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ImageGalleryConfig struct {
	Description any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	Sharing any
	Timeouts any
}

var ImageGallery = sdk.ResourceBinding{
	WireType: "azurerm_shared_image_gallery",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Sharing": sdk.FieldSpec{
			WireName: "sharing",
			Kind: "list",
			Fields: ImageGallery_SharingFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ImageGallery_TimeoutsFields,
		},
	},
}
