// Code generated by `ubx sdk gen` from azurerm_shared_image_version. DO NOT EDIT.
package shared

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ImageVersion_TargetRegion struct {
	DiskEncryptionSetId any
	ExcludeFromLatestEnabled any
	Name any
	RegionalReplicaCount any
	StorageAccountType any
}

type ImageVersion_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ImageVersion_TargetRegionFields = sdk.FieldMap{
		"DiskEncryptionSetId": sdk.FieldSpec{WireName: "disk_encryption_set_id"},
		"ExcludeFromLatestEnabled": sdk.FieldSpec{WireName: "exclude_from_latest_enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RegionalReplicaCount": sdk.FieldSpec{WireName: "regional_replica_count"},
		"StorageAccountType": sdk.FieldSpec{WireName: "storage_account_type"},
	}

var ImageVersion_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ImageVersionConfig struct {
	BlobUri any
	DeletionOfReplicatedLocationsEnabled any
	EndOfLifeDate any
	ExcludeFromLatest any
	GalleryName any
	Id any
	ImageName any
	Location any
	ManagedImageId any
	Name any
	OsDiskSnapshotId any
	ReplicationMode any
	ResourceGroupName any
	StorageAccountId any
	Tags any
	TargetRegion any
	Timeouts any
}

var ImageVersion = sdk.ResourceBinding{
	WireType: "azurerm_shared_image_version",
	Fields: sdk.FieldMap{
		"BlobUri": sdk.FieldSpec{WireName: "blob_uri"},
		"DeletionOfReplicatedLocationsEnabled": sdk.FieldSpec{WireName: "deletion_of_replicated_locations_enabled"},
		"EndOfLifeDate": sdk.FieldSpec{WireName: "end_of_life_date"},
		"ExcludeFromLatest": sdk.FieldSpec{WireName: "exclude_from_latest"},
		"GalleryName": sdk.FieldSpec{WireName: "gallery_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ImageName": sdk.FieldSpec{WireName: "image_name"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"ManagedImageId": sdk.FieldSpec{WireName: "managed_image_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OsDiskSnapshotId": sdk.FieldSpec{WireName: "os_disk_snapshot_id"},
		"ReplicationMode": sdk.FieldSpec{WireName: "replication_mode"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TargetRegion": sdk.FieldSpec{
			WireName: "target_region",
			Kind: "list",
			Fields: ImageVersion_TargetRegionFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ImageVersion_TimeoutsFields,
		},
	},
}
