// Code generated by `ubx sdk gen` from azurerm_image. DO NOT EDIT.
package image

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Image_DataDisk struct {
	BlobUri any
	Caching any
	DiskEncryptionSetId any
	Lun any
	ManagedDiskId any
	SizeGb any
	StorageType any
}

type Image_OsDisk struct {
	BlobUri any
	Caching any
	DiskEncryptionSetId any
	ManagedDiskId any
	OsState any
	OsType any
	SizeGb any
	StorageType any
}

type Image_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Image_DataDiskFields = sdk.FieldMap{
		"BlobUri": sdk.FieldSpec{WireName: "blob_uri"},
		"Caching": sdk.FieldSpec{WireName: "caching"},
		"DiskEncryptionSetId": sdk.FieldSpec{WireName: "disk_encryption_set_id"},
		"Lun": sdk.FieldSpec{WireName: "lun"},
		"ManagedDiskId": sdk.FieldSpec{WireName: "managed_disk_id"},
		"SizeGb": sdk.FieldSpec{WireName: "size_gb"},
		"StorageType": sdk.FieldSpec{WireName: "storage_type"},
	}

var Image_OsDiskFields = sdk.FieldMap{
		"BlobUri": sdk.FieldSpec{WireName: "blob_uri"},
		"Caching": sdk.FieldSpec{WireName: "caching"},
		"DiskEncryptionSetId": sdk.FieldSpec{WireName: "disk_encryption_set_id"},
		"ManagedDiskId": sdk.FieldSpec{WireName: "managed_disk_id"},
		"OsState": sdk.FieldSpec{WireName: "os_state"},
		"OsType": sdk.FieldSpec{WireName: "os_type"},
		"SizeGb": sdk.FieldSpec{WireName: "size_gb"},
		"StorageType": sdk.FieldSpec{WireName: "storage_type"},
	}

var Image_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ImageConfig struct {
	HyperVGeneration any
	Id any
	Location any
	Name any
	ResourceGroupName any
	SourceVirtualMachineId any
	Tags any
	ZoneResilient any
	DataDisk any
	OsDisk any
	Timeouts any
}

var Image = sdk.ResourceBinding{
	WireType: "azurerm_image",
	Fields: sdk.FieldMap{
		"HyperVGeneration": sdk.FieldSpec{WireName: "hyper_v_generation"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SourceVirtualMachineId": sdk.FieldSpec{WireName: "source_virtual_machine_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"ZoneResilient": sdk.FieldSpec{WireName: "zone_resilient"},
		"DataDisk": sdk.FieldSpec{
			WireName: "data_disk",
			Kind: "list",
			Fields: Image_DataDiskFields,
		},
		"OsDisk": sdk.FieldSpec{
			WireName: "os_disk",
			Kind: "list",
			Fields: Image_OsDiskFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Image_TimeoutsFields,
		},
	},
}
