// Code generated by `ubx sdk gen` from azurerm_virtual_desktop_host_pool_registration_info. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DesktopHostPoolRegistrationInfo_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DesktopHostPoolRegistrationInfo_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DesktopHostPoolRegistrationInfoConfig struct {
	ExpirationDate any
	HostpoolId any
	Id any
	Timeouts any
}

var DesktopHostPoolRegistrationInfo = sdk.ResourceBinding{
	WireType: "azurerm_virtual_desktop_host_pool_registration_info",
	Fields: sdk.FieldMap{
		"ExpirationDate": sdk.FieldSpec{WireName: "expiration_date"},
		"HostpoolId": sdk.FieldSpec{WireName: "hostpool_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DesktopHostPoolRegistrationInfo_TimeoutsFields,
		},
	},
}
