// Code generated by `ubx sdk gen` from azurerm_virtual_desktop_scaling_plan. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DesktopScalingPlan_HostPool struct {
	HostpoolId any
	ScalingPlanEnabled any
}

type DesktopScalingPlan_Schedule struct {
	DaysOfWeek any
	Name any
	OffPeakLoadBalancingAlgorithm any
	OffPeakStartTime any
	PeakLoadBalancingAlgorithm any
	PeakStartTime any
	RampDownCapacityThresholdPercent any
	RampDownForceLogoffUsers any
	RampDownLoadBalancingAlgorithm any
	RampDownMinimumHostsPercent any
	RampDownNotificationMessage any
	RampDownStartTime any
	RampDownStopHostsWhen any
	RampDownWaitTimeMinutes any
	RampUpCapacityThresholdPercent any
	RampUpLoadBalancingAlgorithm any
	RampUpMinimumHostsPercent any
	RampUpStartTime any
}

type DesktopScalingPlan_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DesktopScalingPlan_HostPoolFields = sdk.FieldMap{
		"HostpoolId": sdk.FieldSpec{WireName: "hostpool_id"},
		"ScalingPlanEnabled": sdk.FieldSpec{WireName: "scaling_plan_enabled"},
	}

var DesktopScalingPlan_ScheduleFields = sdk.FieldMap{
		"DaysOfWeek": sdk.FieldSpec{WireName: "days_of_week"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OffPeakLoadBalancingAlgorithm": sdk.FieldSpec{WireName: "off_peak_load_balancing_algorithm"},
		"OffPeakStartTime": sdk.FieldSpec{WireName: "off_peak_start_time"},
		"PeakLoadBalancingAlgorithm": sdk.FieldSpec{WireName: "peak_load_balancing_algorithm"},
		"PeakStartTime": sdk.FieldSpec{WireName: "peak_start_time"},
		"RampDownCapacityThresholdPercent": sdk.FieldSpec{WireName: "ramp_down_capacity_threshold_percent"},
		"RampDownForceLogoffUsers": sdk.FieldSpec{WireName: "ramp_down_force_logoff_users"},
		"RampDownLoadBalancingAlgorithm": sdk.FieldSpec{WireName: "ramp_down_load_balancing_algorithm"},
		"RampDownMinimumHostsPercent": sdk.FieldSpec{WireName: "ramp_down_minimum_hosts_percent"},
		"RampDownNotificationMessage": sdk.FieldSpec{WireName: "ramp_down_notification_message"},
		"RampDownStartTime": sdk.FieldSpec{WireName: "ramp_down_start_time"},
		"RampDownStopHostsWhen": sdk.FieldSpec{WireName: "ramp_down_stop_hosts_when"},
		"RampDownWaitTimeMinutes": sdk.FieldSpec{WireName: "ramp_down_wait_time_minutes"},
		"RampUpCapacityThresholdPercent": sdk.FieldSpec{WireName: "ramp_up_capacity_threshold_percent"},
		"RampUpLoadBalancingAlgorithm": sdk.FieldSpec{WireName: "ramp_up_load_balancing_algorithm"},
		"RampUpMinimumHostsPercent": sdk.FieldSpec{WireName: "ramp_up_minimum_hosts_percent"},
		"RampUpStartTime": sdk.FieldSpec{WireName: "ramp_up_start_time"},
	}

var DesktopScalingPlan_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DesktopScalingPlanConfig struct {
	Description any
	ExclusionTag any
	FriendlyName any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	TimeZone any
	HostPool any
	Schedule any
	Timeouts any
}

var DesktopScalingPlan = sdk.ResourceBinding{
	WireType: "azurerm_virtual_desktop_scaling_plan",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"ExclusionTag": sdk.FieldSpec{WireName: "exclusion_tag"},
		"FriendlyName": sdk.FieldSpec{WireName: "friendly_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TimeZone": sdk.FieldSpec{WireName: "time_zone"},
		"HostPool": sdk.FieldSpec{
			WireName: "host_pool",
			Kind: "list",
			Fields: DesktopScalingPlan_HostPoolFields,
		},
		"Schedule": sdk.FieldSpec{
			WireName: "schedule",
			Kind: "list",
			Fields: DesktopScalingPlan_ScheduleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DesktopScalingPlan_TimeoutsFields,
		},
	},
}
