// Code generated by `ubx sdk gen` from azurerm_virtual_hub_ip. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type HubIp_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var HubIp_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type HubIpConfig struct {
	Id any
	Name any
	PrivateIpAddress any
	PrivateIpAllocationMethod any
	PublicIpAddressId any
	SubnetId any
	VirtualHubId any
	Timeouts any
}

var HubIp = sdk.ResourceBinding{
	WireType: "azurerm_virtual_hub_ip",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateIpAddress": sdk.FieldSpec{WireName: "private_ip_address"},
		"PrivateIpAllocationMethod": sdk.FieldSpec{WireName: "private_ip_allocation_method"},
		"PublicIpAddressId": sdk.FieldSpec{WireName: "public_ip_address_id"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
		"VirtualHubId": sdk.FieldSpec{WireName: "virtual_hub_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: HubIp_TimeoutsFields,
		},
	},
}
