// Code generated by `ubx sdk gen` from azurerm_virtual_hub_routing_intent. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type HubRoutingIntent_RoutingPolicy struct {
	Destinations any
	Name any
	NextHop any
}

type HubRoutingIntent_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var HubRoutingIntent_RoutingPolicyFields = sdk.FieldMap{
		"Destinations": sdk.FieldSpec{WireName: "destinations"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NextHop": sdk.FieldSpec{WireName: "next_hop"},
	}

var HubRoutingIntent_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type HubRoutingIntentConfig struct {
	Id any
	Name any
	VirtualHubId any
	RoutingPolicy any
	Timeouts any
}

var HubRoutingIntent = sdk.ResourceBinding{
	WireType: "azurerm_virtual_hub_routing_intent",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"VirtualHubId": sdk.FieldSpec{WireName: "virtual_hub_id"},
		"RoutingPolicy": sdk.FieldSpec{
			WireName: "routing_policy",
			Kind: "list",
			Fields: HubRoutingIntent_RoutingPolicyFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: HubRoutingIntent_TimeoutsFields,
		},
	},
}
