// Code generated by `ubx sdk gen` from azurerm_virtual_machine. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Machine_AdditionalCapabilities struct {
	UltraSsdEnabled any
}

type Machine_BootDiagnostics struct {
	Enabled any
	StorageUri any
}

type Machine_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Machine_OsProfile struct {
	AdminPassword any
	AdminUsername any
	ComputerName any
	CustomData any
}

type Machine_OsProfileLinuxConfig_SshKeys struct {
	KeyData any
	Path any
}

type Machine_OsProfileLinuxConfig struct {
	DisablePasswordAuthentication any
	SshKeys any
}

type Machine_OsProfileSecrets_VaultCertificates struct {
	CertificateStore any
	CertificateUrl any
}

type Machine_OsProfileSecrets struct {
	SourceVaultId any
	VaultCertificates any
}

type Machine_OsProfileWindowsConfig_AdditionalUnattendConfig struct {
	Component any
	Content any
	Pass any
	SettingName any
}

type Machine_OsProfileWindowsConfig_Winrm struct {
	CertificateUrl any
	Protocol any
}

type Machine_OsProfileWindowsConfig struct {
	EnableAutomaticUpgrades any
	ProvisionVmAgent any
	Timezone any
	AdditionalUnattendConfig any
	Winrm any
}

type Machine_Plan struct {
	Name any
	Product any
	Publisher any
}

type Machine_StorageDataDisk struct {
	Caching any
	CreateOption any
	DiskSizeGb any
	Lun any
	ManagedDiskId any
	ManagedDiskType any
	Name any
	VhdUri any
	WriteAcceleratorEnabled any
}

type Machine_StorageImageReference struct {
	Id any
	Offer any
	Publisher any
	Sku any
	Version any
}

type Machine_StorageOsDisk struct {
	Caching any
	CreateOption any
	DiskSizeGb any
	ImageUri any
	ManagedDiskId any
	ManagedDiskType any
	Name any
	OsType any
	VhdUri any
	WriteAcceleratorEnabled any
}

type Machine_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Machine_AdditionalCapabilitiesFields = sdk.FieldMap{
		"UltraSsdEnabled": sdk.FieldSpec{WireName: "ultra_ssd_enabled"},
	}

var Machine_BootDiagnosticsFields = sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"StorageUri": sdk.FieldSpec{WireName: "storage_uri"},
	}

var Machine_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Machine_OsProfileFields = sdk.FieldMap{
		"AdminPassword": sdk.FieldSpec{WireName: "admin_password"},
		"AdminUsername": sdk.FieldSpec{WireName: "admin_username"},
		"ComputerName": sdk.FieldSpec{WireName: "computer_name"},
		"CustomData": sdk.FieldSpec{WireName: "custom_data"},
	}

var Machine_OsProfileLinuxConfig_SshKeysFields = sdk.FieldMap{
		"KeyData": sdk.FieldSpec{WireName: "key_data"},
		"Path": sdk.FieldSpec{WireName: "path"},
	}

var Machine_OsProfileLinuxConfigFields = sdk.FieldMap{
		"DisablePasswordAuthentication": sdk.FieldSpec{WireName: "disable_password_authentication"},
		"SshKeys": sdk.FieldSpec{
			WireName: "ssh_keys",
			Kind: "list",
			Fields: Machine_OsProfileLinuxConfig_SshKeysFields,
		},
	}

var Machine_OsProfileSecrets_VaultCertificatesFields = sdk.FieldMap{
		"CertificateStore": sdk.FieldSpec{WireName: "certificate_store"},
		"CertificateUrl": sdk.FieldSpec{WireName: "certificate_url"},
	}

var Machine_OsProfileSecretsFields = sdk.FieldMap{
		"SourceVaultId": sdk.FieldSpec{WireName: "source_vault_id"},
		"VaultCertificates": sdk.FieldSpec{
			WireName: "vault_certificates",
			Kind: "list",
			Fields: Machine_OsProfileSecrets_VaultCertificatesFields,
		},
	}

var Machine_OsProfileWindowsConfig_AdditionalUnattendConfigFields = sdk.FieldMap{
		"Component": sdk.FieldSpec{WireName: "component"},
		"Content": sdk.FieldSpec{WireName: "content"},
		"Pass": sdk.FieldSpec{WireName: "pass"},
		"SettingName": sdk.FieldSpec{WireName: "setting_name"},
	}

var Machine_OsProfileWindowsConfig_WinrmFields = sdk.FieldMap{
		"CertificateUrl": sdk.FieldSpec{WireName: "certificate_url"},
		"Protocol": sdk.FieldSpec{WireName: "protocol"},
	}

var Machine_OsProfileWindowsConfigFields = sdk.FieldMap{
		"EnableAutomaticUpgrades": sdk.FieldSpec{WireName: "enable_automatic_upgrades"},
		"ProvisionVmAgent": sdk.FieldSpec{WireName: "provision_vm_agent"},
		"Timezone": sdk.FieldSpec{WireName: "timezone"},
		"AdditionalUnattendConfig": sdk.FieldSpec{
			WireName: "additional_unattend_config",
			Kind: "list",
			Fields: Machine_OsProfileWindowsConfig_AdditionalUnattendConfigFields,
		},
		"Winrm": sdk.FieldSpec{
			WireName: "winrm",
			Kind: "list",
			Fields: Machine_OsProfileWindowsConfig_WinrmFields,
		},
	}

var Machine_PlanFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Product": sdk.FieldSpec{WireName: "product"},
		"Publisher": sdk.FieldSpec{WireName: "publisher"},
	}

var Machine_StorageDataDiskFields = sdk.FieldMap{
		"Caching": sdk.FieldSpec{WireName: "caching"},
		"CreateOption": sdk.FieldSpec{WireName: "create_option"},
		"DiskSizeGb": sdk.FieldSpec{WireName: "disk_size_gb"},
		"Lun": sdk.FieldSpec{WireName: "lun"},
		"ManagedDiskId": sdk.FieldSpec{WireName: "managed_disk_id"},
		"ManagedDiskType": sdk.FieldSpec{WireName: "managed_disk_type"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"VhdUri": sdk.FieldSpec{WireName: "vhd_uri"},
		"WriteAcceleratorEnabled": sdk.FieldSpec{WireName: "write_accelerator_enabled"},
	}

var Machine_StorageImageReferenceFields = sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Offer": sdk.FieldSpec{WireName: "offer"},
		"Publisher": sdk.FieldSpec{WireName: "publisher"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"Version": sdk.FieldSpec{WireName: "version"},
	}

var Machine_StorageOsDiskFields = sdk.FieldMap{
		"Caching": sdk.FieldSpec{WireName: "caching"},
		"CreateOption": sdk.FieldSpec{WireName: "create_option"},
		"DiskSizeGb": sdk.FieldSpec{WireName: "disk_size_gb"},
		"ImageUri": sdk.FieldSpec{WireName: "image_uri"},
		"ManagedDiskId": sdk.FieldSpec{WireName: "managed_disk_id"},
		"ManagedDiskType": sdk.FieldSpec{WireName: "managed_disk_type"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OsType": sdk.FieldSpec{WireName: "os_type"},
		"VhdUri": sdk.FieldSpec{WireName: "vhd_uri"},
		"WriteAcceleratorEnabled": sdk.FieldSpec{WireName: "write_accelerator_enabled"},
	}

var Machine_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type MachineConfig struct {
	AvailabilitySetId any
	DeleteDataDisksOnTermination any
	DeleteOsDiskOnTermination any
	Id any
	LicenseType any
	Location any
	Name any
	NetworkInterfaceIds any
	PrimaryNetworkInterfaceId any
	ProximityPlacementGroupId any
	ResourceGroupName any
	Tags any
	VmSize any
	Zones any
	AdditionalCapabilities any
	BootDiagnostics any
	Identity any
	OsProfile any
	OsProfileLinuxConfig any
	OsProfileSecrets any
	OsProfileWindowsConfig any
	Plan any
	StorageDataDisk any
	StorageImageReference any
	StorageOsDisk any
	Timeouts any
}

var Machine = sdk.ResourceBinding{
	WireType: "azurerm_virtual_machine",
	Fields: sdk.FieldMap{
		"AvailabilitySetId": sdk.FieldSpec{WireName: "availability_set_id"},
		"DeleteDataDisksOnTermination": sdk.FieldSpec{WireName: "delete_data_disks_on_termination"},
		"DeleteOsDiskOnTermination": sdk.FieldSpec{WireName: "delete_os_disk_on_termination"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LicenseType": sdk.FieldSpec{WireName: "license_type"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkInterfaceIds": sdk.FieldSpec{WireName: "network_interface_ids"},
		"PrimaryNetworkInterfaceId": sdk.FieldSpec{WireName: "primary_network_interface_id"},
		"ProximityPlacementGroupId": sdk.FieldSpec{WireName: "proximity_placement_group_id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"VmSize": sdk.FieldSpec{WireName: "vm_size"},
		"Zones": sdk.FieldSpec{WireName: "zones"},
		"AdditionalCapabilities": sdk.FieldSpec{
			WireName: "additional_capabilities",
			Kind: "list",
			Fields: Machine_AdditionalCapabilitiesFields,
		},
		"BootDiagnostics": sdk.FieldSpec{
			WireName: "boot_diagnostics",
			Kind: "list",
			Fields: Machine_BootDiagnosticsFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Machine_IdentityFields,
		},
		"OsProfile": sdk.FieldSpec{
			WireName: "os_profile",
			Kind: "set",
			Fields: Machine_OsProfileFields,
		},
		"OsProfileLinuxConfig": sdk.FieldSpec{
			WireName: "os_profile_linux_config",
			Kind: "set",
			Fields: Machine_OsProfileLinuxConfigFields,
		},
		"OsProfileSecrets": sdk.FieldSpec{
			WireName: "os_profile_secrets",
			Kind: "list",
			Fields: Machine_OsProfileSecretsFields,
		},
		"OsProfileWindowsConfig": sdk.FieldSpec{
			WireName: "os_profile_windows_config",
			Kind: "set",
			Fields: Machine_OsProfileWindowsConfigFields,
		},
		"Plan": sdk.FieldSpec{
			WireName: "plan",
			Kind: "list",
			Fields: Machine_PlanFields,
		},
		"StorageDataDisk": sdk.FieldSpec{
			WireName: "storage_data_disk",
			Kind: "list",
			Fields: Machine_StorageDataDiskFields,
		},
		"StorageImageReference": sdk.FieldSpec{
			WireName: "storage_image_reference",
			Kind: "set",
			Fields: Machine_StorageImageReferenceFields,
		},
		"StorageOsDisk": sdk.FieldSpec{
			WireName: "storage_os_disk",
			Kind: "list",
			Fields: Machine_StorageOsDiskFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Machine_TimeoutsFields,
		},
	},
}
