// Code generated by `ubx sdk gen` from azurerm_virtual_machine_restore_point. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type MachineRestorePoint_Timeouts struct {
	Create any
	Delete any
	Read any
}

var MachineRestorePoint_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type MachineRestorePointConfig struct {
	CrashConsistencyModeEnabled any
	ExcludedDisks any
	Id any
	Name any
	VirtualMachineRestorePointCollectionId any
	Timeouts any
}

var MachineRestorePoint = sdk.ResourceBinding{
	WireType: "azurerm_virtual_machine_restore_point",
	Fields: sdk.FieldMap{
		"CrashConsistencyModeEnabled": sdk.FieldSpec{WireName: "crash_consistency_mode_enabled"},
		"ExcludedDisks": sdk.FieldSpec{WireName: "excluded_disks"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"VirtualMachineRestorePointCollectionId": sdk.FieldSpec{WireName: "virtual_machine_restore_point_collection_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: MachineRestorePoint_TimeoutsFields,
		},
	},
}
