// Code generated by `ubx sdk gen` from azurerm_virtual_machine_gallery_application_assignment. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type MachineGalleryApplicationAssignment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var MachineGalleryApplicationAssignment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type MachineGalleryApplicationAssignmentConfig struct {
	ConfigurationBlobUri any
	GalleryApplicationVersionId any
	Id any
	Order any
	Tag any
	VirtualMachineId any
	Timeouts any
}

var MachineGalleryApplicationAssignment = sdk.ResourceBinding{
	WireType: "azurerm_virtual_machine_gallery_application_assignment",
	Fields: sdk.FieldMap{
		"ConfigurationBlobUri": sdk.FieldSpec{WireName: "configuration_blob_uri"},
		"GalleryApplicationVersionId": sdk.FieldSpec{WireName: "gallery_application_version_id"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Order": sdk.FieldSpec{WireName: "order"},
		"Tag": sdk.FieldSpec{WireName: "tag"},
		"VirtualMachineId": sdk.FieldSpec{WireName: "virtual_machine_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: MachineGalleryApplicationAssignment_TimeoutsFields,
		},
	},
}
