// Code generated by `ubx sdk gen` from azurerm_virtual_network_gateway_connection. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type NetworkGatewayConnection_CustomBgpAddresses struct {
	Primary any
	Secondary any
}

type NetworkGatewayConnection_IpsecPolicy struct {
	DhGroup any
	IkeEncryption any
	IkeIntegrity any
	IpsecEncryption any
	IpsecIntegrity any
	PfsGroup any
	SaDatasize any
	SaLifetime any
}

type NetworkGatewayConnection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type NetworkGatewayConnection_TrafficSelectorPolicy struct {
	LocalAddressCidrs any
	RemoteAddressCidrs any
}

var NetworkGatewayConnection_CustomBgpAddressesFields = sdk.FieldMap{
		"Primary": sdk.FieldSpec{WireName: "primary"},
		"Secondary": sdk.FieldSpec{WireName: "secondary"},
	}

var NetworkGatewayConnection_IpsecPolicyFields = sdk.FieldMap{
		"DhGroup": sdk.FieldSpec{WireName: "dh_group"},
		"IkeEncryption": sdk.FieldSpec{WireName: "ike_encryption"},
		"IkeIntegrity": sdk.FieldSpec{WireName: "ike_integrity"},
		"IpsecEncryption": sdk.FieldSpec{WireName: "ipsec_encryption"},
		"IpsecIntegrity": sdk.FieldSpec{WireName: "ipsec_integrity"},
		"PfsGroup": sdk.FieldSpec{WireName: "pfs_group"},
		"SaDatasize": sdk.FieldSpec{WireName: "sa_datasize"},
		"SaLifetime": sdk.FieldSpec{WireName: "sa_lifetime"},
	}

var NetworkGatewayConnection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var NetworkGatewayConnection_TrafficSelectorPolicyFields = sdk.FieldMap{
		"LocalAddressCidrs": sdk.FieldSpec{WireName: "local_address_cidrs"},
		"RemoteAddressCidrs": sdk.FieldSpec{WireName: "remote_address_cidrs"},
	}

type NetworkGatewayConnectionConfig struct {
	AuthorizationKey any
	BgpEnabled any
	ConnectionMode any
	ConnectionProtocol any
	DpdTimeoutSeconds any
	EgressNatRuleIds any
	ExpressRouteCircuitId any
	ExpressRouteGatewayBypass any
	Id any
	IngressNatRuleIds any
	LocalAzureIpAddressEnabled any
	LocalNetworkGatewayId any
	Location any
	Name any
	PeerVirtualNetworkGatewayId any
	PrivateLinkFastPathEnabled any
	ResourceGroupName any
	RoutingWeight any
	SharedKey any
	Tags any
	Type any
	UsePolicyBasedTrafficSelectors any
	VirtualNetworkGatewayId any
	CustomBgpAddresses any
	IpsecPolicy any
	Timeouts any
	TrafficSelectorPolicy any
}

var NetworkGatewayConnection = sdk.ResourceBinding{
	WireType: "azurerm_virtual_network_gateway_connection",
	Fields: sdk.FieldMap{
		"AuthorizationKey": sdk.FieldSpec{WireName: "authorization_key"},
		"BgpEnabled": sdk.FieldSpec{WireName: "bgp_enabled"},
		"ConnectionMode": sdk.FieldSpec{WireName: "connection_mode"},
		"ConnectionProtocol": sdk.FieldSpec{WireName: "connection_protocol"},
		"DpdTimeoutSeconds": sdk.FieldSpec{WireName: "dpd_timeout_seconds"},
		"EgressNatRuleIds": sdk.FieldSpec{WireName: "egress_nat_rule_ids"},
		"ExpressRouteCircuitId": sdk.FieldSpec{WireName: "express_route_circuit_id"},
		"ExpressRouteGatewayBypass": sdk.FieldSpec{WireName: "express_route_gateway_bypass"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IngressNatRuleIds": sdk.FieldSpec{WireName: "ingress_nat_rule_ids"},
		"LocalAzureIpAddressEnabled": sdk.FieldSpec{WireName: "local_azure_ip_address_enabled"},
		"LocalNetworkGatewayId": sdk.FieldSpec{WireName: "local_network_gateway_id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PeerVirtualNetworkGatewayId": sdk.FieldSpec{WireName: "peer_virtual_network_gateway_id"},
		"PrivateLinkFastPathEnabled": sdk.FieldSpec{WireName: "private_link_fast_path_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"RoutingWeight": sdk.FieldSpec{WireName: "routing_weight"},
		"SharedKey": sdk.FieldSpec{WireName: "shared_key"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"UsePolicyBasedTrafficSelectors": sdk.FieldSpec{WireName: "use_policy_based_traffic_selectors"},
		"VirtualNetworkGatewayId": sdk.FieldSpec{WireName: "virtual_network_gateway_id"},
		"CustomBgpAddresses": sdk.FieldSpec{
			WireName: "custom_bgp_addresses",
			Kind: "list",
			Fields: NetworkGatewayConnection_CustomBgpAddressesFields,
		},
		"IpsecPolicy": sdk.FieldSpec{
			WireName: "ipsec_policy",
			Kind: "list",
			Fields: NetworkGatewayConnection_IpsecPolicyFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: NetworkGatewayConnection_TimeoutsFields,
		},
		"TrafficSelectorPolicy": sdk.FieldSpec{
			WireName: "traffic_selector_policy",
			Kind: "list",
			Fields: NetworkGatewayConnection_TrafficSelectorPolicyFields,
		},
	},
}
