// Code generated by `ubx sdk gen` from azurerm_virtual_network_gateway. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type NetworkGateway_BgpSettings_PeeringAddresses struct {
	ApipaAddresses any
	DefaultAddresses any
	IpConfigurationName any
	TunnelIpAddresses any
}

type NetworkGateway_BgpSettings struct {
	Asn any
	PeerWeight any
	PeeringAddresses any
}

type NetworkGateway_CustomRoute struct {
	AddressPrefixes any
}

type NetworkGateway_IpConfiguration struct {
	Name any
	PrivateIpAddressAllocation any
	PublicIpAddressId any
	SubnetId any
}

type NetworkGateway_PolicyGroup_PolicyMember struct {
	Name any
	Type any
	Value any
}

type NetworkGateway_PolicyGroup struct {
	IsDefault any
	Name any
	Priority any
	PolicyMember any
}

type NetworkGateway_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type NetworkGateway_VpnClientConfiguration_IpsecPolicy struct {
	DhGroup any
	IkeEncryption any
	IkeIntegrity any
	IpsecEncryption any
	IpsecIntegrity any
	PfsGroup any
	SaDataSizeInKilobytes any
	SaLifetimeInSeconds any
}

type NetworkGateway_VpnClientConfiguration_RadiusServer struct {
	Address any
	Score any
	Secret any
}

type NetworkGateway_VpnClientConfiguration_RevokedCertificate struct {
	Name any
	Thumbprint any
}

type NetworkGateway_VpnClientConfiguration_RootCertificate struct {
	Name any
	PublicCertData any
}

type NetworkGateway_VpnClientConfiguration_VirtualNetworkGatewayClientConnection struct {
	AddressPrefixes any
	Name any
	PolicyGroupNames any
}

type NetworkGateway_VpnClientConfiguration struct {
	AadAudience any
	AadIssuer any
	AadTenant any
	AddressSpace any
	RadiusServerAddress any
	RadiusServerSecret any
	VpnAuthTypes any
	VpnClientProtocols any
	IpsecPolicy any
	RadiusServer any
	RevokedCertificate any
	RootCertificate any
	VirtualNetworkGatewayClientConnection any
}

var NetworkGateway_BgpSettings_PeeringAddressesFields = sdk.FieldMap{
		"ApipaAddresses": sdk.FieldSpec{WireName: "apipa_addresses"},
		"DefaultAddresses": sdk.FieldSpec{WireName: "default_addresses"},
		"IpConfigurationName": sdk.FieldSpec{WireName: "ip_configuration_name"},
		"TunnelIpAddresses": sdk.FieldSpec{WireName: "tunnel_ip_addresses"},
	}

var NetworkGateway_BgpSettingsFields = sdk.FieldMap{
		"Asn": sdk.FieldSpec{WireName: "asn"},
		"PeerWeight": sdk.FieldSpec{WireName: "peer_weight"},
		"PeeringAddresses": sdk.FieldSpec{
			WireName: "peering_addresses",
			Kind: "list",
			Fields: NetworkGateway_BgpSettings_PeeringAddressesFields,
		},
	}

var NetworkGateway_CustomRouteFields = sdk.FieldMap{
		"AddressPrefixes": sdk.FieldSpec{WireName: "address_prefixes"},
	}

var NetworkGateway_IpConfigurationFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateIpAddressAllocation": sdk.FieldSpec{WireName: "private_ip_address_allocation"},
		"PublicIpAddressId": sdk.FieldSpec{WireName: "public_ip_address_id"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
	}

var NetworkGateway_PolicyGroup_PolicyMemberFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Value": sdk.FieldSpec{WireName: "value"},
	}

var NetworkGateway_PolicyGroupFields = sdk.FieldMap{
		"IsDefault": sdk.FieldSpec{WireName: "is_default"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Priority": sdk.FieldSpec{WireName: "priority"},
		"PolicyMember": sdk.FieldSpec{
			WireName: "policy_member",
			Kind: "list",
			Fields: NetworkGateway_PolicyGroup_PolicyMemberFields,
		},
	}

var NetworkGateway_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var NetworkGateway_VpnClientConfiguration_IpsecPolicyFields = sdk.FieldMap{
		"DhGroup": sdk.FieldSpec{WireName: "dh_group"},
		"IkeEncryption": sdk.FieldSpec{WireName: "ike_encryption"},
		"IkeIntegrity": sdk.FieldSpec{WireName: "ike_integrity"},
		"IpsecEncryption": sdk.FieldSpec{WireName: "ipsec_encryption"},
		"IpsecIntegrity": sdk.FieldSpec{WireName: "ipsec_integrity"},
		"PfsGroup": sdk.FieldSpec{WireName: "pfs_group"},
		"SaDataSizeInKilobytes": sdk.FieldSpec{WireName: "sa_data_size_in_kilobytes"},
		"SaLifetimeInSeconds": sdk.FieldSpec{WireName: "sa_lifetime_in_seconds"},
	}

var NetworkGateway_VpnClientConfiguration_RadiusServerFields = sdk.FieldMap{
		"Address": sdk.FieldSpec{WireName: "address"},
		"Score": sdk.FieldSpec{WireName: "score"},
		"Secret": sdk.FieldSpec{WireName: "secret"},
	}

var NetworkGateway_VpnClientConfiguration_RevokedCertificateFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Thumbprint": sdk.FieldSpec{WireName: "thumbprint"},
	}

var NetworkGateway_VpnClientConfiguration_RootCertificateFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"PublicCertData": sdk.FieldSpec{WireName: "public_cert_data"},
	}

var NetworkGateway_VpnClientConfiguration_VirtualNetworkGatewayClientConnectionFields = sdk.FieldMap{
		"AddressPrefixes": sdk.FieldSpec{WireName: "address_prefixes"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PolicyGroupNames": sdk.FieldSpec{WireName: "policy_group_names"},
	}

var NetworkGateway_VpnClientConfigurationFields = sdk.FieldMap{
		"AadAudience": sdk.FieldSpec{WireName: "aad_audience"},
		"AadIssuer": sdk.FieldSpec{WireName: "aad_issuer"},
		"AadTenant": sdk.FieldSpec{WireName: "aad_tenant"},
		"AddressSpace": sdk.FieldSpec{WireName: "address_space"},
		"RadiusServerAddress": sdk.FieldSpec{WireName: "radius_server_address"},
		"RadiusServerSecret": sdk.FieldSpec{WireName: "radius_server_secret"},
		"VpnAuthTypes": sdk.FieldSpec{WireName: "vpn_auth_types"},
		"VpnClientProtocols": sdk.FieldSpec{WireName: "vpn_client_protocols"},
		"IpsecPolicy": sdk.FieldSpec{
			WireName: "ipsec_policy",
			Kind: "list",
			Fields: NetworkGateway_VpnClientConfiguration_IpsecPolicyFields,
		},
		"RadiusServer": sdk.FieldSpec{
			WireName: "radius_server",
			Kind: "list",
			Fields: NetworkGateway_VpnClientConfiguration_RadiusServerFields,
		},
		"RevokedCertificate": sdk.FieldSpec{
			WireName: "revoked_certificate",
			Kind: "set",
			Fields: NetworkGateway_VpnClientConfiguration_RevokedCertificateFields,
		},
		"RootCertificate": sdk.FieldSpec{
			WireName: "root_certificate",
			Kind: "set",
			Fields: NetworkGateway_VpnClientConfiguration_RootCertificateFields,
		},
		"VirtualNetworkGatewayClientConnection": sdk.FieldSpec{
			WireName: "virtual_network_gateway_client_connection",
			Kind: "list",
			Fields: NetworkGateway_VpnClientConfiguration_VirtualNetworkGatewayClientConnectionFields,
		},
	}

type NetworkGatewayConfig struct {
	ActiveActive any
	BgpEnabled any
	BgpRouteTranslationForNatEnabled any
	DefaultLocalNetworkGatewayId any
	DnsForwardingEnabled any
	EdgeZone any
	Generation any
	Id any
	IpSecReplayProtectionEnabled any
	Location any
	MaximumScaleUnit any
	MinimumScaleUnit any
	Name any
	PrivateIpAddressEnabled any
	RemoteVnetTrafficEnabled any
	ResourceGroupName any
	Sku any
	Tags any
	Type any
	VirtualWanTrafficEnabled any
	VpnType any
	BgpSettings any
	CustomRoute any
	IpConfiguration any
	PolicyGroup any
	Timeouts any
	VpnClientConfiguration any
}

var NetworkGateway = sdk.ResourceBinding{
	WireType: "azurerm_virtual_network_gateway",
	Fields: sdk.FieldMap{
		"ActiveActive": sdk.FieldSpec{WireName: "active_active"},
		"BgpEnabled": sdk.FieldSpec{WireName: "bgp_enabled"},
		"BgpRouteTranslationForNatEnabled": sdk.FieldSpec{WireName: "bgp_route_translation_for_nat_enabled"},
		"DefaultLocalNetworkGatewayId": sdk.FieldSpec{WireName: "default_local_network_gateway_id"},
		"DnsForwardingEnabled": sdk.FieldSpec{WireName: "dns_forwarding_enabled"},
		"EdgeZone": sdk.FieldSpec{WireName: "edge_zone"},
		"Generation": sdk.FieldSpec{WireName: "generation"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IpSecReplayProtectionEnabled": sdk.FieldSpec{WireName: "ip_sec_replay_protection_enabled"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MaximumScaleUnit": sdk.FieldSpec{WireName: "maximum_scale_unit"},
		"MinimumScaleUnit": sdk.FieldSpec{WireName: "minimum_scale_unit"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateIpAddressEnabled": sdk.FieldSpec{WireName: "private_ip_address_enabled"},
		"RemoteVnetTrafficEnabled": sdk.FieldSpec{WireName: "remote_vnet_traffic_enabled"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Sku": sdk.FieldSpec{WireName: "sku"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"VirtualWanTrafficEnabled": sdk.FieldSpec{WireName: "virtual_wan_traffic_enabled"},
		"VpnType": sdk.FieldSpec{WireName: "vpn_type"},
		"BgpSettings": sdk.FieldSpec{
			WireName: "bgp_settings",
			Kind: "list",
			Fields: NetworkGateway_BgpSettingsFields,
		},
		"CustomRoute": sdk.FieldSpec{
			WireName: "custom_route",
			Kind: "list",
			Fields: NetworkGateway_CustomRouteFields,
		},
		"IpConfiguration": sdk.FieldSpec{
			WireName: "ip_configuration",
			Kind: "list",
			Fields: NetworkGateway_IpConfigurationFields,
		},
		"PolicyGroup": sdk.FieldSpec{
			WireName: "policy_group",
			Kind: "list",
			Fields: NetworkGateway_PolicyGroupFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: NetworkGateway_TimeoutsFields,
		},
		"VpnClientConfiguration": sdk.FieldSpec{
			WireName: "vpn_client_configuration",
			Kind: "list",
			Fields: NetworkGateway_VpnClientConfigurationFields,
		},
	},
}
