// Code generated by `ubx sdk gen` from azurerm_virtual_network. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Network_Subnet_Delegation_ServiceDelegation struct {
	Actions any
	Name any
}

type Network_Subnet_Delegation struct {
	Name any
	ServiceDelegation any
}

type Network_Subnet_ServiceEndpoint struct {
	NetworkIdentifier any
	Service any
}

type Network_Subnet struct {
	AddressPrefixes any
	DefaultOutboundAccessEnabled any
	Delegation any
	Id any
	Name any
	PrivateEndpointNetworkPolicies any
	PrivateLinkServiceNetworkPoliciesEnabled any
	RouteTableId any
	SecurityGroup any
	ServiceEndpoint any
	ServiceEndpointPolicyIds any
}

type Network_DdosProtectionPlan struct {
	Enable any
	Id any
}

type Network_Encryption struct {
	Enforcement any
}

type Network_IpAddressPool struct {
	AllocatedIpAddressPrefixes any
	Id any
	NumberOfIpAddresses any
}

type Network_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Network_Subnet_Delegation_ServiceDelegationFields = sdk.FieldMap{
		"Actions": sdk.FieldSpec{WireName: "actions"},
		"Name": sdk.FieldSpec{WireName: "name"},
	}

var Network_Subnet_DelegationFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"ServiceDelegation": sdk.FieldSpec{
			WireName: "service_delegation",
			Kind: "list",
			Fields: Network_Subnet_Delegation_ServiceDelegationFields,
		},
	}

var Network_Subnet_ServiceEndpointFields = sdk.FieldMap{
		"NetworkIdentifier": sdk.FieldSpec{WireName: "network_identifier"},
		"Service": sdk.FieldSpec{WireName: "service"},
	}

var Network_SubnetFields = sdk.FieldMap{
		"AddressPrefixes": sdk.FieldSpec{WireName: "address_prefixes"},
		"DefaultOutboundAccessEnabled": sdk.FieldSpec{WireName: "default_outbound_access_enabled"},
		"Delegation": sdk.FieldSpec{
			WireName: "delegation",
			Kind: "list",
			Fields: Network_Subnet_DelegationFields,
		},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateEndpointNetworkPolicies": sdk.FieldSpec{WireName: "private_endpoint_network_policies"},
		"PrivateLinkServiceNetworkPoliciesEnabled": sdk.FieldSpec{WireName: "private_link_service_network_policies_enabled"},
		"RouteTableId": sdk.FieldSpec{WireName: "route_table_id"},
		"SecurityGroup": sdk.FieldSpec{WireName: "security_group"},
		"ServiceEndpoint": sdk.FieldSpec{
			WireName: "service_endpoint",
			Kind: "list",
			Fields: Network_Subnet_ServiceEndpointFields,
		},
		"ServiceEndpointPolicyIds": sdk.FieldSpec{WireName: "service_endpoint_policy_ids"},
	}

var Network_DdosProtectionPlanFields = sdk.FieldMap{
		"Enable": sdk.FieldSpec{WireName: "enable"},
		"Id": sdk.FieldSpec{WireName: "id"},
	}

var Network_EncryptionFields = sdk.FieldMap{
		"Enforcement": sdk.FieldSpec{WireName: "enforcement"},
	}

var Network_IpAddressPoolFields = sdk.FieldMap{
		"AllocatedIpAddressPrefixes": sdk.FieldSpec{WireName: "allocated_ip_address_prefixes"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"NumberOfIpAddresses": sdk.FieldSpec{WireName: "number_of_ip_addresses"},
	}

var Network_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type NetworkConfig struct {
	AddressSpace any
	BgpCommunity any
	DnsServers any
	EdgeZone any
	FlowTimeoutInMinutes any
	Id any
	Location any
	Name any
	PrivateEndpointVnetPolicies any
	ResourceGroupName any
	Subnet any
	Tags any
	DdosProtectionPlan any
	Encryption any
	IpAddressPool any
	Timeouts any
}

var Network = sdk.ResourceBinding{
	WireType: "azurerm_virtual_network",
	Fields: sdk.FieldMap{
		"AddressSpace": sdk.FieldSpec{WireName: "address_space"},
		"BgpCommunity": sdk.FieldSpec{WireName: "bgp_community"},
		"DnsServers": sdk.FieldSpec{WireName: "dns_servers"},
		"EdgeZone": sdk.FieldSpec{WireName: "edge_zone"},
		"FlowTimeoutInMinutes": sdk.FieldSpec{WireName: "flow_timeout_in_minutes"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrivateEndpointVnetPolicies": sdk.FieldSpec{WireName: "private_endpoint_vnet_policies"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Subnet": sdk.FieldSpec{
			WireName: "subnet",
			Kind: "set",
			Fields: Network_SubnetFields,
		},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"DdosProtectionPlan": sdk.FieldSpec{
			WireName: "ddos_protection_plan",
			Kind: "list",
			Fields: Network_DdosProtectionPlanFields,
		},
		"Encryption": sdk.FieldSpec{
			WireName: "encryption",
			Kind: "list",
			Fields: Network_EncryptionFields,
		},
		"IpAddressPool": sdk.FieldSpec{
			WireName: "ip_address_pool",
			Kind: "list",
			Fields: Network_IpAddressPoolFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Network_TimeoutsFields,
		},
	},
}
