// Code generated by `ubx sdk gen` from azurerm_virtual_network_peering. DO NOT EDIT.
package virtual

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type NetworkPeering_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var NetworkPeering_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type NetworkPeeringConfig struct {
	AllowForwardedTraffic any
	AllowGatewayTransit any
	AllowVirtualNetworkAccess any
	Id any
	LocalSubnetNames any
	Name any
	OnlyIpv6PeeringEnabled any
	PeerCompleteVirtualNetworksEnabled any
	RemoteSubnetNames any
	RemoteVirtualNetworkId any
	ResourceGroupName any
	Triggers any
	UseRemoteGateways any
	VirtualNetworkName any
	Timeouts any
}

var NetworkPeering = sdk.ResourceBinding{
	WireType: "azurerm_virtual_network_peering",
	Fields: sdk.FieldMap{
		"AllowForwardedTraffic": sdk.FieldSpec{WireName: "allow_forwarded_traffic"},
		"AllowGatewayTransit": sdk.FieldSpec{WireName: "allow_gateway_transit"},
		"AllowVirtualNetworkAccess": sdk.FieldSpec{WireName: "allow_virtual_network_access"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LocalSubnetNames": sdk.FieldSpec{WireName: "local_subnet_names"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"OnlyIpv6PeeringEnabled": sdk.FieldSpec{WireName: "only_ipv6_peering_enabled"},
		"PeerCompleteVirtualNetworksEnabled": sdk.FieldSpec{WireName: "peer_complete_virtual_networks_enabled"},
		"RemoteSubnetNames": sdk.FieldSpec{WireName: "remote_subnet_names"},
		"RemoteVirtualNetworkId": sdk.FieldSpec{WireName: "remote_virtual_network_id"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Triggers": sdk.FieldSpec{WireName: "triggers"},
		"UseRemoteGateways": sdk.FieldSpec{WireName: "use_remote_gateways"},
		"VirtualNetworkName": sdk.FieldSpec{WireName: "virtual_network_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: NetworkPeering_TimeoutsFields,
		},
	},
}
