// Code generated by `ubx sdk gen` from azurerm_automation_connection. DO NOT EDIT.
package automation

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Connection_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Connection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ConnectionConfig struct {
	AutomationAccountName any
	Description any
	Id any
	Name any
	ResourceGroupName any
	Type any
	Values any
	Timeouts any
}

var Connection = sdk.ResourceBinding{
	WireType: "azurerm_automation_connection",
	Fields: sdk.FieldMap{
		"AutomationAccountName": sdk.FieldSpec{WireName: "automation_account_name"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Type": sdk.FieldSpec{WireName: "type"},
		"Values": sdk.FieldSpec{WireName: "values"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Connection_TimeoutsFields,
		},
	},
}
