// Code generated by `ubx sdk gen` from azurerm_automation_connection_type. DO NOT EDIT.
package automation

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ConnectionType_Field struct {
	IsEncrypted any
	IsOptional any
	Name any
	Type any
}

type ConnectionType_Timeouts struct {
	Create any
	Delete any
	Read any
}

var ConnectionType_FieldFields = sdk.FieldMap{
		"IsEncrypted": sdk.FieldSpec{WireName: "is_encrypted"},
		"IsOptional": sdk.FieldSpec{WireName: "is_optional"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var ConnectionType_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type ConnectionTypeConfig struct {
	AutomationAccountName any
	Id any
	IsGlobal any
	Name any
	ResourceGroupName any
	Field any
	Timeouts any
}

var ConnectionType = sdk.ResourceBinding{
	WireType: "azurerm_automation_connection_type",
	Fields: sdk.FieldMap{
		"AutomationAccountName": sdk.FieldSpec{WireName: "automation_account_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"IsGlobal": sdk.FieldSpec{WireName: "is_global"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Field": sdk.FieldSpec{
			WireName: "field",
			Kind: "list",
			Fields: ConnectionType_FieldFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ConnectionType_TimeoutsFields,
		},
	},
}
