// Code generated by `ubx sdk gen` from azurerm_automation_python3_package. DO NOT EDIT.
package automation

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Python3Package_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Python3Package_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type Python3PackageConfig struct {
	AutomationAccountName any
	ContentUri any
	ContentVersion any
	HashAlgorithm any
	HashValue any
	Id any
	Name any
	ResourceGroupName any
	Tags any
	Timeouts any
}

var Python3Package = sdk.ResourceBinding{
	WireType: "azurerm_automation_python3_package",
	Fields: sdk.FieldMap{
		"AutomationAccountName": sdk.FieldSpec{WireName: "automation_account_name"},
		"ContentUri": sdk.FieldSpec{WireName: "content_uri"},
		"ContentVersion": sdk.FieldSpec{WireName: "content_version"},
		"HashAlgorithm": sdk.FieldSpec{WireName: "hash_algorithm"},
		"HashValue": sdk.FieldSpec{WireName: "hash_value"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Python3Package_TimeoutsFields,
		},
	},
}
