// Code generated by `ubx sdk gen` from azurerm_automation_runtime_environment. DO NOT EDIT.
package automation

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type RuntimeEnvironment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var RuntimeEnvironment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type RuntimeEnvironmentConfig struct {
	AutomationAccountId any
	Description any
	Id any
	Location any
	Name any
	RuntimeDefaultPackages any
	RuntimeLanguage any
	RuntimeVersion any
	Tags any
	Timeouts any
}

var RuntimeEnvironment = sdk.ResourceBinding{
	WireType: "azurerm_automation_runtime_environment",
	Fields: sdk.FieldMap{
		"AutomationAccountId": sdk.FieldSpec{WireName: "automation_account_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RuntimeDefaultPackages": sdk.FieldSpec{WireName: "runtime_default_packages"},
		"RuntimeLanguage": sdk.FieldSpec{WireName: "runtime_language"},
		"RuntimeVersion": sdk.FieldSpec{WireName: "runtime_version"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: RuntimeEnvironment_TimeoutsFields,
		},
	},
}
