// Code generated by `ubx sdk gen` from azurerm_vmware_netapp_volume_attachment. DO NOT EDIT.
package vmware

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type NetappVolumeAttachment_Timeouts struct {
	Create any
	Delete any
	Read any
}

var NetappVolumeAttachment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type NetappVolumeAttachmentConfig struct {
	Id any
	Name any
	NetappVolumeId any
	VmwareClusterId any
	Timeouts any
}

var NetappVolumeAttachment = sdk.ResourceBinding{
	WireType: "azurerm_vmware_netapp_volume_attachment",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetappVolumeId": sdk.FieldSpec{WireName: "netapp_volume_id"},
		"VmwareClusterId": sdk.FieldSpec{WireName: "vmware_cluster_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: NetappVolumeAttachment_TimeoutsFields,
		},
	},
}
