// Code generated by `ubx sdk gen` from azurerm_vmware_private_cloud. DO NOT EDIT.
package vmware

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type PrivateCloud_ManagementCluster struct {
	Hosts any
	Id any
	Size any
}

type PrivateCloud_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var PrivateCloud_ManagementClusterFields = sdk.FieldMap{
		"Hosts": sdk.FieldSpec{WireName: "hosts"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Size": sdk.FieldSpec{WireName: "size"},
	}

var PrivateCloud_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type PrivateCloudConfig struct {
	Id any
	InternetConnectionEnabled any
	Location any
	Name any
	NetworkSubnetCidr any
	NsxtPassword any
	ResourceGroupName any
	SkuName any
	Tags any
	VcenterPassword any
	ManagementCluster any
	Timeouts any
}

var PrivateCloud = sdk.ResourceBinding{
	WireType: "azurerm_vmware_private_cloud",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"InternetConnectionEnabled": sdk.FieldSpec{WireName: "internet_connection_enabled"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NetworkSubnetCidr": sdk.FieldSpec{WireName: "network_subnet_cidr"},
		"NsxtPassword": sdk.FieldSpec{WireName: "nsxt_password"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"SkuName": sdk.FieldSpec{WireName: "sku_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"VcenterPassword": sdk.FieldSpec{WireName: "vcenter_password"},
		"ManagementCluster": sdk.FieldSpec{
			WireName: "management_cluster",
			Kind: "list",
			Fields: PrivateCloud_ManagementClusterFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PrivateCloud_TimeoutsFields,
		},
	},
}
