// Code generated by `ubx sdk gen` from azurerm_ai_foundry. DO NOT EDIT.
package ai

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Foundry_Encryption struct {
	KeyId any
	KeyVaultId any
	UserAssignedIdentityId any
}

type Foundry_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Foundry_ManagedNetwork struct {
	IsolationMode any
}

type Foundry_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Foundry_EncryptionFields = sdk.FieldMap{
		"KeyId": sdk.FieldSpec{WireName: "key_id"},
		"KeyVaultId": sdk.FieldSpec{WireName: "key_vault_id"},
		"UserAssignedIdentityId": sdk.FieldSpec{WireName: "user_assigned_identity_id"},
	}

var Foundry_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Foundry_ManagedNetworkFields = sdk.FieldMap{
		"IsolationMode": sdk.FieldSpec{WireName: "isolation_mode"},
	}

var Foundry_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FoundryConfig struct {
	ApplicationInsightsId any
	ContainerRegistryId any
	Description any
	FriendlyName any
	HighBusinessImpactEnabled any
	Id any
	KeyVaultId any
	Location any
	Name any
	PrimaryUserAssignedIdentity any
	PublicNetworkAccess any
	ResourceGroupName any
	StorageAccountId any
	Tags any
	Encryption any
	Identity any
	ManagedNetwork any
	Timeouts any
}

var Foundry = sdk.ResourceBinding{
	WireType: "azurerm_ai_foundry",
	Fields: sdk.FieldMap{
		"ApplicationInsightsId": sdk.FieldSpec{WireName: "application_insights_id"},
		"ContainerRegistryId": sdk.FieldSpec{WireName: "container_registry_id"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"FriendlyName": sdk.FieldSpec{WireName: "friendly_name"},
		"HighBusinessImpactEnabled": sdk.FieldSpec{WireName: "high_business_impact_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"KeyVaultId": sdk.FieldSpec{WireName: "key_vault_id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"PrimaryUserAssignedIdentity": sdk.FieldSpec{WireName: "primary_user_assigned_identity"},
		"PublicNetworkAccess": sdk.FieldSpec{WireName: "public_network_access"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"StorageAccountId": sdk.FieldSpec{WireName: "storage_account_id"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Encryption": sdk.FieldSpec{
			WireName: "encryption",
			Kind: "list",
			Fields: Foundry_EncryptionFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Foundry_IdentityFields,
		},
		"ManagedNetwork": sdk.FieldSpec{
			WireName: "managed_network",
			Kind: "list",
			Fields: Foundry_ManagedNetworkFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Foundry_TimeoutsFields,
		},
	},
}
