// Code generated by `ubx sdk gen` from azurerm_web_pubsub_hub. DO NOT EDIT.
package web

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type PubsubHub_EventHandler_Auth struct {
	ManagedIdentityId any
}

type PubsubHub_EventHandler struct {
	SystemEvents any
	UrlTemplate any
	UserEventPattern any
	Auth any
}

type PubsubHub_EventListener struct {
	EventhubName any
	EventhubNamespaceName any
	SystemEventNameFilter any
	UserEventNameFilter any
}

type PubsubHub_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var PubsubHub_EventHandler_AuthFields = sdk.FieldMap{
		"ManagedIdentityId": sdk.FieldSpec{WireName: "managed_identity_id"},
	}

var PubsubHub_EventHandlerFields = sdk.FieldMap{
		"SystemEvents": sdk.FieldSpec{WireName: "system_events"},
		"UrlTemplate": sdk.FieldSpec{WireName: "url_template"},
		"UserEventPattern": sdk.FieldSpec{WireName: "user_event_pattern"},
		"Auth": sdk.FieldSpec{
			WireName: "auth",
			Kind: "list",
			Fields: PubsubHub_EventHandler_AuthFields,
		},
	}

var PubsubHub_EventListenerFields = sdk.FieldMap{
		"EventhubName": sdk.FieldSpec{WireName: "eventhub_name"},
		"EventhubNamespaceName": sdk.FieldSpec{WireName: "eventhub_namespace_name"},
		"SystemEventNameFilter": sdk.FieldSpec{WireName: "system_event_name_filter"},
		"UserEventNameFilter": sdk.FieldSpec{WireName: "user_event_name_filter"},
	}

var PubsubHub_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type PubsubHubConfig struct {
	AnonymousConnectionsEnabled any
	Id any
	Name any
	WebPubsubId any
	EventHandler any
	EventListener any
	Timeouts any
}

var PubsubHub = sdk.ResourceBinding{
	WireType: "azurerm_web_pubsub_hub",
	Fields: sdk.FieldMap{
		"AnonymousConnectionsEnabled": sdk.FieldSpec{WireName: "anonymous_connections_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"WebPubsubId": sdk.FieldSpec{WireName: "web_pubsub_id"},
		"EventHandler": sdk.FieldSpec{
			WireName: "event_handler",
			Kind: "list",
			Fields: PubsubHub_EventHandlerFields,
		},
		"EventListener": sdk.FieldSpec{
			WireName: "event_listener",
			Kind: "list",
			Fields: PubsubHub_EventListenerFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PubsubHub_TimeoutsFields,
		},
	},
}
