// Code generated by `ubx sdk gen` from azurerm_web_pubsub_custom_domain. DO NOT EDIT.
package web

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type PubsubCustomDomain_Timeouts struct {
	Create any
	Delete any
	Read any
}

var PubsubCustomDomain_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type PubsubCustomDomainConfig struct {
	DomainName any
	Id any
	Name any
	WebPubsubCustomCertificateId any
	WebPubsubId any
	Timeouts any
}

var PubsubCustomDomain = sdk.ResourceBinding{
	WireType: "azurerm_web_pubsub_custom_domain",
	Fields: sdk.FieldMap{
		"DomainName": sdk.FieldSpec{WireName: "domain_name"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"WebPubsubCustomCertificateId": sdk.FieldSpec{WireName: "web_pubsub_custom_certificate_id"},
		"WebPubsubId": sdk.FieldSpec{WireName: "web_pubsub_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PubsubCustomDomain_TimeoutsFields,
		},
	},
}
