// Code generated by `ubx sdk gen` from azurerm_sentinel_alert_rule_fusion. DO NOT EDIT.
package sentinel

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AlertRuleFusion_Source_SubType struct {
	Enabled any
	Name any
	SeveritiesAllowed any
}

type AlertRuleFusion_Source struct {
	Enabled any
	Name any
	SubType any
}

type AlertRuleFusion_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AlertRuleFusion_Source_SubTypeFields = sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SeveritiesAllowed": sdk.FieldSpec{WireName: "severities_allowed"},
	}

var AlertRuleFusion_SourceFields = sdk.FieldMap{
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SubType": sdk.FieldSpec{
			WireName: "sub_type",
			Kind: "list",
			Fields: AlertRuleFusion_Source_SubTypeFields,
		},
	}

var AlertRuleFusion_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AlertRuleFusionConfig struct {
	AlertRuleTemplateGuid any
	Enabled any
	Id any
	LogAnalyticsWorkspaceId any
	Source any
	Timeouts any
}

var AlertRuleFusion = sdk.ResourceBinding{
	WireType: "azurerm_sentinel_alert_rule_fusion",
	Fields: sdk.FieldMap{
		"AlertRuleTemplateGuid": sdk.FieldSpec{WireName: "alert_rule_template_guid"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LogAnalyticsWorkspaceId": sdk.FieldSpec{WireName: "log_analytics_workspace_id"},
		"Source": sdk.FieldSpec{
			WireName: "source",
			Kind: "list",
			Fields: AlertRuleFusion_SourceFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AlertRuleFusion_TimeoutsFields,
		},
	},
}
