// Code generated by `ubx sdk gen` from azurerm_sentinel_data_connector_office_365. DO NOT EDIT.
package sentinel

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DataConnectorOffice365_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DataConnectorOffice365_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DataConnectorOffice365Config struct {
	ExchangeEnabled any
	Id any
	LogAnalyticsWorkspaceId any
	Name any
	SharepointEnabled any
	TeamsEnabled any
	TenantId any
	Timeouts any
}

var DataConnectorOffice365 = sdk.ResourceBinding{
	WireType: "azurerm_sentinel_data_connector_office_365",
	Fields: sdk.FieldMap{
		"ExchangeEnabled": sdk.FieldSpec{WireName: "exchange_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LogAnalyticsWorkspaceId": sdk.FieldSpec{WireName: "log_analytics_workspace_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SharepointEnabled": sdk.FieldSpec{WireName: "sharepoint_enabled"},
		"TeamsEnabled": sdk.FieldSpec{WireName: "teams_enabled"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DataConnectorOffice365_TimeoutsFields,
		},
	},
}
