// Code generated by `ubx sdk gen` from azurerm_sentinel_data_connector_microsoft_cloud_app_security. DO NOT EDIT.
package sentinel

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DataConnectorMicrosoftCloudAppSecurity_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var DataConnectorMicrosoftCloudAppSecurity_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type DataConnectorMicrosoftCloudAppSecurityConfig struct {
	AlertsEnabled any
	DiscoveryLogsEnabled any
	Id any
	LogAnalyticsWorkspaceId any
	Name any
	TenantId any
	Timeouts any
}

var DataConnectorMicrosoftCloudAppSecurity = sdk.ResourceBinding{
	WireType: "azurerm_sentinel_data_connector_microsoft_cloud_app_security",
	Fields: sdk.FieldMap{
		"AlertsEnabled": sdk.FieldSpec{WireName: "alerts_enabled"},
		"DiscoveryLogsEnabled": sdk.FieldSpec{WireName: "discovery_logs_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LogAnalyticsWorkspaceId": sdk.FieldSpec{WireName: "log_analytics_workspace_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DataConnectorMicrosoftCloudAppSecurity_TimeoutsFields,
		},
	},
}
