// Code generated by `ubx sdk gen` from azurerm_sentinel_data_connector_azure_advanced_threat_protection. DO NOT EDIT.
package sentinel

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type DataConnectorAzureAdvancedThreatProtection_Timeouts struct {
	Create any
	Delete any
	Read any
}

var DataConnectorAzureAdvancedThreatProtection_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type DataConnectorAzureAdvancedThreatProtectionConfig struct {
	Id any
	LogAnalyticsWorkspaceId any
	Name any
	TenantId any
	Timeouts any
}

var DataConnectorAzureAdvancedThreatProtection = sdk.ResourceBinding{
	WireType: "azurerm_sentinel_data_connector_azure_advanced_threat_protection",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"LogAnalyticsWorkspaceId": sdk.FieldSpec{WireName: "log_analytics_workspace_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: DataConnectorAzureAdvancedThreatProtection_TimeoutsFields,
		},
	},
}
