// Code generated by `ubx sdk gen` from azurerm_servicebus_queue_authorization_rule. DO NOT EDIT.
package servicebus

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type QueueAuthorizationRule_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var QueueAuthorizationRule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type QueueAuthorizationRuleConfig struct {
	Id any
	Listen any
	Manage any
	Name any
	QueueId any
	Send any
	Timeouts any
}

var QueueAuthorizationRule = sdk.ResourceBinding{
	WireType: "azurerm_servicebus_queue_authorization_rule",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Listen": sdk.FieldSpec{WireName: "listen"},
		"Manage": sdk.FieldSpec{WireName: "manage"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"QueueId": sdk.FieldSpec{WireName: "queue_id"},
		"Send": sdk.FieldSpec{WireName: "send"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: QueueAuthorizationRule_TimeoutsFields,
		},
	},
}
