// Code generated by `ubx sdk gen` from azurerm_servicebus_queue. DO NOT EDIT.
package servicebus

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Queue_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Queue_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type QueueConfig struct {
	AutoDeleteOnIdle any
	BatchedOperationsEnabled any
	DeadLetteringOnMessageExpiration any
	DefaultMessageTtl any
	DuplicateDetectionHistoryTimeWindow any
	ExpressEnabled any
	ForwardDeadLetteredMessagesTo any
	ForwardTo any
	Id any
	LockDuration any
	MaxDeliveryCount any
	MaxMessageSizeInKilobytes any
	MaxSizeInMegabytes any
	Name any
	NamespaceId any
	PartitioningEnabled any
	RequiresDuplicateDetection any
	RequiresSession any
	Status any
	Timeouts any
}

var Queue = sdk.ResourceBinding{
	WireType: "azurerm_servicebus_queue",
	Fields: sdk.FieldMap{
		"AutoDeleteOnIdle": sdk.FieldSpec{WireName: "auto_delete_on_idle"},
		"BatchedOperationsEnabled": sdk.FieldSpec{WireName: "batched_operations_enabled"},
		"DeadLetteringOnMessageExpiration": sdk.FieldSpec{WireName: "dead_lettering_on_message_expiration"},
		"DefaultMessageTtl": sdk.FieldSpec{WireName: "default_message_ttl"},
		"DuplicateDetectionHistoryTimeWindow": sdk.FieldSpec{WireName: "duplicate_detection_history_time_window"},
		"ExpressEnabled": sdk.FieldSpec{WireName: "express_enabled"},
		"ForwardDeadLetteredMessagesTo": sdk.FieldSpec{WireName: "forward_dead_lettered_messages_to"},
		"ForwardTo": sdk.FieldSpec{WireName: "forward_to"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LockDuration": sdk.FieldSpec{WireName: "lock_duration"},
		"MaxDeliveryCount": sdk.FieldSpec{WireName: "max_delivery_count"},
		"MaxMessageSizeInKilobytes": sdk.FieldSpec{WireName: "max_message_size_in_kilobytes"},
		"MaxSizeInMegabytes": sdk.FieldSpec{WireName: "max_size_in_megabytes"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"NamespaceId": sdk.FieldSpec{WireName: "namespace_id"},
		"PartitioningEnabled": sdk.FieldSpec{WireName: "partitioning_enabled"},
		"RequiresDuplicateDetection": sdk.FieldSpec{WireName: "requires_duplicate_detection"},
		"RequiresSession": sdk.FieldSpec{WireName: "requires_session"},
		"Status": sdk.FieldSpec{WireName: "status"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Queue_TimeoutsFields,
		},
	},
}
