// Code generated by `ubx sdk gen` from azurerm_mssql_job_step. DO NOT EDIT.
package mssql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type JobStep_OutputTarget struct {
	JobCredentialId any
	MssqlDatabaseId any
	SchemaName any
	TableName any
}

type JobStep_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var JobStep_OutputTargetFields = sdk.FieldMap{
		"JobCredentialId": sdk.FieldSpec{WireName: "job_credential_id"},
		"MssqlDatabaseId": sdk.FieldSpec{WireName: "mssql_database_id"},
		"SchemaName": sdk.FieldSpec{WireName: "schema_name"},
		"TableName": sdk.FieldSpec{WireName: "table_name"},
	}

var JobStep_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type JobStepConfig struct {
	Id any
	InitialRetryIntervalSeconds any
	JobCredentialId any
	JobId any
	JobStepIndex any
	JobTargetGroupId any
	MaximumRetryIntervalSeconds any
	Name any
	RetryAttempts any
	RetryIntervalBackoffMultiplier any
	SqlScript any
	TimeoutSeconds any
	OutputTarget any
	Timeouts any
}

var JobStep = sdk.ResourceBinding{
	WireType: "azurerm_mssql_job_step",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"InitialRetryIntervalSeconds": sdk.FieldSpec{WireName: "initial_retry_interval_seconds"},
		"JobCredentialId": sdk.FieldSpec{WireName: "job_credential_id"},
		"JobId": sdk.FieldSpec{WireName: "job_id"},
		"JobStepIndex": sdk.FieldSpec{WireName: "job_step_index"},
		"JobTargetGroupId": sdk.FieldSpec{WireName: "job_target_group_id"},
		"MaximumRetryIntervalSeconds": sdk.FieldSpec{WireName: "maximum_retry_interval_seconds"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RetryAttempts": sdk.FieldSpec{WireName: "retry_attempts"},
		"RetryIntervalBackoffMultiplier": sdk.FieldSpec{WireName: "retry_interval_backoff_multiplier"},
		"SqlScript": sdk.FieldSpec{WireName: "sql_script"},
		"TimeoutSeconds": sdk.FieldSpec{WireName: "timeout_seconds"},
		"OutputTarget": sdk.FieldSpec{
			WireName: "output_target",
			Kind: "list",
			Fields: JobStep_OutputTargetFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: JobStep_TimeoutsFields,
		},
	},
}
