// Code generated by `ubx sdk gen` from azurerm_mssql_managed_instance_security_alert_policy. DO NOT EDIT.
package mssql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagedInstanceSecurityAlertPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagedInstanceSecurityAlertPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagedInstanceSecurityAlertPolicyConfig struct {
	DisabledAlerts any
	EmailAccountAdminsEnabled any
	EmailAddresses any
	Enabled any
	Id any
	ManagedInstanceName any
	ResourceGroupName any
	RetentionDays any
	StorageAccountAccessKey any
	StorageEndpoint any
	Timeouts any
}

var ManagedInstanceSecurityAlertPolicy = sdk.ResourceBinding{
	WireType: "azurerm_mssql_managed_instance_security_alert_policy",
	Fields: sdk.FieldMap{
		"DisabledAlerts": sdk.FieldSpec{WireName: "disabled_alerts"},
		"EmailAccountAdminsEnabled": sdk.FieldSpec{WireName: "email_account_admins_enabled"},
		"EmailAddresses": sdk.FieldSpec{WireName: "email_addresses"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ManagedInstanceName": sdk.FieldSpec{WireName: "managed_instance_name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"RetentionDays": sdk.FieldSpec{WireName: "retention_days"},
		"StorageAccountAccessKey": sdk.FieldSpec{WireName: "storage_account_access_key"},
		"StorageEndpoint": sdk.FieldSpec{WireName: "storage_endpoint"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagedInstanceSecurityAlertPolicy_TimeoutsFields,
		},
	},
}
