// Code generated by `ubx sdk gen` from azurerm_mssql_managed_instance_transparent_data_encryption. DO NOT EDIT.
package mssql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagedInstanceTransparentDataEncryption_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagedInstanceTransparentDataEncryption_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagedInstanceTransparentDataEncryptionConfig struct {
	AutoRotationEnabled any
	Id any
	KeyVaultKeyId any
	ManagedInstanceId any
	Timeouts any
}

var ManagedInstanceTransparentDataEncryption = sdk.ResourceBinding{
	WireType: "azurerm_mssql_managed_instance_transparent_data_encryption",
	Fields: sdk.FieldMap{
		"AutoRotationEnabled": sdk.FieldSpec{WireName: "auto_rotation_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"KeyVaultKeyId": sdk.FieldSpec{WireName: "key_vault_key_id"},
		"ManagedInstanceId": sdk.FieldSpec{WireName: "managed_instance_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagedInstanceTransparentDataEncryption_TimeoutsFields,
		},
	},
}
