// Code generated by `ubx sdk gen` from azurerm_mssql_managed_instance_start_stop_schedule. DO NOT EDIT.
package mssql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagedInstanceStartStopSchedule_Schedule struct {
	StartDay any
	StartTime any
	StopDay any
	StopTime any
}

type ManagedInstanceStartStopSchedule_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ManagedInstanceStartStopSchedule_ScheduleFields = sdk.FieldMap{
		"StartDay": sdk.FieldSpec{WireName: "start_day"},
		"StartTime": sdk.FieldSpec{WireName: "start_time"},
		"StopDay": sdk.FieldSpec{WireName: "stop_day"},
		"StopTime": sdk.FieldSpec{WireName: "stop_time"},
	}

var ManagedInstanceStartStopSchedule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ManagedInstanceStartStopScheduleConfig struct {
	Description any
	Id any
	ManagedInstanceId any
	TimezoneId any
	Schedule any
	Timeouts any
}

var ManagedInstanceStartStopSchedule = sdk.ResourceBinding{
	WireType: "azurerm_mssql_managed_instance_start_stop_schedule",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"ManagedInstanceId": sdk.FieldSpec{WireName: "managed_instance_id"},
		"TimezoneId": sdk.FieldSpec{WireName: "timezone_id"},
		"Schedule": sdk.FieldSpec{
			WireName: "schedule",
			Kind: "list",
			Fields: ManagedInstanceStartStopSchedule_ScheduleFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ManagedInstanceStartStopSchedule_TimeoutsFields,
		},
	},
}
