// Code generated by `ubx sdk gen` from azurerm_mssql_outbound_firewall_rule. DO NOT EDIT.
package mssql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type OutboundFirewallRule_Timeouts struct {
	Create any
	Delete any
	Read any
}

var OutboundFirewallRule_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type OutboundFirewallRuleConfig struct {
	Id any
	Name any
	ServerId any
	Timeouts any
}

var OutboundFirewallRule = sdk.ResourceBinding{
	WireType: "azurerm_mssql_outbound_firewall_rule",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ServerId": sdk.FieldSpec{WireName: "server_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: OutboundFirewallRule_TimeoutsFields,
		},
	},
}
