// Code generated by `ubx sdk gen` from azurerm_mssql_server_extended_auditing_policy. DO NOT EDIT.
package mssql

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ServerExtendedAuditingPolicy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ServerExtendedAuditingPolicy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ServerExtendedAuditingPolicyConfig struct {
	AuditActionsAndGroups any
	BlobStorageEndpoint any
	Enabled any
	Id any
	LogMonitoringEnabled any
	PredicateExpression any
	RetentionInDays any
	ServerId any
	StorageAccountAccessKey any
	StorageAccountAccessKeyIsSecondary any
	StorageAccountSubscriptionId any
	Timeouts any
}

var ServerExtendedAuditingPolicy = sdk.ResourceBinding{
	WireType: "azurerm_mssql_server_extended_auditing_policy",
	Fields: sdk.FieldMap{
		"AuditActionsAndGroups": sdk.FieldSpec{WireName: "audit_actions_and_groups"},
		"BlobStorageEndpoint": sdk.FieldSpec{WireName: "blob_storage_endpoint"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"LogMonitoringEnabled": sdk.FieldSpec{WireName: "log_monitoring_enabled"},
		"PredicateExpression": sdk.FieldSpec{WireName: "predicate_expression"},
		"RetentionInDays": sdk.FieldSpec{WireName: "retention_in_days"},
		"ServerId": sdk.FieldSpec{WireName: "server_id"},
		"StorageAccountAccessKey": sdk.FieldSpec{WireName: "storage_account_access_key"},
		"StorageAccountAccessKeyIsSecondary": sdk.FieldSpec{WireName: "storage_account_access_key_is_secondary"},
		"StorageAccountSubscriptionId": sdk.FieldSpec{WireName: "storage_account_subscription_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ServerExtendedAuditingPolicy_TimeoutsFields,
		},
	},
}
