// Code generated by `ubx sdk gen` from azurerm_kubernetes_automatic_cluster. DO NOT EDIT.
package kubernetes

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AutomaticCluster_ApiServerAccess struct {
	AuthorizedIpRanges any
	SubnetId any
}

type AutomaticCluster_HostedSystem struct {
	NodeSubnetId any
	SystemNodeSubnetId any
}

type AutomaticCluster_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type AutomaticCluster_PrivateCluster struct {
	PrivateDnsZoneId any
	PublicFullyQualifiedDomainNameEnabled any
}

type AutomaticCluster_ServiceMesh_CertificateAuthority struct {
	CertificateChainObjectName any
	CertificateObjectName any
	KeyObjectName any
	KeyVaultId any
	RootCertificateObjectName any
}

type AutomaticCluster_ServiceMesh struct {
	ExternalIngressGatewayEnabled any
	InternalIngressGatewayEnabled any
	ProxyRedirectMechanism any
	Revisions any
	CertificateAuthority any
}

type AutomaticCluster_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type AutomaticCluster_WebAppRoutingIngress_WebAppRoutingIdentity struct {
	ClientId any
	ObjectId any
	UserAssignedIdentityId any
}

type AutomaticCluster_WebAppRoutingIngress struct {
	DefaultNginxController any
	DnsZoneIds any
	IstioEnabled any
	WebAppRoutingIdentity any
}

var AutomaticCluster_ApiServerAccessFields = sdk.FieldMap{
		"AuthorizedIpRanges": sdk.FieldSpec{WireName: "authorized_ip_ranges"},
		"SubnetId": sdk.FieldSpec{WireName: "subnet_id"},
	}

var AutomaticCluster_HostedSystemFields = sdk.FieldMap{
		"NodeSubnetId": sdk.FieldSpec{WireName: "node_subnet_id"},
		"SystemNodeSubnetId": sdk.FieldSpec{WireName: "system_node_subnet_id"},
	}

var AutomaticCluster_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var AutomaticCluster_PrivateClusterFields = sdk.FieldMap{
		"PrivateDnsZoneId": sdk.FieldSpec{WireName: "private_dns_zone_id"},
		"PublicFullyQualifiedDomainNameEnabled": sdk.FieldSpec{WireName: "public_fully_qualified_domain_name_enabled"},
	}

var AutomaticCluster_ServiceMesh_CertificateAuthorityFields = sdk.FieldMap{
		"CertificateChainObjectName": sdk.FieldSpec{WireName: "certificate_chain_object_name"},
		"CertificateObjectName": sdk.FieldSpec{WireName: "certificate_object_name"},
		"KeyObjectName": sdk.FieldSpec{WireName: "key_object_name"},
		"KeyVaultId": sdk.FieldSpec{WireName: "key_vault_id"},
		"RootCertificateObjectName": sdk.FieldSpec{WireName: "root_certificate_object_name"},
	}

var AutomaticCluster_ServiceMeshFields = sdk.FieldMap{
		"ExternalIngressGatewayEnabled": sdk.FieldSpec{WireName: "external_ingress_gateway_enabled"},
		"InternalIngressGatewayEnabled": sdk.FieldSpec{WireName: "internal_ingress_gateway_enabled"},
		"ProxyRedirectMechanism": sdk.FieldSpec{WireName: "proxy_redirect_mechanism"},
		"Revisions": sdk.FieldSpec{WireName: "revisions"},
		"CertificateAuthority": sdk.FieldSpec{
			WireName: "certificate_authority",
			Kind: "list",
			Fields: AutomaticCluster_ServiceMesh_CertificateAuthorityFields,
		},
	}

var AutomaticCluster_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var AutomaticCluster_WebAppRoutingIngress_WebAppRoutingIdentityFields = sdk.FieldMap{
		"ClientId": sdk.FieldSpec{WireName: "client_id"},
		"ObjectId": sdk.FieldSpec{WireName: "object_id"},
		"UserAssignedIdentityId": sdk.FieldSpec{WireName: "user_assigned_identity_id"},
	}

var AutomaticCluster_WebAppRoutingIngressFields = sdk.FieldMap{
		"DefaultNginxController": sdk.FieldSpec{WireName: "default_nginx_controller"},
		"DnsZoneIds": sdk.FieldSpec{WireName: "dns_zone_ids"},
		"IstioEnabled": sdk.FieldSpec{WireName: "istio_enabled"},
		"WebAppRoutingIdentity": sdk.FieldSpec{
			WireName: "web_app_routing_identity",
			Kind: "list",
			Fields: AutomaticCluster_WebAppRoutingIngress_WebAppRoutingIdentityFields,
		},
	}

type AutomaticClusterConfig struct {
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	ApiServerAccess any
	HostedSystem any
	Identity any
	PrivateCluster any
	ServiceMesh any
	Timeouts any
	WebAppRoutingIngress any
}

var AutomaticCluster = sdk.ResourceBinding{
	WireType: "azurerm_kubernetes_automatic_cluster",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"ApiServerAccess": sdk.FieldSpec{
			WireName: "api_server_access",
			Kind: "list",
			Fields: AutomaticCluster_ApiServerAccessFields,
		},
		"HostedSystem": sdk.FieldSpec{
			WireName: "hosted_system",
			Kind: "list",
			Fields: AutomaticCluster_HostedSystemFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: AutomaticCluster_IdentityFields,
		},
		"PrivateCluster": sdk.FieldSpec{
			WireName: "private_cluster",
			Kind: "list",
			Fields: AutomaticCluster_PrivateClusterFields,
		},
		"ServiceMesh": sdk.FieldSpec{
			WireName: "service_mesh",
			Kind: "list",
			Fields: AutomaticCluster_ServiceMeshFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AutomaticCluster_TimeoutsFields,
		},
		"WebAppRoutingIngress": sdk.FieldSpec{
			WireName: "web_app_routing_ingress",
			Kind: "list",
			Fields: AutomaticCluster_WebAppRoutingIngressFields,
		},
	},
}
