// Code generated by `ubx sdk gen` from azurerm_kubernetes_fleet_update_strategy. DO NOT EDIT.
package kubernetes

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type FleetUpdateStrategy_Stage_Group struct {
	Name any
}

type FleetUpdateStrategy_Stage struct {
	AfterStageWaitInSeconds any
	Name any
	Group any
}

type FleetUpdateStrategy_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var FleetUpdateStrategy_Stage_GroupFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
	}

var FleetUpdateStrategy_StageFields = sdk.FieldMap{
		"AfterStageWaitInSeconds": sdk.FieldSpec{WireName: "after_stage_wait_in_seconds"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Group": sdk.FieldSpec{
			WireName: "group",
			Kind: "list",
			Fields: FleetUpdateStrategy_Stage_GroupFields,
		},
	}

var FleetUpdateStrategy_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type FleetUpdateStrategyConfig struct {
	Id any
	KubernetesFleetManagerId any
	Name any
	Stage any
	Timeouts any
}

var FleetUpdateStrategy = sdk.ResourceBinding{
	WireType: "azurerm_kubernetes_fleet_update_strategy",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"KubernetesFleetManagerId": sdk.FieldSpec{WireName: "kubernetes_fleet_manager_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Stage": sdk.FieldSpec{
			WireName: "stage",
			Kind: "list",
			Fields: FleetUpdateStrategy_StageFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: FleetUpdateStrategy_TimeoutsFields,
		},
	},
}
