// Code generated by `ubx sdk gen` from azurerm_load_test. DO NOT EDIT.
package load

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type Test_Encryption_Identity struct {
	IdentityId any
	Type any
}

type Test_Encryption struct {
	KeyUrl any
	Identity any
}

type Test_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type Test_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var Test_Encryption_IdentityFields = sdk.FieldMap{
		"IdentityId": sdk.FieldSpec{WireName: "identity_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Test_EncryptionFields = sdk.FieldMap{
		"KeyUrl": sdk.FieldSpec{WireName: "key_url"},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Test_Encryption_IdentityFields,
		},
	}

var Test_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var Test_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type TestConfig struct {
	Description any
	Id any
	Location any
	Name any
	ResourceGroupName any
	Tags any
	Encryption any
	Identity any
	Timeouts any
}

var Test = sdk.ResourceBinding{
	WireType: "azurerm_load_test",
	Fields: sdk.FieldMap{
		"Description": sdk.FieldSpec{WireName: "description"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"Encryption": sdk.FieldSpec{
			WireName: "encryption",
			Kind: "list",
			Fields: Test_EncryptionFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: Test_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: Test_TimeoutsFields,
		},
	},
}
