// Code generated by `ubx sdk gen` from azurerm_cognitive_account_connection_custom_keys. DO NOT EDIT.
package cognitive

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type AccountConnectionCustomKeys_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var AccountConnectionCustomKeys_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type AccountConnectionCustomKeysConfig struct {
	Category any
	CognitiveAccountId any
	CustomKeys any
	Id any
	Metadata any
	Name any
	Target any
	Timeouts any
}

var AccountConnectionCustomKeys = sdk.ResourceBinding{
	WireType: "azurerm_cognitive_account_connection_custom_keys",
	Fields: sdk.FieldMap{
		"Category": sdk.FieldSpec{WireName: "category"},
		"CognitiveAccountId": sdk.FieldSpec{WireName: "cognitive_account_id"},
		"CustomKeys": sdk.FieldSpec{WireName: "custom_keys"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Metadata": sdk.FieldSpec{WireName: "metadata"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Target": sdk.FieldSpec{WireName: "target"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: AccountConnectionCustomKeys_TimeoutsFields,
		},
	},
}
