// Code generated by `ubx sdk gen` from azurerm_spring_cloud_gateway_route_config. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudGatewayRouteConfig_OpenApi struct {
	Uri any
}

type CloudGatewayRouteConfig_Route struct {
	ClassificationTags any
	Description any
	Filters any
	Order any
	Predicates any
	SsoValidationEnabled any
	Title any
	TokenRelay any
	Uri any
}

type CloudGatewayRouteConfig_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CloudGatewayRouteConfig_OpenApiFields = sdk.FieldMap{
		"Uri": sdk.FieldSpec{WireName: "uri"},
	}

var CloudGatewayRouteConfig_RouteFields = sdk.FieldMap{
		"ClassificationTags": sdk.FieldSpec{WireName: "classification_tags"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"Filters": sdk.FieldSpec{WireName: "filters"},
		"Order": sdk.FieldSpec{WireName: "order"},
		"Predicates": sdk.FieldSpec{WireName: "predicates"},
		"SsoValidationEnabled": sdk.FieldSpec{WireName: "sso_validation_enabled"},
		"Title": sdk.FieldSpec{WireName: "title"},
		"TokenRelay": sdk.FieldSpec{WireName: "token_relay"},
		"Uri": sdk.FieldSpec{WireName: "uri"},
	}

var CloudGatewayRouteConfig_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CloudGatewayRouteConfigConfig struct {
	Filters any
	Id any
	Name any
	Predicates any
	Protocol any
	SpringCloudAppId any
	SpringCloudGatewayId any
	SsoValidationEnabled any
	OpenApi any
	Route any
	Timeouts any
}

var CloudGatewayRouteConfig = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_gateway_route_config",
	Fields: sdk.FieldMap{
		"Filters": sdk.FieldSpec{WireName: "filters"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Predicates": sdk.FieldSpec{WireName: "predicates"},
		"Protocol": sdk.FieldSpec{WireName: "protocol"},
		"SpringCloudAppId": sdk.FieldSpec{WireName: "spring_cloud_app_id"},
		"SpringCloudGatewayId": sdk.FieldSpec{WireName: "spring_cloud_gateway_id"},
		"SsoValidationEnabled": sdk.FieldSpec{WireName: "sso_validation_enabled"},
		"OpenApi": sdk.FieldSpec{
			WireName: "open_api",
			Kind: "list",
			Fields: CloudGatewayRouteConfig_OpenApiFields,
		},
		"Route": sdk.FieldSpec{
			WireName: "route",
			Kind: "set",
			Fields: CloudGatewayRouteConfig_RouteFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudGatewayRouteConfig_TimeoutsFields,
		},
	},
}
