// Code generated by `ubx sdk gen` from azurerm_spring_cloud_service. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudService_ConfigServerGitSetting_HttpBasicAuth struct {
	Password any
	Username any
}

type CloudService_ConfigServerGitSetting_Repository_SshAuth struct {
	HostKey any
	HostKeyAlgorithm any
	PrivateKey any
	StrictHostKeyCheckingEnabled any
}

type CloudService_ConfigServerGitSetting_Repository struct {
	Label any
	Name any
	Pattern any
	SearchPaths any
	Uri any
	HttpBasicAuth any
	SshAuth any
}

type CloudService_ConfigServerGitSetting struct {
	Label any
	SearchPaths any
	Uri any
	HttpBasicAuth any
	Repository any
	SshAuth any
}

type CloudService_ContainerRegistry struct {
	Name any
	Password any
	Server any
	Username any
}

type CloudService_DefaultBuildService struct {
	ContainerRegistryName any
}

type CloudService_Marketplace struct {
	Plan any
	Product any
	Publisher any
}

type CloudService_Network struct {
	AppNetworkResourceGroup any
	AppSubnetId any
	CidrRanges any
	OutboundType any
	ReadTimeoutSeconds any
	ServiceRuntimeNetworkResourceGroup any
	ServiceRuntimeSubnetId any
}

type CloudService_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

type CloudService_Trace struct {
	ConnectionString any
	SampleRate any
}

var CloudService_ConfigServerGitSetting_HttpBasicAuthFields = sdk.FieldMap{
		"Password": sdk.FieldSpec{WireName: "password"},
		"Username": sdk.FieldSpec{WireName: "username"},
	}

var CloudService_ConfigServerGitSetting_Repository_SshAuthFields = sdk.FieldMap{
		"HostKey": sdk.FieldSpec{WireName: "host_key"},
		"HostKeyAlgorithm": sdk.FieldSpec{WireName: "host_key_algorithm"},
		"PrivateKey": sdk.FieldSpec{WireName: "private_key"},
		"StrictHostKeyCheckingEnabled": sdk.FieldSpec{WireName: "strict_host_key_checking_enabled"},
	}

var CloudService_ConfigServerGitSetting_RepositoryFields = sdk.FieldMap{
		"Label": sdk.FieldSpec{WireName: "label"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"Pattern": sdk.FieldSpec{WireName: "pattern"},
		"SearchPaths": sdk.FieldSpec{WireName: "search_paths"},
		"Uri": sdk.FieldSpec{WireName: "uri"},
		"HttpBasicAuth": sdk.FieldSpec{
			WireName: "http_basic_auth",
			Kind: "list",
			Fields: CloudService_ConfigServerGitSetting_HttpBasicAuthFields,
		},
		"SshAuth": sdk.FieldSpec{
			WireName: "ssh_auth",
			Kind: "list",
			Fields: CloudService_ConfigServerGitSetting_Repository_SshAuthFields,
		},
	}

var CloudService_ConfigServerGitSettingFields = sdk.FieldMap{
		"Label": sdk.FieldSpec{WireName: "label"},
		"SearchPaths": sdk.FieldSpec{WireName: "search_paths"},
		"Uri": sdk.FieldSpec{WireName: "uri"},
		"HttpBasicAuth": sdk.FieldSpec{
			WireName: "http_basic_auth",
			Kind: "list",
			Fields: CloudService_ConfigServerGitSetting_HttpBasicAuthFields,
		},
		"Repository": sdk.FieldSpec{
			WireName: "repository",
			Kind: "list",
			Fields: CloudService_ConfigServerGitSetting_RepositoryFields,
		},
		"SshAuth": sdk.FieldSpec{
			WireName: "ssh_auth",
			Kind: "list",
			Fields: CloudService_ConfigServerGitSetting_Repository_SshAuthFields,
		},
	}

var CloudService_ContainerRegistryFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Password": sdk.FieldSpec{WireName: "password"},
		"Server": sdk.FieldSpec{WireName: "server"},
		"Username": sdk.FieldSpec{WireName: "username"},
	}

var CloudService_DefaultBuildServiceFields = sdk.FieldMap{
		"ContainerRegistryName": sdk.FieldSpec{WireName: "container_registry_name"},
	}

var CloudService_MarketplaceFields = sdk.FieldMap{
		"Plan": sdk.FieldSpec{WireName: "plan"},
		"Product": sdk.FieldSpec{WireName: "product"},
		"Publisher": sdk.FieldSpec{WireName: "publisher"},
	}

var CloudService_NetworkFields = sdk.FieldMap{
		"AppNetworkResourceGroup": sdk.FieldSpec{WireName: "app_network_resource_group"},
		"AppSubnetId": sdk.FieldSpec{WireName: "app_subnet_id"},
		"CidrRanges": sdk.FieldSpec{WireName: "cidr_ranges"},
		"OutboundType": sdk.FieldSpec{WireName: "outbound_type"},
		"ReadTimeoutSeconds": sdk.FieldSpec{WireName: "read_timeout_seconds"},
		"ServiceRuntimeNetworkResourceGroup": sdk.FieldSpec{WireName: "service_runtime_network_resource_group"},
		"ServiceRuntimeSubnetId": sdk.FieldSpec{WireName: "service_runtime_subnet_id"},
	}

var CloudService_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

var CloudService_TraceFields = sdk.FieldMap{
		"ConnectionString": sdk.FieldSpec{WireName: "connection_string"},
		"SampleRate": sdk.FieldSpec{WireName: "sample_rate"},
	}

type CloudServiceConfig struct {
	BuildAgentPoolSize any
	Id any
	Location any
	LogStreamPublicEndpointEnabled any
	ManagedEnvironmentId any
	Name any
	ResourceGroupName any
	ServiceRegistryEnabled any
	SkuName any
	SkuTier any
	Tags any
	ZoneRedundant any
	ConfigServerGitSetting any
	ContainerRegistry any
	DefaultBuildService any
	Marketplace any
	Network any
	Timeouts any
	Trace any
}

var CloudService = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_service",
	Fields: sdk.FieldMap{
		"BuildAgentPoolSize": sdk.FieldSpec{WireName: "build_agent_pool_size"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"LogStreamPublicEndpointEnabled": sdk.FieldSpec{WireName: "log_stream_public_endpoint_enabled"},
		"ManagedEnvironmentId": sdk.FieldSpec{WireName: "managed_environment_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ServiceRegistryEnabled": sdk.FieldSpec{WireName: "service_registry_enabled"},
		"SkuName": sdk.FieldSpec{WireName: "sku_name"},
		"SkuTier": sdk.FieldSpec{WireName: "sku_tier"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"ZoneRedundant": sdk.FieldSpec{WireName: "zone_redundant"},
		"ConfigServerGitSetting": sdk.FieldSpec{
			WireName: "config_server_git_setting",
			Kind: "list",
			Fields: CloudService_ConfigServerGitSettingFields,
		},
		"ContainerRegistry": sdk.FieldSpec{
			WireName: "container_registry",
			Kind: "list",
			Fields: CloudService_ContainerRegistryFields,
		},
		"DefaultBuildService": sdk.FieldSpec{
			WireName: "default_build_service",
			Kind: "list",
			Fields: CloudService_DefaultBuildServiceFields,
		},
		"Marketplace": sdk.FieldSpec{
			WireName: "marketplace",
			Kind: "list",
			Fields: CloudService_MarketplaceFields,
		},
		"Network": sdk.FieldSpec{
			WireName: "network",
			Kind: "list",
			Fields: CloudService_NetworkFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudService_TimeoutsFields,
		},
		"Trace": sdk.FieldSpec{
			WireName: "trace",
			Kind: "list",
			Fields: CloudService_TraceFields,
		},
	},
}
