// Code generated by `ubx sdk gen` from azurerm_spring_cloud_java_deployment. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudJavaDeployment_Quota struct {
	Cpu any
	Memory any
}

type CloudJavaDeployment_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CloudJavaDeployment_QuotaFields = sdk.FieldMap{
		"Cpu": sdk.FieldSpec{WireName: "cpu"},
		"Memory": sdk.FieldSpec{WireName: "memory"},
	}

var CloudJavaDeployment_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CloudJavaDeploymentConfig struct {
	EnvironmentVariables any
	Id any
	InstanceCount any
	JvmOptions any
	Name any
	RuntimeVersion any
	SpringCloudAppId any
	Quota any
	Timeouts any
}

var CloudJavaDeployment = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_java_deployment",
	Fields: sdk.FieldMap{
		"EnvironmentVariables": sdk.FieldSpec{WireName: "environment_variables"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"InstanceCount": sdk.FieldSpec{WireName: "instance_count"},
		"JvmOptions": sdk.FieldSpec{WireName: "jvm_options"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"RuntimeVersion": sdk.FieldSpec{WireName: "runtime_version"},
		"SpringCloudAppId": sdk.FieldSpec{WireName: "spring_cloud_app_id"},
		"Quota": sdk.FieldSpec{
			WireName: "quota",
			Kind: "list",
			Fields: CloudJavaDeployment_QuotaFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudJavaDeployment_TimeoutsFields,
		},
	},
}
