// Code generated by `ubx sdk gen` from azurerm_spring_cloud_elastic_application_performance_monitoring. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudElasticApplicationPerformanceMonitoring_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CloudElasticApplicationPerformanceMonitoring_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CloudElasticApplicationPerformanceMonitoringConfig struct {
	ApplicationPackages any
	GloballyEnabled any
	Id any
	Name any
	ServerUrl any
	ServiceName any
	SpringCloudServiceId any
	Timeouts any
}

var CloudElasticApplicationPerformanceMonitoring = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_elastic_application_performance_monitoring",
	Fields: sdk.FieldMap{
		"ApplicationPackages": sdk.FieldSpec{WireName: "application_packages"},
		"GloballyEnabled": sdk.FieldSpec{WireName: "globally_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ServerUrl": sdk.FieldSpec{WireName: "server_url"},
		"ServiceName": sdk.FieldSpec{WireName: "service_name"},
		"SpringCloudServiceId": sdk.FieldSpec{WireName: "spring_cloud_service_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudElasticApplicationPerformanceMonitoring_TimeoutsFields,
		},
	},
}
