// Code generated by `ubx sdk gen` from azurerm_spring_cloud_new_relic_application_performance_monitoring. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudNewRelicApplicationPerformanceMonitoring_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CloudNewRelicApplicationPerformanceMonitoring_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CloudNewRelicApplicationPerformanceMonitoringConfig struct {
	AgentEnabled any
	AppName any
	AppServerPort any
	AuditModeEnabled any
	AutoAppNamingEnabled any
	AutoTransactionNamingEnabled any
	CustomTracingEnabled any
	GloballyEnabled any
	Id any
	Labels any
	LicenseKey any
	Name any
	SpringCloudServiceId any
	Timeouts any
}

var CloudNewRelicApplicationPerformanceMonitoring = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_new_relic_application_performance_monitoring",
	Fields: sdk.FieldMap{
		"AgentEnabled": sdk.FieldSpec{WireName: "agent_enabled"},
		"AppName": sdk.FieldSpec{WireName: "app_name"},
		"AppServerPort": sdk.FieldSpec{WireName: "app_server_port"},
		"AuditModeEnabled": sdk.FieldSpec{WireName: "audit_mode_enabled"},
		"AutoAppNamingEnabled": sdk.FieldSpec{WireName: "auto_app_naming_enabled"},
		"AutoTransactionNamingEnabled": sdk.FieldSpec{WireName: "auto_transaction_naming_enabled"},
		"CustomTracingEnabled": sdk.FieldSpec{WireName: "custom_tracing_enabled"},
		"GloballyEnabled": sdk.FieldSpec{WireName: "globally_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Labels": sdk.FieldSpec{WireName: "labels"},
		"LicenseKey": sdk.FieldSpec{WireName: "license_key"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SpringCloudServiceId": sdk.FieldSpec{WireName: "spring_cloud_service_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudNewRelicApplicationPerformanceMonitoring_TimeoutsFields,
		},
	},
}
