// Code generated by `ubx sdk gen` from azurerm_spring_cloud_dynatrace_application_performance_monitoring. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudDynatraceApplicationPerformanceMonitoring_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CloudDynatraceApplicationPerformanceMonitoring_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CloudDynatraceApplicationPerformanceMonitoringConfig struct {
	ApiToken any
	ApiUrl any
	ConnectionPoint any
	EnvironmentId any
	GloballyEnabled any
	Id any
	Name any
	SpringCloudServiceId any
	Tenant any
	TenantToken any
	Timeouts any
}

var CloudDynatraceApplicationPerformanceMonitoring = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_dynatrace_application_performance_monitoring",
	Fields: sdk.FieldMap{
		"ApiToken": sdk.FieldSpec{WireName: "api_token"},
		"ApiUrl": sdk.FieldSpec{WireName: "api_url"},
		"ConnectionPoint": sdk.FieldSpec{WireName: "connection_point"},
		"EnvironmentId": sdk.FieldSpec{WireName: "environment_id"},
		"GloballyEnabled": sdk.FieldSpec{WireName: "globally_enabled"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SpringCloudServiceId": sdk.FieldSpec{WireName: "spring_cloud_service_id"},
		"Tenant": sdk.FieldSpec{WireName: "tenant"},
		"TenantToken": sdk.FieldSpec{WireName: "tenant_token"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudDynatraceApplicationPerformanceMonitoring_TimeoutsFields,
		},
	},
}
