// Code generated by `ubx sdk gen` from azurerm_spring_cloud_build_pack_binding. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudBuildPackBinding_Launch struct {
	Properties any
	Secrets any
}

type CloudBuildPackBinding_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var CloudBuildPackBinding_LaunchFields = sdk.FieldMap{
		"Properties": sdk.FieldSpec{WireName: "properties"},
		"Secrets": sdk.FieldSpec{WireName: "secrets"},
	}

var CloudBuildPackBinding_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type CloudBuildPackBindingConfig struct {
	BindingType any
	Id any
	Name any
	SpringCloudBuilderId any
	Launch any
	Timeouts any
}

var CloudBuildPackBinding = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_build_pack_binding",
	Fields: sdk.FieldMap{
		"BindingType": sdk.FieldSpec{WireName: "binding_type"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SpringCloudBuilderId": sdk.FieldSpec{WireName: "spring_cloud_builder_id"},
		"Launch": sdk.FieldSpec{
			WireName: "launch",
			Kind: "list",
			Fields: CloudBuildPackBinding_LaunchFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudBuildPackBinding_TimeoutsFields,
		},
	},
}
