// Code generated by `ubx sdk gen` from azurerm_spring_cloud_accelerator. DO NOT EDIT.
package spring

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type CloudAccelerator_Timeouts struct {
	Create any
	Delete any
	Read any
}

var CloudAccelerator_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type CloudAcceleratorConfig struct {
	Id any
	Name any
	SpringCloudServiceId any
	Timeouts any
}

var CloudAccelerator = sdk.ResourceBinding{
	WireType: "azurerm_spring_cloud_accelerator",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"SpringCloudServiceId": sdk.FieldSpec{WireName: "spring_cloud_service_id"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: CloudAccelerator_TimeoutsFields,
		},
	},
}
