// Code generated by `ubx sdk gen` from azurerm_monitor_private_link_scoped_service. DO NOT EDIT.
package monitor

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type PrivateLinkScopedService_Timeouts struct {
	Create any
	Delete any
	Read any
}

var PrivateLinkScopedService_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
	}

type PrivateLinkScopedServiceConfig struct {
	Id any
	LinkedResourceId any
	Name any
	ResourceGroupName any
	ScopeName any
	Timeouts any
}

var PrivateLinkScopedService = sdk.ResourceBinding{
	WireType: "azurerm_monitor_private_link_scoped_service",
	Fields: sdk.FieldMap{
		"Id": sdk.FieldSpec{WireName: "id"},
		"LinkedResourceId": sdk.FieldSpec{WireName: "linked_resource_id"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"ScopeName": sdk.FieldSpec{WireName: "scope_name"},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: PrivateLinkScopedService_TimeoutsFields,
		},
	},
}
