// Code generated by `ubx sdk gen` from azurerm_monitor_scheduled_query_rules_alert_v2. DO NOT EDIT.
package monitor

import sdk "github.com/ubiquex/ubx-sdk-go/runtime"

type ScheduledQueryRulesAlertV2_Action struct {
	ActionGroups any
	CustomProperties any
	EmailSubject any
}

type ScheduledQueryRulesAlertV2_Criteria_Dimension struct {
	Name any
	Operator any
	Values any
}

type ScheduledQueryRulesAlertV2_Criteria_FailingPeriods struct {
	MinimumFailingPeriodsToTriggerAlert any
	NumberOfEvaluationPeriods any
}

type ScheduledQueryRulesAlertV2_Criteria struct {
	MetricMeasureColumn any
	Operator any
	Query any
	ResourceIdColumn any
	Threshold any
	TimeAggregationMethod any
	Dimension any
	FailingPeriods any
}

type ScheduledQueryRulesAlertV2_Identity struct {
	IdentityIds any
	PrincipalId any
	TenantId any
	Type any
}

type ScheduledQueryRulesAlertV2_Timeouts struct {
	Create any
	Delete any
	Read any
	Update any
}

var ScheduledQueryRulesAlertV2_ActionFields = sdk.FieldMap{
		"ActionGroups": sdk.FieldSpec{WireName: "action_groups"},
		"CustomProperties": sdk.FieldSpec{WireName: "custom_properties"},
		"EmailSubject": sdk.FieldSpec{WireName: "email_subject"},
	}

var ScheduledQueryRulesAlertV2_Criteria_DimensionFields = sdk.FieldMap{
		"Name": sdk.FieldSpec{WireName: "name"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Values": sdk.FieldSpec{WireName: "values"},
	}

var ScheduledQueryRulesAlertV2_Criteria_FailingPeriodsFields = sdk.FieldMap{
		"MinimumFailingPeriodsToTriggerAlert": sdk.FieldSpec{WireName: "minimum_failing_periods_to_trigger_alert"},
		"NumberOfEvaluationPeriods": sdk.FieldSpec{WireName: "number_of_evaluation_periods"},
	}

var ScheduledQueryRulesAlertV2_CriteriaFields = sdk.FieldMap{
		"MetricMeasureColumn": sdk.FieldSpec{WireName: "metric_measure_column"},
		"Operator": sdk.FieldSpec{WireName: "operator"},
		"Query": sdk.FieldSpec{WireName: "query"},
		"ResourceIdColumn": sdk.FieldSpec{WireName: "resource_id_column"},
		"Threshold": sdk.FieldSpec{WireName: "threshold"},
		"TimeAggregationMethod": sdk.FieldSpec{WireName: "time_aggregation_method"},
		"Dimension": sdk.FieldSpec{
			WireName: "dimension",
			Kind: "list",
			Fields: ScheduledQueryRulesAlertV2_Criteria_DimensionFields,
		},
		"FailingPeriods": sdk.FieldSpec{
			WireName: "failing_periods",
			Kind: "list",
			Fields: ScheduledQueryRulesAlertV2_Criteria_FailingPeriodsFields,
		},
	}

var ScheduledQueryRulesAlertV2_IdentityFields = sdk.FieldMap{
		"IdentityIds": sdk.FieldSpec{WireName: "identity_ids"},
		"PrincipalId": sdk.FieldSpec{WireName: "principal_id"},
		"TenantId": sdk.FieldSpec{WireName: "tenant_id"},
		"Type": sdk.FieldSpec{WireName: "type"},
	}

var ScheduledQueryRulesAlertV2_TimeoutsFields = sdk.FieldMap{
		"Create": sdk.FieldSpec{WireName: "create"},
		"Delete": sdk.FieldSpec{WireName: "delete"},
		"Read": sdk.FieldSpec{WireName: "read"},
		"Update": sdk.FieldSpec{WireName: "update"},
	}

type ScheduledQueryRulesAlertV2Config struct {
	AutoMitigationEnabled any
	Description any
	DisplayName any
	Enabled any
	EvaluationFrequency any
	Id any
	Location any
	MuteActionsAfterAlertDuration any
	Name any
	QueryTimeRangeOverride any
	ResourceGroupName any
	Scopes any
	Severity any
	SkipQueryValidation any
	Tags any
	TargetResourceTypes any
	WindowDuration any
	WorkspaceAlertsStorageEnabled any
	Action any
	Criteria any
	Identity any
	Timeouts any
}

var ScheduledQueryRulesAlertV2 = sdk.ResourceBinding{
	WireType: "azurerm_monitor_scheduled_query_rules_alert_v2",
	Fields: sdk.FieldMap{
		"AutoMitigationEnabled": sdk.FieldSpec{WireName: "auto_mitigation_enabled"},
		"Description": sdk.FieldSpec{WireName: "description"},
		"DisplayName": sdk.FieldSpec{WireName: "display_name"},
		"Enabled": sdk.FieldSpec{WireName: "enabled"},
		"EvaluationFrequency": sdk.FieldSpec{WireName: "evaluation_frequency"},
		"Id": sdk.FieldSpec{WireName: "id"},
		"Location": sdk.FieldSpec{WireName: "location"},
		"MuteActionsAfterAlertDuration": sdk.FieldSpec{WireName: "mute_actions_after_alert_duration"},
		"Name": sdk.FieldSpec{WireName: "name"},
		"QueryTimeRangeOverride": sdk.FieldSpec{WireName: "query_time_range_override"},
		"ResourceGroupName": sdk.FieldSpec{WireName: "resource_group_name"},
		"Scopes": sdk.FieldSpec{WireName: "scopes"},
		"Severity": sdk.FieldSpec{WireName: "severity"},
		"SkipQueryValidation": sdk.FieldSpec{WireName: "skip_query_validation"},
		"Tags": sdk.FieldSpec{WireName: "tags"},
		"TargetResourceTypes": sdk.FieldSpec{WireName: "target_resource_types"},
		"WindowDuration": sdk.FieldSpec{WireName: "window_duration"},
		"WorkspaceAlertsStorageEnabled": sdk.FieldSpec{WireName: "workspace_alerts_storage_enabled"},
		"Action": sdk.FieldSpec{
			WireName: "action",
			Kind: "list",
			Fields: ScheduledQueryRulesAlertV2_ActionFields,
		},
		"Criteria": sdk.FieldSpec{
			WireName: "criteria",
			Kind: "list",
			Fields: ScheduledQueryRulesAlertV2_CriteriaFields,
		},
		"Identity": sdk.FieldSpec{
			WireName: "identity",
			Kind: "list",
			Fields: ScheduledQueryRulesAlertV2_IdentityFields,
		},
		"Timeouts": sdk.FieldSpec{
			WireName: "timeouts",
			Kind: "object",
			Fields: ScheduledQueryRulesAlertV2_TimeoutsFields,
		},
	},
}
